AVRLibs: hardware/adc.h File Reference
adc.h File Reference
AVR simple ADC library.
#include <hardware/adc_defs.h>
Functions
void adc_enable (void)
Enable the ADC converter.
void adc_disable (void)
Disable the ADC converter.
void adc_configure (adc_ref_t ref, bool hi_speed)
Set the configuration of the ADC.
uint16_t adc_read (pins_t pin)
Get the analog value from a given ADC line.
uint16_t adc_temp (void)
If available, return the value of the temperature sensor of the board.
Detailed Description
AVR simple ADC library.
#include "hardware/adc.h"
Definition in file adc.h.
Function Documentation
adc_enable()
void adc_enable (void)
Enable the ADC converter.
Definition at line 56 of file adc.cpp.
References adc_csra_t::aden, and adc_ctrla_t::field.
                       {
     _ctrla->field.aden = true;
 }
adc_disable()
void adc_disable (void)
Disable the ADC converter.
Definition at line 60 of file adc.cpp.
References adc_csra_t::aden, and adc_ctrla_t::field.
{
     _ctrla->field.aden = false;
 }
adc_configure()
void adc_configure (adc_ref_t ref, bool hi_speed)
Set the configuration of the ADC.
Parameters
ref Set the ADC converter reference.
hi_speed Enable, if available, the high-speed mode.
Definition at line 64 of file adc.cpp.
References adc_prescaler(), adc_csrb_t::adhsm, adc_csra_t::adps, adc_mux_t::field, adc_ctrla_t::field, adc_ctrlb_t::field, adc_mux_t::raw, adc_ctrla_t::raw, adc_ctrlb_t::raw, and adc_admux_t::ref.
{
     // Set ADC reference (by default ADLAR is disabled and ADC0 is selected)
     _admux->raw = 0x00;
     _admux->field.ref = ref;
     // Enable ADC and set the prescaler (by default ADC has no trigger and
     // is not interrupt driven).
     _ctrla->raw = 0x00;
     _ctrla->field.adps = adc_prescaler();
     // Set if the ADC will work on high speed (only if the mcu supports it.
     // by default the ADC is in free running mode and the analog comparator
     // multiplexer is disabled).
     _ctrlb->raw = 0x00;
     _ctrlb->field.adhsm = hi_speed;
 }
adc_read()
uint16_t adc_read (pins_t pin)
Get the analog value from a given ADC line.
Parameters
pin Board pin value.
Returns
ADC value.
Definition at line 79 of file adc.cpp.
References adc_line_from_pin(), and adc_value().
{
     uint8_t code = adc_line_from_pin(pin);
     return adc_value(code);
 }
adc_temp()
uint16_t adc_temp (void)
If available, return the value of the temperature sensor of the board.
Returns
Temperature sensor value.
Definition at line 84 of file adc.cpp.
References adc_temp_sensor_line(), and adc_value().
{
     uint8_t code = adc_temp_sensor_line();
     return adc_value(code);
 }