AVRLibs: base/base.h File Reference
base.h File Reference
Basic definitions.
#include <stdio.h>
#include <stdlib.h>
#include <stdbool.h>
#include <string.h>
#include <math.h>
#include <base/fix_cpp.h>
Classes
struct u16_u8_t
Used to represent a 16bit value with 8bit values.
struct u32_u8_t
Used to represent a 32bit value with 8bit values.
union bk_u16_u8_t
Simplify conversions between 16bit and 8bit values.
union bk_u32_u8_t
Simplify conversions between 32bit and 8bit values.
Macros
#define _BV(x) (1 << (x))
#define LSB_U16(x) ((x) & 0x00FF)
#define MSB_U16(x) LSB_U16((x) >> 8)
#define BYTES_U16(x) {LSB_U16(x), MSB_U16(x)}
#define MAKE_U16(msb, lsb)
#define LSB_U32(x) ((x) & 0x000000FF)
#define B1_U32(x) LSB_U32((x) >> 8)
#define B2_U32(x) LSB_U32((x) >> 16)
#define MSB_U32(x) LSB_U32((x) >> 24)
#define BYTES_U32(x) {LSB_U16(x), B1_U32(x), B2_U32(x), MSB_U16(x)}
#define MAKE_U32(msb, b2, b1, lsb)
#define PI 3.14159265358979323846
#define RAD_2_DEG 57.29577951308232087679
#define DEG_2_RAD 0.01745329251994329576
#define RAD(deg) ((deg) * DEG_2_RAD)
#define DEG(rad) ((rad) * RAD_2_DEG)
#define min(a, b) (((a)<(b))?(a):(b))
#define max(a, b) (((a)<(b))?(a):(b))
#define abs(x) (((x)>=0)?(x):-(x))
Typedefs
typedef void(* fun_ptr_vd_vd) (void)
typedef void(* fun_ptr_vd_u8) (uint8_t)
typedef uint8_t(* fun_ptr_u8_u8) (uint8_t)
Functions
uint16_t bswap16 (uint16_t val)
Return the bytes inverted, for example 0xaabb becomes 0xbbaa.
u16_u8_t break_uint16 (uint16_t val)
Breaks a 16bit value into 8bit values.
uint16_t make_uint16 (int16_t val)
uint16_t make_uint16 (uint16_t val)
uint16_t make_uint16 (u16_u8_t val)
uint16_t make_uint16 (uint8_t msb, uint8_t lsb)
uint32_t bswap32 (uint32_t val)
Similar to bswap16() but for 32bit.
u32_u8_t break_uint32 (uint32_t val)
Similar to break_uint16() but for 32bit.
uint32_t make_uint32 (int32_t val)
uint16_t make_uint16 (uint32_t val)
uint32_t make_uint32 (u32_u8_t val)
uint32_t make_uint32 (uint8_t msb, uint8_t b2, uint8_t b1, uint8_t lsb)
uint8_t get_field_mask (uint8_t pos, uint8_t len)
Get the field mask.
uint8_t get_field_value (uint8_t reg, uint8_t pos, uint8_t len)
Get a field value from a register.
uint8_t set_field_value (uint8_t reg, uint8_t pos, uint8_t len, uint8_t value)
Set a field value on a register.
void fun_vd_vd_dummy (void)
Dummy function, does nothing. Used to initialize fun_ptr_vd_vd pointers.
void fun_vd_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_vd_u8 pointers.
uint8_t fun_u8_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_u8_u8 pointers.
Detailed Description
Basic definitions.
#include "base/base.h"
Definition in file base.h.
Class Documentation
u16_u8_t
struct u16_u8_t
Used to represent a 16bit value with 8bit values.
Definition at line 56 of file base.h.
Class Members
uint8_t lsb LSB byte.
uint8_t msb MSB byte.
u32_u8_t
struct u32_u8_t
Used to represent a 32bit value with 8bit values.
Definition at line 65 of file base.h.
Class Members
uint8_t lsb LSB byte.
uint8_t b1 Mid LSB byte.
uint8_t b2 Mid MSB byte.
uint8_t msb MSB byte.
bk_u16_u8_t
union bk_u16_u8_t
Simplify conversions between 16bit and 8bit values.
Definition at line 76 of file base.h.
Class Members
u16_u8_t u8 u16_u8_t value
uint16_t u16 16bit value
bk_u32_u8_t
union bk_u32_u8_t
Simplify conversions between 32bit and 8bit values.
Definition at line 85 of file base.h.
Class Members
u32_u8_t u8 u32_u8_t value
uint32_t u32 32bit value
Macro Definition Documentation
_BV
#define _BV (x) (1 << (x))
Definition at line 22 of file base.h.
Referenced by SPI::disable(), TWI::disable(), TWI::enable(), SPI::enable(), get_micros(), int_ext_attach(), int_ext_detach(), int_pc_attach(), int_pc_detach(), TWI::release_bus(), TWI::reply(), TWI::start(), TWI::state_machine(), and TWI::stop().
LSB_U16
#define LSB_U16 (x) ((x) & 0x00FF)
Definition at line 25 of file base.h.
MSB_U16
#define MSB_U16 (x) LSB_U16((x) >> 8)
Definition at line 27 of file base.h.
BYTES_U16
#define BYTES_U16 (x) {LSB_U16(x), MSB_U16(x)}
Definition at line 29 of file base.h.
MAKE_U16
#define MAKE_U16 (msb, lsb)
Value:
((uint16_t)msb << 8) |  \
    (uint16_t) lsb
Definition at line 31 of file base.h.
Referenced by make_uint16().
LSB_U32
#define LSB_U32 (x) ((x) & 0x000000FF)
Definition at line 35 of file base.h.
B1_U32
#define B1_U32 (x) LSB_U32((x) >> 8)
Definition at line 37 of file base.h.
B2_U32
#define B2_U32 (x) LSB_U32((x) >> 16)
Definition at line 39 of file base.h.
MSB_U32
#define MSB_U32 (x) LSB_U32((x) >> 24)
Definition at line 41 of file base.h.
BYTES_U32
#define BYTES_U32 (x) {LSB_U16(x), B1_U32(x), B2_U32(x), MSB_U16(x)}
Definition at line 43 of file base.h.
MAKE_U32
#define MAKE_U32 (msb, b2, b1, lsb)
Value:
((uint32_t)msb << 24) | \
    ((uint32_t)b2 << 16)  | \
    ((uint32_t)b1 << 8)   | \
    (uint32_t)lsb
Definition at line 45 of file base.h.
Referenced by make_uint32().
PI
#define PI 3.14159265358979323846
Definition at line 192 of file base.h.
RAD_2_DEG
#define RAD_2_DEG 57.29577951308232087679
Definition at line 193 of file base.h.
DEG_2_RAD
#define DEG_2_RAD 0.01745329251994329576
Definition at line 194 of file base.h.
RAD
#define RAD (deg) ((deg) * DEG_2_RAD)
Definition at line 200 of file base.h.
DEG
#define DEG (rad) ((rad) * RAD_2_DEG)
Definition at line 202 of file base.h.
min
#define min (a, b) (((a)<(b))?(a):(b))
Definition at line 204 of file base.h.
max
#define max (a, b) (((a)<(b))?(a):(b))
Definition at line 206 of file base.h.
abs
#define abs (x) (((x)>=0)?(x):-(x))
Definition at line 208 of file base.h.
Typedef Documentation
fun_ptr_vd_vd
typedef void(* fun_ptr_vd_vd) (void)
Pointer to function (input: void, output: void).
Definition at line 160 of file base.h.
fun_ptr_vd_u8
typedef void(* fun_ptr_vd_u8) (uint8_t)
Pointer to function (input: uint8_t, output: void).
Definition at line 163 of file base.h.
fun_ptr_u8_u8
typedef uint8_t(* fun_ptr_u8_u8) (uint8_t)
Pointer to function (input: uint8_t, output: uint8_t).
Definition at line 166 of file base.h.
Function Documentation
bswap16()
uint16_t bswap16 (uint16_t val)
Return the bytes inverted, for example 0xaabb becomes 0xbbaa.
Parameters
val 16bit value.
Returns
Bytes inverted.
Definition at line 8 of file bytes.cpp.
{
     return (
         ((val & 0x00FF) << 8) |
         ((val & 0xFF00) >> 8)
     );
 }
break_uint16()
u16_u8_t break_uint16 (uint16_t val)
Breaks a 16bit value into 8bit values.
Parameters
val 16bit value.
Returns
8bit struct.
Definition at line 15 of file bytes.cpp.
References bk_u16_u8_t::u16, and bk_u16_u8_t::u8.
{
     bk_u16_u8_t bk16;
     bk16.u16 = val;
     return bk16.u8;
 }
make_uint16() [1/5]
uint16_t make_uint16 (int16_t val)
Definition at line 21 of file bytes.cpp.
{
     return (uint16_t) val;
 }
make_uint16() [2/5]
uint16_t make_uint16 (uint16_t val)
Definition at line 25 of file bytes.cpp.
{
     return val;
 }
make_uint16() [3/5]
uint16_t make_uint16 (u16_u8_t val)
Definition at line 29 of file bytes.cpp.
References bk_u16_u8_t::u16, and bk_u16_u8_t::u8.
{
     bk_u16_u8_t mk16;
     mk16.u8 = val;
     return mk16.u16;
 }
make_uint16() [4/5]
uint16_t make_uint16 (uint8_t msb, uint8_t lsb)
Definition at line 35 of file bytes.cpp.
References MAKE_U16.
{
     return MAKE_U16(msb, lsb);
 }
bswap32()
uint32_t bswap32 (uint32_t val)
Similar to bswap16() but for 32bit.
Parameters
val 32bit value.
Returns
Bytes inverted.
Definition at line 40 of file bytes.cpp.
{
     return (
         ((val & 0xFF000000) >> 24) |
         ((val & 0x00FF0000) >> 8)  |
         ((val & 0x0000FF00) << 8)  |
         ((val & 0x000000FF) << 24)
     );
 }
break_uint32()
u32_u8_t break_uint32 (uint32_t val)
Similar to break_uint16() but for 32bit.
Parameters
val 32bit value.
Returns
8bit struct.
Definition at line 49 of file bytes.cpp.
References bk_u32_u8_t::u32, and bk_u32_u8_t::u8.
{
     bk_u32_u8_t bk32;
     bk32.u32 = val;
     return bk32.u8;
 }
make_uint32() [1/3]
uint32_t make_uint32 (int32_t val)
Definition at line 55 of file bytes.cpp.
{
     return (uint32_t) val;
 }
make_uint16() [5/5]
uint16_t make_uint16 (uint32_t val)
make_uint32() [2/3]
uint32_t make_uint32 (u32_u8_t val)
Definition at line 63 of file bytes.cpp.
References bk_u32_u8_t::u32, and bk_u32_u8_t::u8.
{
     bk_u32_u8_t mk32;
     mk32.u8 = value;
     return mk32.u32;
 }
make_uint32() [3/3]
uint32_t make_uint32 (uint8_t msb, uint8_t b2, uint8_t b1, uint8_t lsb)
Definition at line 69 of file bytes.cpp.
References MAKE_U32.
{
     return MAKE_U32(msb, b2, b1, lsb);
 }
get_field_mask()
uint8_t get_field_mask (uint8_t pos, uint8_t len)
Get the field mask.
Parameters
pos Position of the field (lsb).
len Length of the field (bits).
Returns
Field mask.
Definition at line 74 of file bytes.cpp.
Referenced by set_field_value().
{
     return (((1 << len) - 1) << pos);
 }
get_field_value()
uint8_t get_field_value (uint8_t reg, uint8_t pos, uint8_t len)
Get a field value from a register.
Parameters
reg Target register.
pos Position of the field (lsb).
len Length of the field (bits).
Returns
Field value.
Definition at line 78 of file bytes.cpp.
{
     return ((reg >> pos) & ((1 << len) - 1));
 }
set_field_value()
uint8_t set_field_value (uint8_t reg, uint8_t pos, uint8_t len, uint8_t value)
Set a field value on a register.
Parameters
reg Target register.
pos Position of the field (lsb).
len Length of the field (bits).
value Field value.
Returns
Modified register.
Definition at line 82 of file bytes.cpp.
References get_field_mask().
Referenced by int_ext_attach(), int_pc_attach(), and int_pc_detach().
{
     return ((reg &~ get_field_mask(pos, len)) | ((value & ((1 << len) - 1)) << pos));
 }
fun_vd_vd_dummy()
void fun_vd_vd_dummy (void)
Dummy function, does nothing. Used to initialize fun_ptr_vd_vd pointers.
Definition at line 8 of file callbacks.cpp.
Referenced by SPI::enable(), TWI::enable(), TWI::on_request(), SPI::SPI(), and TWI::TWI().
{
 }
fun_vd_u8_dummy()
void fun_vd_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_vd_u8 pointers.
Parameters
value
Definition at line 12 of file callbacks.cpp.
Referenced by TWI::enable(), TWI::on_receive(), and TWI::TWI().
{
 }
fun_u8_u8_dummy()
uint8_t fun_u8_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_u8_u8 pointers.
Parameters
value
Returns
0x00.
Definition at line 16 of file callbacks.cpp.
Referenced by SPI::on_receive(), and SPI::SPI().
{
     return 0x00;
 }