AVRLibs: base/callbacks.cpp File Reference
callbacks.cpp File Reference
Callback definitions.
#include <base/base.h>
Functions
void fun_vd_vd_dummy (void)
Dummy function, does nothing. Used to initialize fun_ptr_vd_vd pointers.
void fun_vd_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_vd_u8 pointers.
uint8_t fun_u8_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_u8_u8 pointers.
Detailed Description
Callback definitions.
Definition in file callbacks.cpp.
Function Documentation
fun_vd_vd_dummy()
void fun_vd_vd_dummy (void)
Dummy function, does nothing. Used to initialize fun_ptr_vd_vd pointers.
Definition at line 8 of file callbacks.cpp.
Referenced by SPI::enable(), TWI::enable(), TWI::on_request(), SPI::SPI(), and TWI::TWI().
{
 }
fun_vd_u8_dummy()
void fun_vd_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_vd_u8 pointers.
Parameters
value
Definition at line 12 of file callbacks.cpp.
Referenced by TWI::enable(), TWI::on_receive(), and TWI::TWI().
{
 }
fun_u8_u8_dummy()
uint8_t fun_u8_u8_dummy (uint8_t value)
Dummy function, does nothing. Used to initialize fun_ptr_u8_u8 pointers.
Parameters
value
Returns
0x00.
Definition at line 16 of file callbacks.cpp.
Referenced by SPI::on_receive(), and SPI::SPI().
{
     return 0x00;
 }