AVRLibs: String Class Reference
String Class Reference
String handling implementation.
#include <string.h>
Public Member Functions
String (const char *cstr="")
String object constructor. This allows to initialize an object with a char array.
String (const String &str)
String object constructor. This allows to initialize an object copying the contents of another object.
String (const FlashString *pstr)
String object constructor. This allows to initialize an object with a progmem space string.
template<typename T >
String (T value)
String object constructor. Used for any input type.
uint16_t get_capacity (void) const
Returns the capacity of the string array.
uint16_t get_length (void) const
Returns the length of the string array.
bool reserve (size_t size)
This method is used to increase the size of the string if needed.
bool resize (size_t size)
Resize the string to any size.
void set_char (size_t idx, char c)
Set the given character 'c' on the position 'idx' of the string.
char get_char (size_t fromidx) const
Get a given character from the position 'fromidx' of the string.
void get_chars (char *buff, size_t size, size_t fromidx)
Used to retrieve a character array from the string.
void get_bytes (uint8_t *buff, size_t size, size_t fromidx)
Retrieve a byte array from the string.
char * begin (void)
Retrieve the address of the first character in the string.
char * end (void)
Retrieve the address of the last character in the string.
const char * begin (void) const
Retrieve the address of the first character in the string.
const char * end (void) const
Retrieve the address of the last character in the string.
bool concat (const char *cstr)
Used to concatenate a char array.
bool concat (const String &str)
Used to concatenate another string object.
bool concat (const FlashString *pstr)
Used to concatenate a progmem string.
bool concat (char c)
Used to concatenate a single character.
bool concat (uint32_t num, num_base_t base=NUM_BASE_DEC)
Used to concatenate a given number.
bool concat (uint16_t num, num_base_t base=NUM_BASE_DEC)
Used to concatenate a given number.
bool concat (uint8_t num, num_base_t base=NUM_BASE_DEC)
Used to concatenate a given number.
bool concat (int32_t num, num_base_t base=NUM_BASE_DEC)
Used to concatenate a given number.
bool concat (int16_t num, num_base_t base=NUM_BASE_DEC)
Used to concatenate a given number.
bool concat (int8_t num, num_base_t base=NUM_BASE_DEC)
Used to concatenate a given number.
bool concat (double num, uint8_t p=3)
Used to concatenate a double value.
void replace (char find, char replace)
Replace a given character on the string.
void replace (const String &find, const String &replace)
Replace a given substring on the string.
void remove (size_t idx)
Remove a single character from the string. The position of the character is given by the index 'idx'.
void remove (size_t idx, size_t size)
Return 'size' number of characters from the string starting from the index 'idx'.
void to_upper_case (void)
Upper case all the characters on the string.
void to_lower_case (void)
Lower case all the characters on the string.
void trim (void)
Remove all the white space characters from the beginning and end of the string.
int32_t to_int (void)
Tries to convert the string into a integer value.
double to_double (void)
Tries to convert the string into a double value.
int16_t index_of (char c) const
Search for a character on the string and return the index where it's first found (if exists).
int16_t index_of (char c, size_t fromidx) const
Search for a character on the string and return the index where it's first found (if exists).
int16_t index_of (const String &str) const
Search for a substring on the string and return the index where it's first found (if exists).
int16_t index_of (const String &str, size_t fromidx) const
Search for a substring on the string and return the index where it's first found (if exists).
int16_t last_index_of (char c) const
Same as String::index_of(char)const but backwards.
int16_t last_index_of (char c, size_t fromidx) const
Same as String::index_of(char, size_t)const but backwards.
int16_t last_index_of (const String &str) const
Same as String::index_of(const String&)const but backwards.
int16_t last_index_of (const String &str, size_t fromidx) const
Same as String::index_of(const String&, size_t)const but backwards.
String get_substring (size_t fromidx) const
Similar to String::get_substring(uint16_t, uint16_t)const but takes all the characters from 'fromidx' to the end of the string.
String get_substring (size_t fromidx, size_t toidx) const
Get a substring from the string starting from 'fromidx' and ending on 'toidx'.
int16_t compare_to (const String &str) const
Compare 2 strings.
bool is_equal_to (const String &str) const
Check if the string is equal to a given substring.
bool is_equal_to (const char *cstr) const
Check if the string is equal to a given character array.
bool start_with (const String &str) const
Check if the string starts with a given substring.
bool start_with (const String &str, size_t fromidx) const
Check if the string starts with a given substring.
bool ends_with (const String &str) const
Check if the string ends with a given substring.
operator if_bool_type (void) const
Safe bool method implementation.
String & operator= (const char *cstr)
String & operator= (const String &str)
String & operator= (const FlashString *pstr)
template<typename T >
String & operator+= (T value)
template<typename T >
String & operator+ (T value)
bool operator== (const String &str) const
bool operator== (const char *cstr) const
bool operator!= (const String &str) const
bool operator!= (const char *cstr) const
bool operator< (const String &str) const
bool operator> (const String &str) const
bool operator<= (const String &str) const
bool operator>= (const String &str) const
char operator[] (uint16_t fromidx) const
char & operator[] (uint16_t fromidx)
Protected Member Functions
bool buffer_change (size_t size)
Change the size of the string buffer.
void buffer_delete (void)
Delete the contents of the string buffer and reset the length and capacity to 0.
void buffer_init (void)
Reset the buffer, it's length and capacity.
bool concat (const char *cstr, size_t size)
Add a character array 'cstr' with size 'size' to the string.
String & copy (const char *cstr, size_t size)
Tries to copy a character array into the string buffer. If it's not possible, reset the buffer.
String & copy (const FlashString *pstr, uint16_t size)
Tries to copy a progmem character array into the string buffer. If it's not possible, reset the buffer.
void move (String &str)
Tries to move the contents of 'str' to the string, after this deletes 'str'.
Protected Attributes
char * _buff
The actual string.
uint16_t _len
The string length (Not counting the final '\0').
uint16_t _cap
The array length minus one (reserve for '\0').
Private Types
typedef void(String::* if_bool_type) () const
This type is used to create a method to associate a boolean value to the string object. See more on: http://www.artima.com/cppsource/safebool.html.
Private Member Functions
void if_bool (void) const
Used to apply the safe bool method.
Detailed Description
String handling implementation.
Definition at line 27 of file string.h.
Member Typedef Documentation
if_bool_type
typedef void(String::* String::if_bool_type) () const private
This type is used to create a method to associate a boolean value to the string object. See more on: http://www.artima.com/cppsource/safebool.html.
Definition at line 35 of file string.h.
Constructor & Destructor Documentation
String() [1/4]
String::String (const char * cstr = "")
String object constructor. This allows to initialize an object with a char array.
Parameters
cstr Char array string.
Definition at line 11 of file string.cpp.
References buffer_init(), and copy().
Referenced by if_bool().
{
     buffer_init();
     if (cstr) copy(cstr, strlen(cstr));
 }
String() [2/4]
String::String (const String & str)
String object constructor. This allows to initialize an object copying the contents of another object.
Parameters
str String object.
Definition at line 16 of file string.cpp.
References buffer_init().
{
     buffer_init();
     *this = str;
 }
String() [3/4]
String::String (const FlashString * pstr)
String object constructor. This allows to initialize an object with a progmem space string.
Parameters
pstr Progmem string.
Definition at line 21 of file string.cpp.
References buffer_init().
{
     buffer_init();
     *this = pstr;
 }
String() [4/4]
template<typename T > String::String (T value) explicit
String object constructor. Used for any input type.
Parameters
value Input value.
Definition at line 483 of file string.h.
References buffer_init(), and concat().
                       {
     buffer_init();
     concat(value);
 }
Member Function Documentation
if_bool()
void String::if_bool (void) const inline private
Used to apply the safe bool method.
Definition at line 40 of file string.h.
References String().
Referenced by operator if_bool_type().
 {}
get_capacity()
uint16_t String::get_capacity (void) const inline
Returns the capacity of the string array.
Returns
String capacity.
Definition at line 77 of file string.h.
References _cap.
 {return _cap;}
get_length()
uint16_t String::get_length (void) const inline
Returns the length of the string array.
Returns
String length.
Definition at line 83 of file string.h.
References _len, begin(), compare_to(), concat(), end(), ends_with(), get_bytes(), get_char(), get_chars(), get_substring(), index_of(), is_equal_to(), last_index_of(), NUM_BASE_DEC, replace(), reserve(), resize(), set_char(), start_with(), to_double(), to_int(), to_lower_case(), to_upper_case(), and trim().
Referenced by end(), and Stream::print().
 {return _len;}
reserve()
bool String::reserve (size_t size)
This method is used to increase the size of the string if needed.
Parameters
size String desired length.
Returns
True if success, False otherwise.
Definition at line 29 of file string.cpp.
References _buff, _cap, and resize().
Referenced by concat(), copy(), and get_length().
{
     // If the buffer is bigger than needed, all OK!
     if (_buff && (_cap >= size)) return true;
     // If requires resize and the operation is succesful, all OK!
     return resize(size);
 }
resize()
bool String::resize (size_t size)
Resize the string to any size.
Parameters
size String desired length.
Returns
True if success, False otherwise.
Definition at line 36 of file string.cpp.
References _buff, _cap, _len, and buffer_change().
Referenced by get_length(), and reserve().
{
     // If the resize fails...
     if (!buffer_change(size)) return false;
     // Otherwise...
     if (_len > _cap) {
         _len = _cap;
         _buff[_len + 1] = '\0';
     } else if (_len == 0) {
         _buff[0] = '\0';
     }
     return true;
 }
set_char()
void String::set_char (size_t idx, char c)
Set the given character 'c' on the position 'idx' of the string.
Parameters
idx Position to modify.
c Character to write.
Definition at line 77 of file string.cpp.
References _buff, _cap, and _len.
Referenced by get_length().
{
     if (idx < _len) _buff[idx] = c;
     if ((idx > _len) && (idx < _cap)) {
         _buff[_len + 1] = c;
         _buff[_len + 2] = '\0';
     }
 }
get_char()
char String::get_char (size_t fromidx) const
Get a given character from the position 'fromidx' of the string.
Parameters
fromidx Position from where the character is retrieved.
Definition at line 85 of file string.cpp.
References operator[]().
Referenced by get_length().
{
     return operator[](fromidx);
 }
get_chars()
void String::get_chars (char * buff, size_t size, size_t fromidx)
Used to retrieve a character array from the string.
Parameters
buff Pointer to byte array.
size Number of bytes to retrieve.
fromidx Position to begin the extraction.
Definition at line 89 of file string.cpp.
References get_bytes().
Referenced by get_length().
{
     get_bytes((uint8_t*) buff, size, fromidx);
 }
get_bytes()
void String::get_bytes (uint8_t * buff, size_t size, size_t fromidx)
Retrieve a byte array from the string.
Parameters
buff Pointer to byte array.
size Number of bytes to retrieve.
fromidx Position to begin the extraction.
Definition at line 93 of file string.cpp.
References _buff, and _len.
Referenced by get_chars(), and get_length().
{
     // Check if the buffer and size are ok...
     if (!buff || (size == 0)) return;
     // If the start point is after the last character...
     if (fromidx > _len) {
         buff[0] = '\0';
         return;
     }
     // If all is OK
     uint16_t num = size - 1;
     if (num > (_len - fromidx))
         num = _len - fromidx;
     strncpy((char*) buff, _buff + fromidx, num);
     buff[num] = '\0';
 }
begin() [1/2]
char * String::begin (void)
Retrieve the address of the first character in the string.
Returns
Address of the first string.
Definition at line 109 of file string.cpp.
References _buff.
Referenced by end(), get_length(), Stream::print(), and trim().
{
     return _buff;
 }
end() [1/2]
char * String::end (void)
Retrieve the address of the last character in the string.
Returns
Address of the last string.
Definition at line 113 of file string.cpp.
References _buff, and _len.
Referenced by ends_with(), get_length(), and trim().
                       {
     return _buff + _len;
 }
begin() [2/2]
const char * String::begin (void) const
Retrieve the address of the first character in the string.
Returns
Address of the first string.
Definition at line 117 of file string.cpp.
References _buff.
{
     return _buff;
 }
end() [2/2]
const char * String::end (void) const
Retrieve the address of the last character in the string.
Returns
Address of the last string.
Definition at line 121 of file string.cpp.
References begin(), and get_length().
{
     return begin() + get_length();
 }
concat() [1/12]
bool String::concat (const char * cstr)
Used to concatenate a char array.
Parameters
cstr Character array.
Returns
True if success, False otherwise.
Definition at line 142 of file string.cpp.
Referenced by concat(), get_length(), operator+(), operator+=(), and String().
{
     return concat(cstr, strlen(cstr));
 }
concat() [2/12]
bool String::concat (const String & str)
Used to concatenate another string object.
Parameters
str String object.
Returns
True if success, False otherwise.
Definition at line 146 of file string.cpp.
References _buff, _len, and concat().
{
     return concat(str._buff, str._len);
 }
concat() [3/12]
bool String::concat (const FlashString * pstr)
Used to concatenate a progmem string.
Parameters
pstr Progmem string.
Returns
True if success, False otherwise.
Definition at line 150 of file string.cpp.
References _buff, _len, and reserve().
{
     uint16_t size = strlen_P((const char*)pstr);
     // If there's nothing to add, end operation with error.
     if (!pstr)          return false;
     // If the size is 0, end operation OK.
     if (size == 0)      return true;
     // If there's problems with the resize, end with error.
     uint16_t new_len = _len + size;
     if (!reserve(new_len)) return false;
     // Concatenate
     strcpy_P(_buff + _len, (const char*)pstr);
     _len = new_len;
     return true;
 }
concat() [4/12]
bool String::concat (char c)
Used to concatenate a single character.
Parameters
c Character.
Returns
True if success, False otherwise.
Definition at line 165 of file string.cpp.
References concat().
{
     char tmp[] = {c, '\0'};
     return concat(tmp, 1);
 }
concat() [5/12]
bool String::concat (uint32_t num, num_base_t base = NUM_BASE_DEC)
Used to concatenate a given number.
Parameters
num Value.
base Numeric base to perform conversion.
Returns
True if success, False otherwise.
Definition at line 170 of file string.cpp.
References concat().
{
     // U32 max: 4.294.967.295 => 12 digits (+ null)
     char tmp[12];
     ultoa(num, tmp, base);
     return concat(tmp, strlen(tmp));
 }
concat() [6/12]
bool String::concat (uint16_t num, num_base_t base = NUM_BASE_DEC)
Used to concatenate a given number.
Parameters
num Value.
base Numeric base to perform conversion.
Returns
True if success, False otherwise.
Definition at line 177 of file string.cpp.
References concat().
{
     // U16 max: 65.535 => 8 digits (+ null)
     char tmp[8];
     utoa(num, tmp, base);
     return concat(tmp, strlen(tmp));
 }
concat() [7/12]
bool String::concat (uint8_t num, num_base_t base = NUM_BASE_DEC)
Used to concatenate a given number.
Parameters
num Value.
base Numeric base to perform conversion.
Returns
True if success, False otherwise.
Definition at line 184 of file string.cpp.
References concat().
{
     // U8 max: 255 => 5 digits(+ null)
     char tmp[5];
     utoa(num, tmp, base);
     return concat(tmp, strlen(tmp));
 }
concat() [8/12]
bool String::concat (int32_t num, num_base_t base = NUM_BASE_DEC)
Used to concatenate a given number.
Parameters
num Value.
base Numeric base to perform conversion.
Returns
True if success, False otherwise.
Definition at line 191 of file string.cpp.
References concat().
{
     // I32 max: 4.294.967.295 => 12 digits (+ null + sign)
     char tmp[12];
     ltoa(num, tmp, base);
     return concat(tmp, strlen(tmp));
 }
concat() [9/12]
bool String::concat (int16_t num, num_base_t base = NUM_BASE_DEC)
Used to concatenate a given number.
Parameters
num Value.
base Numeric base to perform conversion.
Returns
True if success, False otherwise.
Definition at line 198 of file string.cpp.
References concat().
{
     // I16 max: 65.535 => 8 digits (+ null + sign)
     char tmp[8];
     itoa(num, tmp, base);
     return concat(tmp, strlen(tmp));
 }
concat() [10/12]
bool String::concat (int8_t num, num_base_t base = NUM_BASE_DEC)
Used to concatenate a given number.
Parameters
num Value.
base Numeric base to perform conversion.
Returns
True if success, False otherwise.
Definition at line 205 of file string.cpp.
References concat().
{
     // I8 max: 255 => 5 digits (+ null + sign)
     char tmp[5];
     itoa(num, tmp, base);
     return concat(tmp, strlen(tmp));
 }
concat() [11/12]
bool String::concat (double num, uint8_t p = 3)
Used to concatenate a double value.
Parameters
num Value.
p Precision.
Returns
True if success, False otherwise.
Definition at line 212 of file string.cpp.
References concat().
{
     char tmp[15];
     char* str = dtostrf(num, 4, p, tmp);
     return concat(str, strlen(str));
 }
replace() [1/2]
void String::replace (char find, char replace)
Replace a given character on the string.
Parameters
find Character to be replaced.
replace Character replacement.
Definition at line 221 of file string.cpp.
References _buff.
Referenced by get_length().
{
     // If there's not data, return
     if (!_buff) return;
     // Else, replace
     for (char* cp = _buff; *cp; cp++) {
         if (*cp == find) *cp = replace;
     }
 }
replace() [2/2]
void String::replace (const String & find, const String & replace)
Replace a given substring on the string.
Parameters
find substring to be replaced.
replace substring replacement.
Definition at line 230 of file string.cpp.
References _buff, _cap, _len, buffer_change(), and last_index_of().
{
     // If the target buffer or the word to find are empty, do nothing
     if ((_len == 0) || (find._len == 0)) return;
     // Otherwise, find and replace
     int16_t str_diff = replace._len - find._len;
     char* source = _buff;
     char* found_at;
     if (str_diff == 0) {
         // If the old and new values have the same size...
         while ((found_at = strstr(source, find._buff)) != NULL) {
             memcpy(found_at, replace._buff, replace._len);
             source = found_at + replace._len;
         }
     } else if (str_diff < 0) {
         // If the new value is smaller than the old one...
         char* output = _buff;
         while ((found_at = strstr(source, find._buff)) != NULL) {
             uint16_t pos = found_at - source;
             memcpy(output, source, pos);
             output += pos;
             memcpy(output, replace._buff, replace._len);
             output += replace._len;
             source += pos + find._len;
             _len += str_diff;
         }
         strcpy(output, source);
     } else {
         // If the new value is bigger than the old one...
         uint16_t new_len = _len;
         while ((found_at = strstr(source, find._buff)) != NULL) {
             source = found_at + find._len;
             new_len += str_diff;
         }
         if (new_len == _len) return;
         if ((new_len > _cap) && !buffer_change(new_len)) return;
         int16_t index = _len - 1;
         while ((index > 0) && ((index = last_index_of(find, index)) >= 0)) {
             source = _buff + index + find._len;
             memmove(source + str_diff, source, _len - (source - _buff));
             memcpy(_buff + index, replace._buff, replace._len);
             _len += str_diff;
             _buff[_len] = '\0';
             index--;
         }
     }
 }
remove() [1/2]
void String::remove (size_t idx)
Remove a single character from the string. The position of the character is given by the index 'idx'.
Parameters
idx Character index.
Definition at line 277 of file string.cpp.
{
     remove(idx, (uint16_t)-1);
 }
remove() [2/2]
void String::remove (size_t idx, size_t size)
Return 'size' number of characters from the string starting from the index 'idx'.
Parameters
idx Starting index.
size Number of characters to be removed.
Definition at line 281 of file string.cpp.
References _buff, and _len.
{
     // If no data is selected, return
     if (size == 0) return;
     // If the index exceeds the length, return
     if (idx > _len) return;
     // Ensure the size is OK
     if (size > (_len - idx)) {
         _len = idx;
     } else {
         char* output = _buff + idx;
         memcpy(output, output + size, _len - (idx + size));
         _len -= size;
     }
     _buff[_len] = '\0';
 }
to_upper_case()
void String::to_upper_case (void)
Upper case all the characters on the string.
Definition at line 297 of file string.cpp.
References _buff.
Referenced by get_length().
{
     // If there's not data, return
     if (!_buff) return;
     // Else, replace
     for (char* cp = _buff; *cp; cp++) {
         *cp = toupper(*cp);
     }
 }
to_lower_case()
void String::to_lower_case (void)
Lower case all the characters on the string.
Definition at line 306 of file string.cpp.
References _buff.
Referenced by get_length().
{
     // If there's not data, return
     if (!_buff) return;
     // Else, replace
     for (char* cp = _buff; *cp; cp++) {
         *cp = tolower(*cp);
     }
 }
trim()
void String::trim (void)
Remove all the white space characters from the beginning and end of the string.
Definition at line 315 of file string.cpp.
References _buff, _len, begin(), and end().
Referenced by get_length().
                       {
     // If the buffer is not available, return
     if (!_buff || (_len == 0)) return;
     // Else, clean all the spaces (in the beginning and end)
     char* begin = _buff;
     while (isspace(*begin)) begin++;
     char* end = _buff + _len - 1;
     while (isspace(*end) && (end >= begin)) end--;
     _len = end + 1 - begin;
     if (begin > _buff) memcpy(_buff, begin, _len);
     _buff[_len] = '\0';
 }
to_int()
int32_t String::to_int (void)
Tries to convert the string into a integer value.
Returns
Integer value.
Definition at line 331 of file string.cpp.
References _buff.
Referenced by get_length().
{
     if (!_buff) return 0;
     return atol(_buff);
 }
to_double()
double String::to_double (void)
Tries to convert the string into a double value.
Returns
Double value.
Definition at line 336 of file string.cpp.
References _buff.
Referenced by get_length().
{
     if (!_buff) return 0;
     return atof(_buff);
 }
index_of() [1/4]
int16_t String::index_of (char c) const
Search for a character on the string and return the index where it's first found (if exists).
Parameters
c Character to be found.
Returns
Index in which the character is found. If the character is not found, returns -1.
Definition at line 344 of file string.cpp.
Referenced by get_length(), and index_of().
{
     return index_of(c, 0);
 }
index_of() [2/4]
int16_t String::index_of (char c, size_t fromidx) const
Search for a character on the string and return the index where it's first found (if exists).
Parameters
c Character to be found.
fromidx Index from the search is started.
Returns
Index in which the character is found. If the character is not found, returns -1.
Definition at line 348 of file string.cpp.
References _buff, and _len.
{
     // Check if the index is OK...
     if (fromidx >= _len) return -1;
     // Search
     const char* tmp = strchr(_buff + fromidx, c);
     if (tmp == NULL) return -1;
     return (tmp - _buff);
 }
index_of() [3/4]
int16_t String::index_of (const String & str) const
Search for a substring on the string and return the index where it's first found (if exists).
Parameters
str String to be found.
Returns
Index in which the substring is found. If the substring is not found, returns -1.
Definition at line 357 of file string.cpp.
References index_of().
{
     return index_of(str, 0);
 }
index_of() [4/4]
int16_t String::index_of (const String & str, size_t fromidx) const
Search for a substring on the string and return the index where it's first found (if exists).
Parameters
str String to be found.
fromidx Index from the search is started.
Returns
Index in which the substring is found. If the substring is not found, returns -1.
Definition at line 361 of file string.cpp.
References _buff, and _len.
{
     // Check if the index is OK...
     if (fromidx >= _len) return -1;
     // Search
     const char* tmp = strstr(_buff + fromidx, str._buff);
     if (tmp == NULL) return -1;
     return (tmp - _buff);
 }
last_index_of() [1/4]
int16_t String::last_index_of (char c) const
Same as String::index_of(char)const but backwards.
Parameters
c Character to be found.
Returns
Index in which the character is found. If the character is not found, returns -1.
Definition at line 370 of file string.cpp.
References _len.
Referenced by get_length(), last_index_of(), and replace().
{
     return last_index_of(c, _len - 1);
 }
last_index_of() [2/4]
int16_t String::last_index_of (char c, size_t fromidx) const
Same as String::index_of(char, size_t)const but backwards.
Parameters
c Character to be found.
fromidx Index from the search is started.
Returns
Index in which the character is found. If the character is not found, returns -1.
Definition at line 374 of file string.cpp.
References _buff, and _len.
{
     // Check if index is OK...
     if (fromidx >= _len) return -1;
     // Search
     const char* tmp = strchr(_buff + fromidx, c);
     if (tmp == NULL) return -1;
     return (tmp - _buff);
 }
last_index_of() [3/4]
int16_t String::last_index_of (const String & str) const
Same as String::index_of(const String&)const but backwards.
Parameters
str String to be found.
Returns
Index in which the substring is found. If the substring is not found, returns -1.
Definition at line 383 of file string.cpp.
References _len, and last_index_of().
{
     return last_index_of(str, _len - str._len);
 }
last_index_of() [4/4]
int16_t String::last_index_of (const String & str, size_t fromidx) const
Same as String::index_of(const String&, size_t)const but backwards.
Parameters
str String to be found.
fromidx Index from the search is started.
Returns
Index in which the substring is found. If the substring is not found, returns -1.
Definition at line 387 of file string.cpp.
References _buff, and _len.
{
     // Check if indexes are OK...
     if ((str._len == 0) || (str._len > _len) || (_len == 0)) return -1;
     // Search
     int16_t found = -1;
     if (fromidx >= _len) fromidx = _len - 1;
     for (char* p = _buff; p <= _buff + fromidx; p++) {
         p = strstr(p, str._buff);
         if (!p) break;
         if ((uint16_t)(p - _buff) <= fromidx) found = (p - _buff);
     }
     return found;
 }
get_substring() [1/2]
String String::get_substring (size_t fromidx) const
Similar to String::get_substring(uint16_t, uint16_t)const but takes all the characters from 'fromidx' to the end of the string.
Parameters
fromidx Index of the first character of the substring.
Returns
Desired substring.
Definition at line 401 of file string.cpp.
References _len.
Referenced by get_length().
{
     return get_substring(fromidx, _len);
 }
get_substring() [2/2]
String String::get_substring (size_t fromidx, size_t toidx) const
Get a substring from the string starting from 'fromidx' and ending on 'toidx'.
Parameters
fromidx Index of the first character of the substring.
toidx Index of the last character of the substring.
Returns
Desired substring.
Definition at line 405 of file string.cpp.
References _buff, and _len.
{
     String out;
     // Ensure that from < to
     if (fromidx > toidx) {
         uint16_t tmp = fromidx;
         fromidx = toidx;
         toidx = tmp;
     }
     // Check limits
     if (fromidx > _len) return out;
     if (toidx > _len)   toidx = _len;
     // Get substring
     char tmp = _buff[toidx];
     _buff[toidx] = '\0';
     out = _buff + fromidx;
     _buff[toidx] = tmp;
     return out;
 }
compare_to()
int16_t String::compare_to (const String & str) const
Compare 2 strings.
Parameters
str String to be compared to.
Returns
Comparison result.
Definition at line 427 of file string.cpp.
References _buff, and _len.
Referenced by get_length(), is_equal_to(), operator<(), operator<=(), operator>(), and operator>=().
{
     // If any of the strings is empty, return the firs
     if (!_buff || !str._buff)   {
         if (str._buff && (str._len > 0)) return 0 - *(uint8_t*)str._buff;
         if (_buff && (_len > 0))         return *(uint8_t*)_buff;
         return 0;
     }
     return strcmp(_buff, str._buff);
 }
is_equal_to() [1/2]
bool String::is_equal_to (const String & str) const
Check if the string is equal to a given substring.
Parameters
str String to be compared to.
Returns
True if matched, False otherwise.
Definition at line 437 of file string.cpp.
References _len, and compare_to().
Referenced by get_length(), operator!=(), and operator==().
{
     return ((_len == str._len) && (compare_to(str) == 0));
 }
is_equal_to() [2/2]
bool String::is_equal_to (const char * cstr) const
Check if the string is equal to a given character array.
Parameters
cstr Character array to be compared to.
Returns
True if matched, False otherwise.
Definition at line 441 of file string.cpp.
References _buff, and _len.
{
     if (_len == 0)      return ((cstr == NULL) || (*cstr == 0));
     if (cstr == NULL)   return (_buff[0] == '\0');
     return (strcmp(_buff, cstr) == 0);
 }
start_with() [1/2]
bool String::start_with (const String & str) const
Check if the string starts with a given substring.
Parameters
str String to be compared to.
Returns
True if matched, False otherwise.
Definition at line 447 of file string.cpp.
Referenced by get_length().
{
     return start_with(str, 0);
 }
start_with() [2/2]
bool String::start_with (const String & str, size_t fromidx) const
Check if the string starts with a given substring.
Parameters
str String to be compared to.
fromidx Index from which the comparison will be done.
Returns
True if matched, False otherwise.
Definition at line 451 of file string.cpp.
References _buff, and _len.
{
     if ((fromidx > _len) || !_buff || !str._buff) return false;
     return (strncmp((_buff + fromidx), str._buff, str._len) == 0);
 }
ends_with()
bool String::ends_with (const String & str) const
Check if the string ends with a given substring.
Parameters
str String to be compared to.
Returns
True if matched, False otherwise.
Definition at line 456 of file string.cpp.
References _buff, _len, and end().
Referenced by get_length().
{
     if ((_len < str._len) || !_buff || !str._buff) return false;
     return (strcmp((end() - str._len), str._buff) == 0);
 }
operator if_bool_type()
String::operator if_bool_type (void) const inline
Safe bool method implementation.
Definition at line 397 of file string.h.
References _buff, if_bool(), operator!=(), operator+(), operator+=(), operator<(), operator<=(), operator=(), operator==(), operator>(), operator>=(), and operator[]().
 { return (_buff) ? &String::if_bool : NULL; }
operator=() [1/3]
String & String::operator= (const char * cstr)
Definition at line 508 of file string.cpp.
References buffer_delete(), and copy().
Referenced by operator if_bool_type().
{
     // If there's something to copy...
     if (cstr) copy(cstr, strlen(cstr));
     // In any other case, empty the string...
     else buffer_delete();
     return *this;
 }
operator=() [2/3]
String & String::operator= (const String & str)
Definition at line 516 of file string.cpp.
References _buff, _len, buffer_delete(), and copy().
{
     // If is the same object...
     if (this == &str) return *this;
     // If there's something to copy...
     if (str._buff) copy(str._buff, str._len);
     // In any other case, empty the string...
     else buffer_delete();
     return *this;
 }
operator=() [3/3]
String & String::operator= (const FlashString * pstr)
Definition at line 526 of file string.cpp.
References buffer_delete(), and copy().
{
     // If there's something to copy...
     if (pstr) copy(pstr, strlen_P((PGM_P)pstr));
     // In any other case, empty the string...
     else buffer_delete();
     return *this;
 }
operator+=()
template<typename T > String & String::operator+= (T value)
Definition at line 489 of file string.h.
References concat().
Referenced by operator if_bool_type().
{
     concat(value);
     return *this;
 }
operator+()
template<typename T > String & String::operator+ (T value)
Definition at line 495 of file string.h.
References concat().
Referenced by operator if_bool_type().
{
     String tmp(value);
     concat(tmp);
     return *this;
 }
operator==() [1/2]
bool String::operator== (const String & str) const
Definition at line 534 of file string.cpp.
References is_equal_to().
Referenced by operator if_bool_type().
{
     return is_equal_to(str);
 }
operator==() [2/2]
bool String::operator== (const char * cstr) const
Definition at line 538 of file string.cpp.
References is_equal_to().
{
     return is_equal_to(cstr);
 }
operator!=() [1/2]
bool String::operator!= (const String & str) const
Definition at line 542 of file string.cpp.
References is_equal_to().
Referenced by operator if_bool_type().
{
     return !is_equal_to(str);
 }
operator!=() [2/2]
bool String::operator!= (const char * cstr) const
Definition at line 546 of file string.cpp.
References is_equal_to().
{
     return !is_equal_to(cstr);
 }
operator<()
bool String::operator< (const String & str) const
Definition at line 550 of file string.cpp.
References compare_to().
Referenced by operator if_bool_type().
{
     return (compare_to(str) < 0);
 }
operator>()
bool String::operator> (const String & str) const
Definition at line 554 of file string.cpp.
References compare_to().
Referenced by operator if_bool_type().
{
     return (compare_to(str) > 0);
 }
operator<=()
bool String::operator<= (const String & str) const
Definition at line 558 of file string.cpp.
References compare_to().
Referenced by operator if_bool_type().
{
     return (compare_to(str) <= 0);
 }
operator>=()
bool String::operator>= (const String & str) const
Definition at line 562 of file string.cpp.
References compare_to().
Referenced by operator if_bool_type().
{
     return (compare_to(str) >= 0);
 }
operator[]() [1/2]
char String::operator[] (uint16_t fromidx) const
Definition at line 566 of file string.cpp.
References _buff, and _len.
Referenced by get_char(), and operator if_bool_type().
{
     // If is not initialized or the index is out of bounds...
     if (!_buff || (fromidx > _len)) return 0;
     // If nothing goes wrong...
     return _buff[fromidx];
 }
operator[]() [2/2]
char & String::operator[] (uint16_t fromidx)
Definition at line 573 of file string.cpp.
References _buff, and _len.
{
     // If is not initialized or the index is out of bounds...
     if (!_buff || (fromidx > _len)) {
         static char dummy = 0;
         return dummy;
     }
     // If nothing goes wrong...
     return _buff[fromidx];
 }
buffer_change()
bool String::buffer_change (size_t size) protected
Change the size of the string buffer.
Parameters
size Desired size of the buffer.
Returns
True if success, False otherwise.
Definition at line 49 of file string.cpp.
References _buff, and _cap.
Referenced by replace(), and resize().
{
     // Allocate space for the 'size' chars and the terminator
     char* new_buff = (char*)realloc(_buff, size + 1);
     // If the operation goes wrong...
     if (!new_buff) return false;
     // Otherwise...
     _buff = new_buff;
     _cap = size;
     return true;
 }
buffer_delete()
void String::buffer_delete (void) protected
Delete the contents of the string buffer and reset the length and capacity to 0.
Definition at line 60 of file string.cpp.
References _buff, and buffer_init().
Referenced by copy(), move(), and operator=().
{
     // Free the used memory
     if (_buff) free(_buff);
     // Reset the string
     buffer_init();
 }
buffer_init()
void String::buffer_init (void) protected
Reset the buffer, it's length and capacity.
Definition at line 67 of file string.cpp.
References _buff, _cap, and _len.
Referenced by buffer_delete(), and String().
{
     // Set the default contents
     _buff = NULL;       // String empty.
     _cap = 0;           // No space reserved.
     _len = 0;           // No data on string.
 }
concat() [12/12]
bool String::concat (const char * cstr, size_t size) protected
Add a character array 'cstr' with size 'size' to the string.
Parameters
cstr Character array pointer.
size Size of the character array.
Returns
True if success, False otherwise.
Definition at line 128 of file string.cpp.
References _buff, _len, and reserve().
{
     // If there's nothing to add, end operation with error.
     if (!cstr)          return false;
     // If the size is 0, end operation OK.
     if (size == 0)      return true;
     // If there's problems with the resize, end with error.
     uint16_t new_len = _len + size;
     if (!reserve(new_len)) return false;
     // Concatenate
     strcpy(_buff + _len, cstr);
     _len = new_len;
     return true;
 }
copy() [1/2]
String & String::copy (const char * cstr, size_t size) protected
Tries to copy a character array into the string buffer. If it's not possible, reset the buffer.
Parameters
cstr Character array pointer.
size Size of the character array.
Returns
Modified string.
Definition at line 464 of file string.cpp.
References _buff, _len, buffer_delete(), and reserve().
Referenced by operator=(), and String().
{
     // If it's possible to reserve some space, copy the contents
     if (reserve(size)) {
         strcpy(_buff, cstr);
         _len = size;
         return *this;
     }
     // If not, empty
     buffer_delete();
     return *this;
 }
copy() [2/2]
String & String::copy (const FlashString * pstr, uint16_t size) protected
Tries to copy a progmem character array into the string buffer. If it's not possible, reset the buffer.
Parameters
pstr Progmem string.
size Size of the string.
Returns
Modified string.
Definition at line 476 of file string.cpp.
References _buff, _len, buffer_delete(), and reserve().
{
     // If it's possible to reserve some space, copy the contents
     if (reserve(size)) {
         _len = size;
         strcpy_P(_buff, (PGM_P)pstr);
         return *this;
     }
     // If not, empty
     buffer_delete();
     return *this;
 }
move()
void String::move (String & str) protected
Tries to move the contents of 'str' to the string, after this deletes 'str'.
Parameters
str String to be moved.
Definition at line 488 of file string.cpp.
References _buff, _cap, _len, and buffer_delete().
{
     if (_buff) {
         if (str && (_cap >= str._len)) {
             strcpy(_buff, str._buff);
             _len = str._len;
             str.buffer_delete();
             return;
         } else {
             free(_buff);
         }
     }
     _buff = str._buff;
     _cap = str._cap;
     _len = str._len;
     str.buffer_delete();
 }
Member Data Documentation
_buff
char* String::_buff protected
The actual string.
Definition at line 422 of file string.h.
Referenced by begin(), buffer_change(), buffer_delete(), buffer_init(), compare_to(), concat(), copy(), end(), ends_with(), get_bytes(), get_substring(), index_of(), is_equal_to(), last_index_of(), move(), operator if_bool_type(), operator=(), operator[](), remove(), replace(), reserve(), resize(), set_char(), start_with(), to_double(), to_int(), to_lower_case(), to_upper_case(), and trim().
_len
uint16_t String::_len protected
The string length (Not counting the final '\0').
Definition at line 423 of file string.h.
Referenced by buffer_init(), compare_to(), concat(), copy(), end(), ends_with(), get_bytes(), get_length(), get_substring(), index_of(), is_equal_to(), last_index_of(), move(), operator=(), operator[](), remove(), replace(), resize(), set_char(), start_with(), and trim().
_cap
uint16_t String::_cap protected
The array length minus one (reserve for '\0').
Definition at line 424 of file string.h.
Referenced by buffer_change(), buffer_init(), get_capacity(), move(), replace(), reserve(), resize(), and set_char().
The documentation for this class was generated from the following files:
utils/string.h
utils/string.cpp