AVRLibs: SPI Class Reference
SPI Class Reference
SPI bus general implementation.
#include <spi.h>
Classes
class Device
SPI device class. Use this class to simplify the SPI device creation and configuration.
Public Member Functions
void disable (void)
Disable the SPI bus.
void enable (void)
Configure the MOSI, MISO, SCLK and SS pins for master operation.
void start (spi_conf_t *conf)
Start the SPI bus as master with the given configuration.
void get_config (spi_conf_t *conf)
Initialize the master configuration struct with the default values: F_CPU/4[Hz], SPI_MODE_0, MSB_FIRST.
void get_config (spi_conf_t *conf, uint32_t freq, spi_tx_mode_t tx_mode, spi_ds_mode_t bit_order)
Set the SPI configuration.
uint8_t transfer (uint8_t data)
The master send a single byte to the slave and returns it's response.
void transfer (uint8_t *src, uint8_t *rec, size_t size, uint8_t off=0, uint16_t dly=0)
Perform a data transfer between the SPI master and the slave. Send "size" bytes from "src" and save the responses on "rec". The method allow to start saving the responses after "offset" bytes sent (the master will send "offset" dummy bytes after "src" is transmitted to get the full response) and add delay after each transfer.
void write (uint8_t src, uint16_t dly=0)
write(uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
void write (uint8_t *src, size_t size, uint16_t dly=0)
Write "size" bytes from "src" to the slave.
void write_reg (uint8_t reg, uint8_t src, uint16_t dly)
void write_reg (uint8_t reg, uint8_t *src, size_t size, uint16_t dly)
Handler of spi_master_write() to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave.
void read (uint8_t *rec, size_t size, uint16_t dly=0)
Read "size" bytes from the slave to "rec".
void read_reg (uint8_t reg, uint8_t *rec, uint16_t dly)
void read_reg (uint8_t reg, uint8_t *rec, size_t size, uint16_t dly)
Handler of spi_master_read() to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave and copy them to "rec".
bool enable (pins_t ss_int, fun_ptr_vd_vd fun=NULL)
Prepare the MOSI, MISO, SCLK and SS pins for slave operation and start the slave routine. The SS pin of the board has to be connected to a pin with external or pin-change interrupt capabilities (used to control the SPI flow). It's possible to set a user-defined function that executes before the slave interruption is handled (if required).
void on_receive (fun_ptr_u8_u8 fun)
Set a user-defined function to handle the data received from the master. The input of the function is the byte received and the output is the response generated. By default the slave will send 0x00 for every byte received.
Static Public Member Functions
static SPI * get_instance (void)
Get this class instance.
static void delete_instance (void)
Deletes the actual instance. This action turns off the interface and reset its configurations.
Private Types
enum spi_mode_t { SPI_NONE, SPI_MASTER, SPI_SLAVE }
SPI modes.
Private Member Functions
SPI (void)
SPI constructor.
uint8_t get_prescaler (uint32_t freq)
Calculate the most adequate prescaler depending on the selected frequency.
Static Private Member Functions
static uint8_t on_receive_callback (uint8_t m_data)
Internal slave on receive ISR callback.
static void on_request_callback (void)
Internal slave on request ISR callback.
Private Attributes
volatile spi_mode_t _mode
SPI mode.
Static Private Attributes
static SPI * _inst = NULL
Device Singleton.
static pins_t _ss_pin
Slave SS interrupt pin.
static bool _slave_active
Slave on-request flag.
static fun_ptr_u8_u8 _user_on_receive
Slave on receive ISR callback.
static fun_ptr_vd_vd _user_on_request
Slave on request ISR callback.
Friends
void SPI_STC_vect ()
Used to make available private SPI methods on the ISR.
Detailed Description
SPI bus general implementation.
Definition at line 19 of file spi.h.
Member Enumeration Documentation
spi_mode_t
enum SPI::spi_mode_t private
SPI modes.
Enumerator
SPI_NONE
SPI not configured.
SPI_MASTER
SPI master mode.
SPI_SLAVE
SPI slave mode.
Definition at line 263 of file spi.h.
                  {
         SPI_NONE,
         SPI_MASTER,
         SPI_SLAVE
     } spi_mode_t;
Constructor & Destructor Documentation
SPI()
SPI::SPI (void) private
SPI constructor.
Definition at line 287 of file spi.cpp.
References _slave_active, _ss_pin, _user_on_receive, _user_on_request, fun_u8_u8_dummy(), fun_vd_vd_dummy(), and timing_enable().
Referenced by get_instance().
              {
     // Start the SPI configuration
     _ss_pin = NO_PIN;
     _slave_active = false;
     _user_on_receive = fun_u8_u8_dummy;
     _user_on_request = fun_vd_vd_dummy;
     // Start the timing functions
     timing_enable();
 }
Member Function Documentation
get_instance()
SPI * SPI::get_instance (void) static
Get this class instance.
Returns
Device singleton.
Definition at line 17 of file spi.cpp.
References _inst, and SPI().
{
     if (!_inst) _inst = new SPI();
     return _inst;
 }
delete_instance()
void SPI::delete_instance (void) static
Deletes the actual instance. This action turns off the interface and reset its configurations.
Definition at line 22 of file spi.cpp.
References _inst, and disable().
{
     if (!_inst) return;
     _inst->disable();
     delete _inst;
     _inst = NULL;
 }
disable()
void SPI::disable (void)
Disable the SPI bus.
Definition at line 30 of file spi.cpp.
References _BV, and ATOMIC.
Referenced by delete_instance().
                       {
     // Disable SPI (and the interrupts)
     ATOMIC({
         SPCR &= ~(_BV(SPIE) | _BV(SPE));
     });
 }
enable() [1/2]
void SPI::enable (void)
Configure the MOSI, MISO, SCLK and SS pins for master operation.
Definition at line 38 of file spi.cpp.
References _mode, INPUT, OUTPUT, pin_mode(), pin_write(), and SPI_MASTER.
                      {
     // Set SPI mode
     _mode = SPI_MASTER;
     // Set SS as master
     pin_mode(SS, OUTPUT);
     pin_write(SS, true);
     // Set SCK, MOSI and MISO
     pin_mode(SCK,  OUTPUT);
     pin_mode(MOSI, OUTPUT);
     pin_mode(MISO, INPUT);
 }
start()
void SPI::start (spi_conf_t * conf)
Start the SPI bus as master with the given configuration.
Parameters
conf Pointer to SPI bus configuration spi_conf_t.
Definition at line 50 of file spi.cpp.
References _mode, ATOMIC, spi_conf_t::ctrl, spi_ctrl_t::raw, spi_stat_t::raw, SPI_MASTER, and spi_conf_t::stat.
Referenced by SPI::Device::begin_transaction().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return;
     // Setup with given config.
     ATOMIC({
         SPCR = conf->ctrl.raw;
         SPSR = conf->stat.raw;
     });
 }
get_config() [1/2]
void SPI::get_config (spi_conf_t * conf)
Initialize the master configuration struct with the default values: F_CPU/4[Hz], SPI_MODE_0, MSB_FIRST.
Parameters
conf Pointer to SPI bus configuration spi_conf_t.
Definition at line 61 of file spi.cpp.
References MSB_FIRST, SPI_MAX_FREQ, and SPI_MODE_0.
Referenced by SPI::Device::configure(), and SPI::Device::Device().
{
     get_config(conf, SPI_MAX_FREQ/2, SPI_MODE_0, MSB_FIRST);
 }
get_config() [2/2]
void SPI::get_config (spi_conf_t * conf, uint32_t freq, spi_tx_mode_t tx_mode, spi_ds_mode_t bit_order)
Set the SPI configuration.
Parameters
conf Pointer to SPI bus configuration spi_conf_t.
freq SPI SCLK frequency.
tx_mode SPI transmission mode spi_tx_mode_t.
bit_order SPI data transmission mode spi_ds_mode_t.
Definition at line 65 of file spi.cpp.
References spi_spcr_t::cconf, spi_conf_t::ctrl, spi_spcr_t::dord, spi_ctrl_t::field, spi_stat_t::field, get_prescaler(), spi_spcr_t::mstr, spi_ctrl_t::raw, spi_stat_t::raw, spi_spcr_t::spe, spi_spsr_t::spi2x, SPI_MAX_FREQ, spi_spcr_t::spr, and spi_conf_t::stat.
{
     // Get prescaler
     uint8_t prescaler = (freq > SPI_MAX_FREQ) ? get_prescaler(SPI_MAX_FREQ) : get_prescaler(freq);
     // Set control register
     conf->ctrl.raw          = 0x00;
     conf->ctrl.field.spe    = true;
     conf->ctrl.field.mstr   = true;
     conf->ctrl.field.dord   = bit_order;
     conf->ctrl.field.cconf  = tx_mode;
     conf->ctrl.field.spr    = (prescaler & 0x03);
     // Set last prescaler bit on status register
     conf->stat.raw          = 0x00;
     conf->stat.field.spi2x  = ((prescaler >> 2) & 0x01);
 }
transfer() [1/2]
uint8_t SPI::transfer (uint8_t data)
The master send a single byte to the slave and returns it's response.
Parameters
data Byte to send.
Returns
Slave response byte.
Definition at line 81 of file spi.cpp.
References _mode, and SPI_MASTER.
Referenced by read(), transfer(), SPI::Device::transfer(), and write().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return 0x00;
     // Prepare data
     SPDR = data;
     // Wait until the data is sent
     __asm__ __volatile__("nop" ::: "memory");
     loop_until_bit_is_set(SPSR, SPIF);
     // Return data received
     return SPDR;
 }
transfer() [2/2]
void SPI::transfer (uint8_t * src, uint8_t * rec, size_t size, uint8_t off = 0, uint16_t dly = 0)
Perform a data transfer between the SPI master and the slave. Send "size" bytes from "src" and save the responses on "rec". The method allow to start saving the responses after "offset" bytes sent (the master will send "offset" dummy bytes after "src" is transmitted to get the full response) and add delay after each transfer.
Parameters
src Pointer to source byte array.
rec Pointer to received byte array.
size Bytes to be transfered.
off Offset (in bytes).
dly Time to wait between transfers (in [us]).
Definition at line 94 of file spi.cpp.
References _mode, delay_micros(), SPI_MASTER, and transfer().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return;
     // Check buffers
     if ((size == 0) || (src == NULL) || (rec == NULL))
         return;
     // Prepare
     uint8_t state = (off > 0)? 0 : 1;
     // Transfer
     for (uint16_t idx = 0; idx < (size + off); idx++) {
         switch (state) {
             case 0: {
                 transfer(*src++);
                 if (idx >= (uint8_t)(off - 1)) state = 1;
             } break;
             case 1: {
                 *rec++ = transfer(*src++);
                 if (idx >= (uint8_t)(size - 1)) state = 2;
             } break;
             case 2: {
                 *rec++ = transfer(0x00);
             } break;
         }
         if (dly > 0) delay_micros(dly);
     }
 }
write() [1/2]
void SPI::write (uint8_t src, uint16_t dly = 0)
write(uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
Parameters
src Source byte.
dly Time to wait after write (in [us]).
Definition at line 122 of file spi.cpp.
Referenced by read_reg(), SPI::Device::write(), and write_reg().
{
     write(&src, 1, dly);
 }
write() [2/2]
void SPI::write (uint8_t * src, size_t size, uint16_t dly = 0)
Write "size" bytes from "src" to the slave.
Parameters
src Pointer to source byte array.
size Bytes to be transmitted.
dly Time to wait between writes (in [us]).
Definition at line 126 of file spi.cpp.
References _mode, delay_micros(), SPI_MASTER, and transfer().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return;
     // Check buffer
     if ((size == 0) || (src == NULL))
         return;
     // Send
     while (size--) {
         transfer(*src++);
         if (dly > 0) delay_micros(dly);
     }
 }
write_reg() [1/2]
void SPI::write_reg (uint8_t reg, uint8_t src, uint16_t dly)
brief write_reg(uint8_t, uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
Parameters
reg Slave register address.
src Source byte.
dly Time to wait after write (in [us]).
Definition at line 140 of file spi.cpp.
Referenced by SPI::Device::write_reg().
{
     write_reg(reg, &src, 1, dly);
 }
write_reg() [2/2]
void SPI::write_reg (uint8_t reg, uint8_t * src, size_t size, uint16_t dly)
Handler of spi_master_write() to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave.
Parameters
reg Slave register address.
src Pointer to source byte array.
size Bytes to be transmitted.
dly Time to wait between writes (in [us]).
Definition at line 144 of file spi.cpp.
References _mode, SPI_MASTER, and write().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return;
     // Check buffer
     if ((size == 0) || (src == NULL))
         return;
     // Put the "reg" and "src" in one auxiliary array and send
     uint8_t* reg_src = (uint8_t*) malloc((size + 1));
     memcpy(reg_src, &reg, 1);
     memcpy((reg_src + 1), src, size);
     // Write the register
     write(reg_src, size, dly);
     // Free the auxiliary space
     free(reg_src);
 }
read()
void SPI::read (uint8_t * rec, size_t size, uint16_t dly = 0)
Read "size" bytes from the slave to "rec".
Parameters
rec Pointer to received byte array.
size Bytes to be read.
dly Time to wait between reads (in [us]).
Definition at line 162 of file spi.cpp.
References _mode, delay_micros(), SPI_MASTER, and transfer().
Referenced by SPI::Device::read(), and read_reg().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return;
     // Check buffer
     if ((size == 0) || (rec == NULL))
         return;
     // Receive
     while (size--) {
         *rec++ = transfer(0x00);
         if (dly > 0) delay_micros(dly);
     }
 }
read_reg() [1/2]
void SPI::read_reg (uint8_t reg, uint8_t * rec, uint16_t dly)
brief read_reg(uint8_t, uint8_t*, uint8_t, uint16_t) handler for 1 byte "rec".
Parameters
reg Slave register address.
rec Receive byte.
dly Time to wait after write (in [us]).
Definition at line 176 of file spi.cpp.
Referenced by SPI::Device::read_reg().
{
     read_reg(reg, rec, 1, dly);
 }
read_reg() [2/2]
void SPI::read_reg (uint8_t reg, uint8_t * rec, size_t size, uint16_t dly)
Handler of spi_master_read() to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave and copy them to "rec".
Parameters
reg Slave register address.
rec Pointer to received byte array.
size Bytes to be read.
dly Time to wait between reads (in [us]).
Definition at line 180 of file spi.cpp.
References _mode, read(), SPI_MASTER, and write().
{
     // Only for master mode
     if (_mode != SPI_MASTER)
         return;
     // Check buffer
     if ((size == 0) || (rec == NULL))
         return;
     // Write the register
     write(&reg, 1, dly);
     // Read the data
     read(rec, size, dly);
 }
enable() [2/2]
bool SPI::enable (pins_t ss_int, fun_ptr_vd_vd fun = NULL)
Prepare the MOSI, MISO, SCLK and SS pins for slave operation and start the slave routine. The SS pin of the board has to be connected to a pin with external or pin-change interrupt capabilities (used to control the SPI flow). It's possible to set a user-defined function that executes before the slave interruption is handled (if required).
Parameters
ss_int Board pin value, interrupt compatible.
fun ISR callback.
Returns
Return if it was possible to set the SPI as slave. If it was a success returns true, else returns false.
Definition at line 255 of file spi.cpp.
References _BV, _mode, _ss_pin, _user_on_request, ATOMIC, CHANGE, fun_vd_vd_dummy(), INPUT, INPUT_PULLUP, int_ext_attach(), int_pc_attach(), on_request_callback(), OUTPUT, pin_mode(), and SPI_SLAVE.
{
     bool status;
     // Set user-defined callbacks.
     _user_on_request = (fun)? fun : fun_vd_vd_dummy;
     // Set pin interrupt: try first with external, if not, with pin-change
     pin_mode(ss_int, INPUT_PULLUP);
     status = int_ext_attach(ss_int, on_request_callback, CHANGE);
     status = (!status)? int_pc_attach(ss_int, on_request_callback, CHANGE) : status;
     if (status) {
         // Save pin
         _ss_pin = ss_int;
         // Set SPI mode
         _mode = SPI_SLAVE;
         // Set SS as slave
         pin_mode(SS,   INPUT_PULLUP);
         // Set SCK, MOSI and MISO
         pin_mode(SCK,  INPUT);
         pin_mode(MOSI, INPUT);
         pin_mode(MISO, OUTPUT);
         // Enable interrupts
         ATOMIC({
             SPCR |= (_BV(SPE) | _BV(SPIE));
         });
     }
     return status;
 }
on_receive()
void SPI::on_receive (fun_ptr_u8_u8 fun)
Set a user-defined function to handle the data received from the master. The input of the function is the byte received and the output is the response generated. By default the slave will send 0x00 for every byte received.
Parameters
fun ISR callback.
Definition at line 282 of file spi.cpp.
References _user_on_receive, and fun_u8_u8_dummy().
{
     _user_on_receive = (fun)? fun : fun_u8_u8_dummy;
 }
get_prescaler()
uint8_t SPI::get_prescaler (uint32_t freq) private
Calculate the most adequate prescaler depending on the selected frequency.
Returns
Prescaler value.
Definition at line 299 of file spi.cpp.
Referenced by get_config().
{
     uint32_t scale = F_CPU / freq;
     if (scale <= 2)  return 0x04;
     if (scale <= 4)  return 0x00;
     if (scale <= 8)  return 0x05;
     if (scale <= 16) return 0x01;
     if (scale <= 32) return 0x06;
     if (scale <= 64) return 0x07;
     return 0x03;
 }
on_receive_callback()
uint8_t SPI::on_receive_callback (uint8_t m_data) static private
Internal slave on receive ISR callback.
Parameters
m_data Byte received from the master.
Definition at line 311 of file spi.cpp.
References _slave_active, and _user_on_receive.
Referenced by ISR().
{
     if (!_slave_active)
         return 0x00;
     return _user_on_receive(m_data);
 }
on_request_callback()
void SPI::on_request_callback (void) static private
Internal slave on request ISR callback.
Definition at line 317 of file spi.cpp.
References _slave_active, _ss_pin, _user_on_request, and pin_read().
Referenced by enable().
{
     if (pin_read(_ss_pin)) {
         _slave_active = false;
     } else {
         _slave_active = true;
         _user_on_request();
     }
 }
Friends And Related Function Documentation
SPI_STC_vect
void SPI_STC_vect () friend
Used to make available private SPI methods on the ISR.
Member Data Documentation
_inst
SPI * SPI::_inst = NULL static private
Device Singleton.
Device singleton initialization.
Definition at line 255 of file spi.h.
Referenced by delete_instance(), and get_instance().
_mode
volatile spi_mode_t SPI::_mode private
SPI mode.
Definition at line 270 of file spi.h.
Referenced by enable(), read(), read_reg(), start(), transfer(), write(), and write_reg().
_ss_pin
pins_t SPI::_ss_pin static private
Slave SS interrupt pin.
Definition at line 271 of file spi.h.
Referenced by enable(), on_request_callback(), and SPI().
_slave_active
bool SPI::_slave_active static private
Slave on-request flag.
Definition at line 272 of file spi.h.
Referenced by on_receive_callback(), on_request_callback(), and SPI().
_user_on_receive
fun_ptr_u8_u8 SPI::_user_on_receive static private
Slave on receive ISR callback.
Definition at line 273 of file spi.h.
Referenced by on_receive(), on_receive_callback(), and SPI().
_user_on_request
fun_ptr_vd_vd SPI::_user_on_request static private
Slave on request ISR callback.
Definition at line 274 of file spi.h.
Referenced by enable(), on_request_callback(), and SPI().
The documentation for this class was generated from the following files:
hardware/spi.h
hardware/spi.cpp