AVRLibs: LIS3DH Class Reference
LIS3DH Class Reference
LIS3DH driver class.
#include <lis3dh.h>
Public Member Functions
LIS3DH (TWI *twi, uint8_t addr)
LIS3DH constructor. For TWI mode.
LIS3DH (SPI *spi, pins_t ss_pin)
LIS3DH constructor. For SPI mode.
bool is_available (void)
Check if the device is available.
bool enable (void)
Initialize the device.
void set_defaults (void)
Set all the configuration registers to the default values.
void set_mode (lis3dh_odr_t odr, lis3dh_res_t res, lis3dh_bdu_t bdu, bool x_en, bool y_en, bool z_en)
Set sensor mode.
void set_scale (lis3dh_scale_t scale)
Set sensor scale.
lis3dh_scale_t get_scale (void)
Get the sensor scale.
lis3dh_res_t get_resolution (void)
Get the sensor resolution.
bool is_data_available (void)
Get if data is available.
void get_accel (lis3dh_accel_t *accel)
Read the acceleration value.
void adc_enable (bool adc, bool temp)
Enable/Disable the ADC lines or temperature sensor.
void get_adc (lis3dh_adc_t *adc)
Read all the ADC lines.
void fifo_enable (lis3dh_fifo_t mode, uint8_t wtm, bool wtm_int=true, bool ovr_int=false, bool tr=false)
Enable the FIFO with a given mode. In the case that "stream to fifo" mode is configured, the interruption source has to be defined.
void fifo_disable (void)
Disable the FIFO mode.
lis3dh_reg_fifo_src_t fifo_get_state (void)
Get the FIFO state.
lis3dh_reg_fifo_src_t fifo_get_data (lis3dh_accel_t *data, uint8_t len)
Read bulk data from FIFO buffer.
void int_polarity (bool pol=false)
Set the interruption polarity.
void int_set_parameters (lis3dh_int_t signal, uint8_t ths, uint8_t dur, bool latch)
Set the interrupt general parameters on signal INT1 or INT2.
void int_data_enable (lis3dh_int_t signal, lis3dh_int_type_t type, bool enable)
Configure an interrupt on signal INT1 or INT2.
void get_int_data_src (lis3dh_int_src_t *source)
Get the source of the interruption (FIFO or data ready) for signal INT1.
void int_data_disable (lis3dh_int_t signal)
Disable interrupts on signal INT1 or INT2.
void int_event_enable (lis3dh_int_t signal, lis3dh_int_evt_t event, uint8_t axis_mask)
Set the configuration of an inertial event interrupt generator on signal INT1 or INT2. The interrupt occurs when the acceleration of the defined axis is lower than a defined threshold and one defined event occurs.
void get_int_event_src (lis3dh_int_t signal, lis3dh_reg_intx_src_t *source)
Get the source of the inertial event for signal INT1/INT2.
void int_event_disable (lis3dh_int_t signal)
Disable the configuration of an inertial event on signal INT1 or INT2.
void click_enable (uint8_t axis_mask, bool sclick, bool dclick, uint8_t ths, uint8_t tlim, uint8_t tlat, uint8_t twin, bool latch)
Enable the click driven interruption with the given configuration.
void click_disable (void)
Disable the click driven interruption.
void get_click_src (lis3dh_reg_click_src_t *source)
Read the click source register.
void activity_enable (uint8_t ths, uint8_t dur)
Enable the activity dependent power mode.
void activity_disable (void)
Disable the activity dependent power mode.
void hpf_configure (lis3dh_hpm_t mode, lis3dh_hpcf_t cf, bool fds, bool click, bool ia1, bool ia2)
Configure the high-pass filter.
void hpd_reset (void)
Reset to default the filter configurations.
void get_reference (uint8_t *source)
Get the reference source register.
Protected Member Functions
void configure (uint32_t freq, spi_tx_mode_t tx_mode, spi_ds_mode_t bit_order)
Set the configuration required to communicate with the device.
void begin_transaction (void)
Activate the device changing the state of the SS pin.
void end_transaction (void)
Deactivate the device changing the state of the SS pin.
uint8_t transfer (uint8_t data)
The master send a single byte to the slave and returns it's response.
void transfer (uint8_t *src, uint8_t *rec, size_t size, uint8_t off=0, uint16_t dly=0)
Perform a data transfer between the SPI master and the slave. Send "size" bytes from "src" and save the responses on "rec". The method allow to start saving the responses after "offset" bytes sent (the master will send "offset" dummy bytes after "src" is transmitted to get the full response) and add delay after each transfer.
void write (uint8_t src, uint16_t dly=0)
write(uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
void write (uint8_t *src, size_t size, uint16_t dly=0)
Write "size" bytes from "src" to the slave.
void write_reg (uint8_t reg, uint8_t src, uint16_t dly=0)
void write_reg (uint8_t reg, uint8_t *src, size_t size, uint16_t dly=0)
Handler of spi_master_write() to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave.
void read (uint8_t *rec, size_t size, uint16_t dly=0)
Read "size" bytes from the slave to "rec".
void read_reg (uint8_t reg, uint8_t *rec, uint16_t dly=0)
void read_reg (uint8_t reg, uint8_t *rec, size_t size, uint16_t dly=0)
Handler of spi_master_read() to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave and copy them to "rec".
uint16_t write (uint8_t src, bool stop=true)
TWI::write(uint8_t, uint8_t, bool) with the slave address fixed.
uint16_t write (uint8_t *src, size_t size, bool stop=true)
TWI::write(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t write_reg (uint8_t reg, uint8_t src, bool stop=true)
TWI::write_reg(uint8_t, uint8_t, uint8_t, bool) with the slave address fixed.
uint16_t write_reg (uint8_t reg, uint8_t *src, size_t size, bool stop=true)
TWI::write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t read (uint8_t *rec, bool stop)
TWI::read(uint8_t, uint8_t*, bool) with the slave address fixed.
uint16_t read (uint8_t *rec, size_t size, bool stop=true)
TWI::read(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t read_reg (uint8_t reg, uint8_t *rec, bool stop=true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, bool) with the slave address fixed.
uint16_t read_reg (uint8_t reg, uint8_t *rec, size_t size, bool stop=true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Protected Attributes
SPI * _dev_spi
SPI manager.
spi_conf_t _dev_conf
SPI settings.
pins_t _dev_ss
Device SS.
bool _dev_on
Device on SS status.
TWI * _dev_twi
TWI manager.
uint8_t _dev_addr
Device address.
Private Member Functions
uint8_t get_accel_conversion (void)
Get the compensation value needed to adjust the accelerometer values in dependence with the resolution and power mode of the device.
void set_register (uint8_t src, uint8_t reg)
Write "src" to "reg" register.
void get_register (uint8_t *rec, uint8_t reg)
LIS3DH::get_register(uint8_t*, uint8_t, uint8_t) handler to get a single byte.
void get_registers (uint8_t *rec, uint8_t reg, uint8_t len)
read a "len" number of registers on "rec" starting from "reg" register.
Private Attributes
bool _is_spi
TWI/SPI selector.
lis3dh_t _config
Sensor configuration.
Detailed Description
LIS3DH driver class.
Definition at line 17 of file lis3dh.h.
Constructor & Destructor Documentation
LIS3DH() [1/2]
LIS3DH::LIS3DH (TWI * twi, uint8_t addr)
LIS3DH constructor. For TWI mode.
Parameters
twi TWI bus manager.
addr Device address (SDO pin dependent).
Definition at line 15 of file lis3dh.cpp.
References timing_enable().
                                     : SPI::Device(), TWI::Device(twi, addr), _is_spi(false) {
     // Start the timing functions
     timing_enable();
 }
LIS3DH() [2/2]
LIS3DH::LIS3DH (SPI * spi, pins_t ss_pin)
LIS3DH constructor. For SPI mode.
Parameters
spi SPI bus manager.
ss_pin Device SS pin.
Definition at line 20 of file lis3dh.cpp.
References SPI::Device::configure(), MSB_FIRST, SPI_MODE_3, and timing_enable().
                                      : SPI::Device(spi, ss_pin), TWI::Device(), _is_spi(true) {
     // Configure the SPI device
     SPI::Device::configure(F_CPU/4, SPI_MODE_3, MSB_FIRST);
     // Start the timing functions
     timing_enable();
 }
Member Function Documentation
is_available()
bool LIS3DH::is_available (void)
Check if the device is available.
Returns
If the device is available true, else false.
Definition at line 29 of file lis3dh.cpp.
References get_register(), LIS3DH_DEF_ID, LIS3DH_REG_ID, and lis3dh_reg_t::raw.
Referenced by enable().
{
     lis3dh_reg_t reg;
     // Read ID
     get_register(&reg.raw, LIS3DH_REG_ID);
     // Return
     return (reg.raw == LIS3DH_DEF_ID);
 }
enable()
bool LIS3DH::enable (void)
Initialize the device.
Returns
If was possible to initialize the device.
Definition at line 37 of file lis3dh.cpp.
References _config, lis3dh_t::fifo_mode, get_accel_conversion(), is_available(), LIS3DH_BDU_ON_READ, LIS3DH_BYPASS, LIS3DH_LOWPOWER, LIS3DH_REG_CTRL4, LIS3DH_SCALE_2G, lis3dh_t::mg_dig, lis3dh_t::resolution, lis3dh_t::scale, set_defaults(), and update_field.
Referenced by int_data_enable().
{
     // Check if the device is available
     if (!is_available())
         return false;
     // Set default values
     set_defaults();
     // Set BDU on
     lis3dh_reg_t reg;
     update_field(reg, LIS3DH_REG_CTRL4, ctrl4, BDU, LIS3DH_BDU_ON_READ);
     // Set configuration
     _config.scale = LIS3DH_SCALE_2G;
     _config.fifo_mode = LIS3DH_BYPASS;
     _config.resolution = LIS3DH_LOWPOWER;
     _config.mg_dig = get_accel_conversion();
     // Return
     return true;
 }
set_defaults()
void LIS3DH::set_defaults (void)
Set all the configuration registers to the default values.
Definition at line 55 of file lis3dh.cpp.
References LIS3DH_DEF_ACT_DUR, LIS3DH_DEF_ACT_THS, LIS3DH_DEF_CLICK_CFG, LIS3DH_DEF_CLICK_THS, LIS3DH_DEF_CTRL0, LIS3DH_DEF_CTRL1, LIS3DH_DEF_CTRL2, LIS3DH_DEF_CTRL3, LIS3DH_DEF_CTRL4, LIS3DH_DEF_CTRL5, LIS3DH_DEF_CTRL6, LIS3DH_DEF_FIFO_CTRL, LIS3DH_DEF_INT1_CFG, LIS3DH_DEF_INT1_DUR, LIS3DH_DEF_INT1_THS, LIS3DH_DEF_INT2_CFG, LIS3DH_DEF_INT2_DUR, LIS3DH_DEF_INT2_THS, LIS3DH_DEF_REF, LIS3DH_DEF_TEMP_CFG, LIS3DH_DEF_TIME_LAT, LIS3DH_DEF_TIME_LIM, LIS3DH_DEF_TIME_WIN, LIS3DH_REG_ACT_DUR, LIS3DH_REG_ACT_THS, LIS3DH_REG_CLICK_CFG, LIS3DH_REG_CLICK_THS, LIS3DH_REG_CTRL0, LIS3DH_REG_CTRL1, LIS3DH_REG_CTRL2, LIS3DH_REG_CTRL3, LIS3DH_REG_CTRL4, LIS3DH_REG_CTRL5, LIS3DH_REG_CTRL6, LIS3DH_REG_FIFO_CTRL, LIS3DH_REG_INT1_CFG, LIS3DH_REG_INT1_DUR, LIS3DH_REG_INT1_THS, LIS3DH_REG_INT2_CFG, LIS3DH_REG_INT2_DUR, LIS3DH_REG_INT2_THS, LIS3DH_REG_REF, LIS3DH_REG_TEMP_CFG, LIS3DH_REG_TIME_LAT, LIS3DH_REG_TIME_LIM, LIS3DH_REG_TIME_WIN, and set_register().
Referenced by enable().
{
     // Reboot memory content
     set_register(LIS3DH_DEF_TEMP_CFG, LIS3DH_REG_TEMP_CFG);
     set_register(LIS3DH_DEF_CTRL0,      LIS3DH_REG_CTRL0);
     set_register(LIS3DH_DEF_CTRL1,      LIS3DH_REG_CTRL1);
     set_register(LIS3DH_DEF_CTRL2,      LIS3DH_REG_CTRL2);
     set_register(LIS3DH_DEF_CTRL3,      LIS3DH_REG_CTRL3);
     set_register(LIS3DH_DEF_CTRL4,      LIS3DH_REG_CTRL4);
     set_register(LIS3DH_DEF_CTRL5,      LIS3DH_REG_CTRL5);
     set_register(LIS3DH_DEF_CTRL6,      LIS3DH_REG_CTRL6);
     set_register(LIS3DH_DEF_REF,        LIS3DH_REG_REF);
     set_register(LIS3DH_DEF_FIFO_CTRL,  LIS3DH_REG_FIFO_CTRL);
     set_register(LIS3DH_DEF_INT1_CFG,   LIS3DH_REG_INT1_CFG);
     set_register(LIS3DH_DEF_INT1_THS,   LIS3DH_REG_INT1_THS);
     set_register(LIS3DH_DEF_INT1_DUR,   LIS3DH_REG_INT1_DUR);
     set_register(LIS3DH_DEF_INT2_CFG,   LIS3DH_REG_INT2_CFG);
     set_register(LIS3DH_DEF_INT2_THS,   LIS3DH_REG_INT2_THS);
     set_register(LIS3DH_DEF_INT2_DUR,   LIS3DH_REG_INT2_DUR);
     set_register(LIS3DH_DEF_CLICK_CFG,  LIS3DH_REG_CLICK_CFG);
     set_register(LIS3DH_DEF_CLICK_THS,  LIS3DH_REG_CLICK_THS);
     set_register(LIS3DH_DEF_TIME_LIM,   LIS3DH_REG_TIME_LIM);
     set_register(LIS3DH_DEF_TIME_LAT,   LIS3DH_REG_TIME_LAT);
     set_register(LIS3DH_DEF_TIME_WIN,   LIS3DH_REG_TIME_WIN);
     set_register(LIS3DH_DEF_ACT_THS,    LIS3DH_REG_ACT_THS);
     set_register(LIS3DH_DEF_ACT_DUR,    LIS3DH_REG_ACT_DUR);
 }
set_mode()
void LIS3DH::set_mode (lis3dh_odr_t odr, lis3dh_res_t res, lis3dh_bdu_t bdu, bool x_en, bool y_en, bool z_en)
Set sensor mode.
Parameters
odr Sensor Output Data Rate (ODR).
res Sensor resolution.
bdu Set block data update.
x_en Enable X-axis.
y_en Enable Y-axis.
z_en Enable Z-axis.
Definition at line 82 of file lis3dh.cpp.
References _config, lis3dh_reg_ctrl4_t::BDU, lis3dh_reg_t::ctrl1, lis3dh_reg_t::ctrl4, delay_micros(), get_accel_conversion(), get_register(), lis3dh_reg_ctrl4_t::HR, LIS3DH_HIGHRES, LIS3DH_LOWPOWER, LIS3DH_REG_CTRL1, LIS3DH_REG_CTRL4, lis3dh_reg_ctrl1_t::LP_EN, lis3dh_t::mg_dig, lis3dh_reg_ctrl1_t::ODR, lis3dh_reg_t::raw, lis3dh_t::resolution, set_register(), and lis3dh_reg_ctrl1_t::X_EN.
{
     lis3dh_reg_t reg;
     // Set resolution and BDU
     get_register(&reg.raw, LIS3DH_REG_CTRL4);
     reg.ctrl4.BDU = bdu;
     reg.ctrl4.HR = (res == LIS3DH_HIGHRES);
     set_register(reg.raw, LIS3DH_REG_CTRL4);
     // Set mode
     get_register(&reg.raw, LIS3DH_REG_CTRL1);
     reg.ctrl1.LP_EN = (res == LIS3DH_LOWPOWER);
     reg.ctrl1.X_EN = x;
     reg.ctrl1.X_EN = y;
     reg.ctrl1.X_EN = z;
     reg.ctrl1.ODR  = odr;
     set_register(reg.raw, LIS3DH_REG_CTRL1);
     // Give the device time to restart
     delay_micros(200);
     // Update config
     _config.resolution = res;
     _config.mg_dig = get_accel_conversion();
 }
set_scale()
void LIS3DH::set_scale (lis3dh_scale_t scale)
Set sensor scale.
Parameters
scale Full range scale.
Definition at line 104 of file lis3dh.cpp.
References _config, get_accel_conversion(), LIS3DH_REG_CTRL4, lis3dh_t::mg_dig, lis3dh_t::scale, and update_field.
{
     lis3dh_reg_t reg;
     // Set scale
     update_field(reg, LIS3DH_REG_CTRL4, ctrl4, FS, scale);
     // Update config
     _config.scale = scale;
     _config.mg_dig = get_accel_conversion();
 }
get_scale()
lis3dh_scale_t LIS3DH::get_scale (void)
Get the sensor scale.
Returns
Full range scale.
Definition at line 113 of file lis3dh.cpp.
References _config, and lis3dh_t::scale.
{
     return _config.scale;
 }
get_resolution()
lis3dh_res_t LIS3DH::get_resolution (void)
Get the sensor resolution.
Returns
Sensor resolution.
Definition at line 117 of file lis3dh.cpp.
References _config, and lis3dh_t::resolution.
Referenced by get_adc().
{
     return _config.resolution;
 }
is_data_available()
bool LIS3DH::is_data_available (void)
Get if data is available.
Returns
True if is data available, false otherwise.
Definition at line 121 of file lis3dh.cpp.
References _config, lis3dh_reg_fifo_src_t::EMPTY, lis3dh_t::fifo_mode, lis3dh_reg_t::fifo_src, get_register(), LIS3DH_BYPASS, LIS3DH_REG_FIFO_SRC, LIS3DH_REG_STAT, lis3dh_reg_t::raw, lis3dh_reg_t::stat, and lis3dh_reg_stat_t::ZYXDA.
{
     lis3dh_reg_t reg;
     if (_config.fifo_mode == LIS3DH_BYPASS) {
         get_register(&reg.raw, LIS3DH_REG_STAT);
         return reg.stat.ZYXDA;
     } else {
         get_register(&reg.raw, LIS3DH_REG_FIFO_SRC);
         return !reg.fifo_src.EMPTY;
     }
 }
get_accel()
void LIS3DH::get_accel (lis3dh_accel_t * accel)
Read the acceleration value.
Parameters
accel Acceleration values (in [mg]).
Definition at line 133 of file lis3dh.cpp.
References _config, lis3dh_data_t::accel, get_registers(), lis3dh_accel_bits_t::high_res, LIS3DH_LOWPOWER, LIS3DH_NORMAL, LIS3DH_REG_X_OUT_L, lis3dh_accel_bits_t::low_power, lis3dh_t::mg_dig, lis3dh_accel_bits_t::normal, lis3dh_t::resolution, lis3dh_accel_t::x, lis3dh_accel_t::y, and lis3dh_accel_t::z.
Referenced by fifo_get_data().
{
     lis3dh_data_t   data[3];
     // Get values
     get_registers((uint8_t*)(&data), LIS3DH_REG_X_OUT_L, 6);
     // Transform
     switch(_config.resolution) {
         case LIS3DH_LOWPOWER: {
             accel->x = (data[0].accel.low_power.value << _config.mg_dig);
             accel->y = (data[1].accel.low_power.value << _config.mg_dig);
             accel->z = (data[2].accel.low_power.value << _config.mg_dig);
         } break;
         case LIS3DH_NORMAL: {
             accel->x = (data[0].accel.normal.value << _config.mg_dig);
             accel->y = (data[1].accel.normal.value << _config.mg_dig);
             accel->z = (data[2].accel.normal.value << _config.mg_dig);
         } break;
         default: {
             accel->x = (data[0].accel.high_res.value << _config.mg_dig);
             accel->y = (data[1].accel.high_res.value << _config.mg_dig);
             accel->z = (data[2].accel.high_res.value << _config.mg_dig);
         } break;
     }
 }
adc_enable()
void LIS3DH::adc_enable (bool adc, bool temp)
Enable/Disable the ADC lines or temperature sensor.
Parameters
adc Enable ADC.
temp Enable temperature sensor on ADC line 3.
Definition at line 158 of file lis3dh.cpp.
References lis3dh_reg_temp_cfg_t::ADC_EN, get_register(), LIS3DH_REG_TEMP_CFG, lis3dh_reg_t::raw, set_register(), lis3dh_reg_t::temp_cfg, and lis3dh_reg_temp_cfg_t::TEMP_EN.
{
     lis3dh_reg_t reg;
     // Enable ADC on TEMP_CFG
     get_register(&reg.raw, LIS3DH_REG_TEMP_CFG);
     reg.temp_cfg.ADC_EN = adc;
     reg.temp_cfg.TEMP_EN = temp;
     set_register(reg.raw, LIS3DH_REG_TEMP_CFG);
 }
get_adc()
void LIS3DH::get_adc (lis3dh_adc_t * adc)
Read all the ADC lines.
Parameters
adc ADC values.
Definition at line 167 of file lis3dh.cpp.
References lis3dh_data_t::adc, lis3dh_adc_bits_t::ADC10, lis3dh_adc_bits_t::ADC8, get_register(), get_registers(), get_resolution(), lis3dh_adc_t::l1, lis3dh_adc_t::l2, lis3dh_adc_t::l3, LIS3DH_LOWPOWER, LIS3DH_REG_ADC1_OUT_L, LIS3DH_REG_TEMP_CFG, lis3dh_reg_t::raw, lis3dh_reg_t::temp_cfg, and lis3dh_reg_temp_cfg_t::TEMP_EN.
{
     lis3dh_reg_t    reg;
     lis3dh_data_t   data[3];
     // Get values
     get_register(&reg.raw, LIS3DH_REG_TEMP_CFG);
     get_registers((uint8_t*)(&data), LIS3DH_REG_ADC1_OUT_L, 6);
     // Transform
     switch(get_resolution()) {
         case LIS3DH_LOWPOWER: {
             adc->l1 = data[0].adc.ADC8.value;
             adc->l2 = data[1].adc.ADC8.value;
             adc->l3 = data[2].adc.ADC8.value;
         } break;
         default: {
             adc->l1 = data[0].adc.ADC10.value;
             adc->l2 = data[1].adc.ADC10.value;
             adc->l3 = (reg.temp_cfg.TEMP_EN)? data[2].adc.ADC8.value : data[2].adc.ADC10.value;
         } break;
     }
 }
fifo_enable()
void LIS3DH::fifo_enable (lis3dh_fifo_t mode, uint8_t wtm, bool wtm_int = true, bool ovr_int = false, bool tr = false)
Enable the FIFO with a given mode. In the case that "stream to fifo" mode is configured, the interruption source has to be defined.
Parameters
mode FIFO mode.
wtm Watermark level.
wtm_int If a watermark interruption is generated.
ovr_int If an overrun interrupt is generated.
tr In case of "stream to fifo" mode is defined, this allow to select the interruption source: INT1(false), INT2(true).
Definition at line 190 of file lis3dh.cpp.
References lis3dh_reg_t::ctrl3, lis3dh_reg_t::fifo_ctrl, lis3dh_reg_fifo_ctrl_t::FM, lis3dh_reg_fifo_ctrl_t::FTH, get_register(), lis3dh_reg_ctrl3_t::I1_OVR, lis3dh_reg_ctrl3_t::I1_WTM, LIS3DH_BYPASS, LIS3DH_REG_CTRL3, LIS3DH_REG_CTRL5, LIS3DH_REG_FIFO_CTRL, lis3dh_reg_t::raw, set_register(), lis3dh_reg_fifo_ctrl_t::TR, and update_field.
Referenced by fifo_disable().
{
     lis3dh_reg_t reg;
     // Turn FIFO on/off
     update_field(reg, LIS3DH_REG_CTRL5, ctrl5, FIFO_EN, (mode !=LIS3DH_BYPASS));
     // Set FIFO CTRL
     get_register(&reg.raw, LIS3DH_REG_FIFO_CTRL);
     reg.fifo_ctrl.FM = mode;
     reg.fifo_ctrl.TR = tr;
     reg.fifo_ctrl.FTH = wtm;
     set_register(reg.raw, LIS3DH_REG_FIFO_CTRL);
     // Configure interrupts
     get_register(&reg.raw, LIS3DH_REG_CTRL3);
     reg.ctrl3.I1_WTM = wtm_int;
     reg.ctrl3.I1_OVR = ovr_int;
     set_register(reg.raw, LIS3DH_REG_CTRL3);
 }
fifo_disable()
void LIS3DH::fifo_disable (void)
Disable the FIFO mode.
Definition at line 207 of file lis3dh.cpp.
References fifo_enable(), and LIS3DH_BYPASS.
{
     fifo_enable(LIS3DH_BYPASS, 0x00, false, false);
 }
fifo_get_state()
lis3dh_reg_fifo_src_t LIS3DH::fifo_get_state (void)
Get the FIFO state.
Returns
FIFO source register value.
Definition at line 211 of file lis3dh.cpp.
References lis3dh_reg_t::fifo_src, get_register(), LIS3DH_REG_FIFO_SRC, and lis3dh_reg_t::raw.
Referenced by fifo_get_data().
{
     lis3dh_reg_t reg;
     // Get the source register
     get_register(&reg.raw, LIS3DH_REG_FIFO_SRC);
     // Return
     return reg.fifo_src;
 }
fifo_get_data()
lis3dh_reg_fifo_src_t LIS3DH::fifo_get_data (lis3dh_accel_t * data, uint8_t len)
Read bulk data from FIFO buffer.
Parameters
data Pointer to accel data array.
len Number of samples to retrieve.
Returns
FIFO source register value.
Definition at line 219 of file lis3dh.cpp.
References fifo_get_state(), get_accel(), and LIS3DH_FIFO_BUFF_LEN.
{
     // Check buffer
     if ((len == 0) || (data == NULL)) {
         return fifo_get_state();
     }
     // Check size
     len = (len > LIS3DH_FIFO_BUFF_LEN)? LIS3DH_FIFO_BUFF_LEN : len;
     // Retrieve data
     uint8_t idx = 0;
     while (idx++ < len) {
         get_accel(data++);
     }
     // Read and return FIFO state
     return fifo_get_state();
 }
int_polarity()
void LIS3DH::int_polarity (bool pol = false)
Set the interruption polarity.
Parameters
pol Polarity. On interrupt low(true), high(false).
Definition at line 236 of file lis3dh.cpp.
References LIS3DH_REG_CTRL6, and update_field.
{
     lis3dh_reg_t reg;
     update_field(reg, LIS3DH_REG_CTRL6, ctrl6, INT_POL, pol);
 }
int_set_parameters()
void LIS3DH::int_set_parameters (lis3dh_int_t signal, uint8_t ths, uint8_t dur, bool latch)
Set the interrupt general parameters on signal INT1 or INT2.
Parameters
signal Interrupt signal.
ths Interrupt threshold.
dur Interrupt duration.
latch Define if it's necessary to read the INTx source register to stop the interrupt.
Definition at line 241 of file lis3dh.cpp.
References LIS3DH_INT1, LIS3DH_REG_CTRL5, LIS3DH_REG_INT1_DUR, LIS3DH_REG_INT1_THS, LIS3DH_REG_INT2_DUR, LIS3DH_REG_INT2_THS, set_register(), and update_field.
{
     bool         is_int1 = (signal == LIS3DH_INT1);
     lis3dh_reg_t reg;
     // Configure
     update_field(reg, LIS3DH_REG_CTRL5, ctrl5, I1_LIR, latch);
     set_register((0x7F & ths), (is_int1)? LIS3DH_REG_INT1_THS  : LIS3DH_REG_INT2_THS);
     set_register((0x7F & dur), (is_int1)? LIS3DH_REG_INT1_DUR : LIS3DH_REG_INT2_DUR);
 }
int_data_enable()
void LIS3DH::int_data_enable (lis3dh_int_t signal, lis3dh_int_type_t type, bool enable)
Configure an interrupt on signal INT1 or INT2.
Parameters
signal Interrupt signal.
type Interrupt to be enabled/disabled.
enable Enable flag.
Definition at line 250 of file lis3dh.cpp.
References lis3dh_reg_t::ctrl3, lis3dh_reg_t::ctrl6, enable(), get_register(), lis3dh_reg_ctrl3_t::I1_CLICK, lis3dh_reg_ctrl3_t::I1_IA1, lis3dh_reg_ctrl3_t::I1_IA2, lis3dh_reg_ctrl3_t::I1_OVR, lis3dh_reg_ctrl3_t::I1_WTM, lis3dh_reg_ctrl3_t::I1_ZYXDA, lis3dh_reg_ctrl6_t::I2_ACT, lis3dh_reg_ctrl6_t::I2_BOOT, lis3dh_reg_ctrl6_t::I2_CLICK, lis3dh_reg_ctrl6_t::I2_IA1, lis3dh_reg_ctrl6_t::I2_IA2, LIS3DH_INT1, LIS3DH_INT1_DATA_READY, LIS3DH_INT1_FIFO_OVR, LIS3DH_INT1_FIFO_WTM, LIS3DH_INT2_ACT, LIS3DH_INT2_BOOT, LIS3DH_INT_CLICK, LIS3DH_INT_IA1, LIS3DH_INT_IA2, LIS3DH_REG_CTRL3, LIS3DH_REG_CTRL6, lis3dh_reg_t::raw, and set_register().
{
     bool         is_int1  = (signal == LIS3DH_INT1);
     lis3dh_reg_t reg;
     // Configure
     if (is_int1) {
         get_register(&reg.raw, LIS3DH_REG_CTRL3);
         switch(type) {
             case LIS3DH_INT_IA1:            reg.ctrl3.I1_IA1 = enable;      break;
             case LIS3DH_INT_IA2:            reg.ctrl3.I1_IA2 = enable;      break;
             case LIS3DH_INT_CLICK:          reg.ctrl3.I1_CLICK = enable;    break;
             case LIS3DH_INT1_DATA_READY:    reg.ctrl3.I1_ZYXDA = enable;    break;
             case LIS3DH_INT1_FIFO_WTM:      reg.ctrl3.I1_WTM = enable;      break;
             case LIS3DH_INT1_FIFO_OVR:      reg.ctrl3.I1_OVR = enable;      break;
             default: return;
         }
         set_register(reg.raw, LIS3DH_REG_CTRL3);
     } else {
         get_register(&reg.raw, LIS3DH_REG_CTRL6);
         switch(type) {
             case LIS3DH_INT_IA1:            reg.ctrl6.I2_IA1 = enable;      break;
             case LIS3DH_INT_IA2:            reg.ctrl6.I2_IA2 = enable;      break;
             case LIS3DH_INT_CLICK:          reg.ctrl6.I2_CLICK = enable;    break;
             case LIS3DH_INT2_BOOT:          reg.ctrl6.I2_BOOT = enable;     break;
             case LIS3DH_INT2_ACT:           reg.ctrl6.I2_ACT = enable;      break;
             default: return;
         }
         set_register(reg.raw, LIS3DH_REG_CTRL6);
     }
 }
get_int_data_src()
void LIS3DH::get_int_data_src (lis3dh_int_src_t * source)
Get the source of the interruption (FIFO or data ready) for signal INT1.
Parameters
source Pointer to interrupt source flags.
Definition at line 280 of file lis3dh.cpp.
References lis3dh_int_src_t::data_ready, get_register(), LIS3DH_REG_CTRL3, LIS3DH_REG_FIFO_SRC, and LIS3DH_REG_STAT.
{
     lis3dh_reg_ctrl3_t      ctrl3;
     lis3dh_reg_stat_t       stat;
     lis3dh_reg_fifo_src_t   fifo;
     // Get registers
     get_register((uint8_t*)&ctrl3, LIS3DH_REG_CTRL3);
     get_register((uint8_t*)&stat, LIS3DH_REG_STAT);
     get_register((uint8_t*)&fifo, LIS3DH_REG_FIFO_SRC);
     // Set values
     source->data_ready = stat.ZYXDA & ctrl3.I1_ZYXDA;
     source->data_ready = fifo.WTM & ctrl3.I1_WTM;
     source->data_ready = fifo.OVR & ctrl3.I1_OVR;
 }
int_data_disable()
void LIS3DH::int_data_disable (lis3dh_int_t signal)
Disable interrupts on signal INT1 or INT2.
Parameters
signal Interrupt signal.
Definition at line 294 of file lis3dh.cpp.
References lis3dh_reg_t::ctrl6, get_register(), lis3dh_reg_ctrl6_t::INT_POL, LIS3DH_DEF_CTRL3, LIS3DH_DEF_CTRL6, LIS3DH_INT1, LIS3DH_REG_CTRL3, LIS3DH_REG_CTRL6, lis3dh_reg_t::raw, and set_register().
{
     bool         is_int1  = (signal == LIS3DH_INT1);
     // Disable
     if (is_int1) {
         set_register(LIS3DH_DEF_CTRL3, LIS3DH_REG_CTRL3);
     } else {
         lis3dh_reg_t reg_old;
         lis3dh_reg_t reg_new;
         get_register(&reg_old.raw, LIS3DH_REG_CTRL6);
         reg_new.raw = LIS3DH_DEF_CTRL6;
         reg_new.ctrl6.INT_POL = reg_old.ctrl6.INT_POL;
         set_register(reg_new.raw, LIS3DH_REG_CTRL6);
     }
 }
int_event_enable()
void LIS3DH::int_event_enable (lis3dh_int_t signal, lis3dh_int_evt_t event, uint8_t axis_mask)
Set the configuration of an inertial event interrupt generator on signal INT1 or INT2. The interrupt occurs when the acceleration of the defined axis is lower than a defined threshold and one defined event occurs.
Parameters
signal Interrupt signal.
event Inertial event.
axis_mask The axis (LO or HI) selected to trigger the event. The mask is defined by the 6 lsb bits and starts from X_LOW.
Definition at line 309 of file lis3dh.cpp.
References lis3dh_int_evtcfg_t::cfg, LIS3DH_INT1, LIS3DH_REG_CTRL5, LIS3DH_REG_INT1_CFG, LIS3DH_REG_INT2_CFG, u16_u8_t::lsb, lis3dh_int_evtcfg_t::raw, set_register(), bk_u16_u8_t::u16, bk_u16_u8_t::u8, and update_field.
{
     bool         is_int1 = (signal == LIS3DH_INT1);
     lis3dh_reg_t reg;
     // Get the event configuration
     lis3dh_int_evtcfg_t evt_cfg;
     evt_cfg.raw.u16 = ((event << 6) | axis_mask);
     // Write the interrupt configuration
     set_register(evt_cfg.raw.u8.lsb, (is_int1)? LIS3DH_REG_INT1_CFG  : LIS3DH_REG_INT2_CFG);
     // Set D4D
     if (is_int1) {
         update_field(reg, LIS3DH_REG_CTRL5, ctrl5, I1_D4D, evt_cfg.cfg.D4D);
     } else {
         update_field(reg, LIS3DH_REG_CTRL5, ctrl5, I2_D4D, evt_cfg.cfg.D4D);
     }
 }
get_int_event_src()
void LIS3DH::get_int_event_src (lis3dh_int_t signal, lis3dh_reg_intx_src_t * source)
Get the source of the inertial event for signal INT1/INT2.
Parameters
signal Interrupt signal.
source Pointer to interrupt source register data.
Definition at line 325 of file lis3dh.cpp.
References get_register(), LIS3DH_INT1, LIS3DH_REG_INT1_SRC, and LIS3DH_REG_INT2_SRC.
{
     get_register((uint8_t*)source, (signal == LIS3DH_INT1)? LIS3DH_REG_INT1_SRC : LIS3DH_REG_INT2_SRC);
 }
int_event_disable()
void LIS3DH::int_event_disable (lis3dh_int_t signal)
Disable the configuration of an inertial event on signal INT1 or INT2.
Parameters
signal Interrupt signal.
Definition at line 329 of file lis3dh.cpp.
References LIS3DH_DEF_INT1_CFG, LIS3DH_DEF_INT2_CFG, LIS3DH_INT1, LIS3DH_REG_CTRL5, LIS3DH_REG_INT1_CFG, LIS3DH_REG_INT2_CFG, set_register(), and update_field.
{
     bool         is_int1  = (signal == LIS3DH_INT1);
     lis3dh_reg_t reg;
     // Set default configuration
     set_register(((is_int1)? LIS3DH_DEF_INT1_CFG : LIS3DH_DEF_INT2_CFG),
                  ((is_int1)? LIS3DH_REG_INT1_CFG : LIS3DH_REG_INT2_CFG));
     // Set default D4D
     if (is_int1) {
         update_field(reg, LIS3DH_REG_CTRL5, ctrl5, I1_D4D, 0);
     } else {
         update_field(reg, LIS3DH_REG_CTRL5, ctrl5, I2_D4D, 0);
     }
 }
click_enable()
void LIS3DH::click_enable (uint8_t axis_mask, bool sclick, bool dclick, uint8_t ths, uint8_t tlim, uint8_t tlat, uint8_t twin, bool latch)
Enable the click driven interruption with the given configuration.
Parameters
axis_mask The axis selected to trigger the click interruption event. The mask is defined by the 3 lsb bits and start from the X axis.
sclick Enable single click detection on mask.
dclick Enable double click detection on mask.
ths Click interrupt threshold.
tlim Click time limit. Maximum time that the signal can be over the threshold to be considered a click.
tlat Click time latency. Time that stops the detection after a click (avoid false-positives because bounce).
twin Click time window. Time after the latency in which a second click is expected to occur (begin of).
latch Define if it's necessary to read the click source register to stop the interrupt.
Definition at line 344 of file lis3dh.cpp.
References lis3dh_reg_t::click_cfg, lis3dh_reg_t::click_tht, get_register(), lis3dh_reg_click_tht_t::LIR_CLICK, LIS3DH_REG_CLICK_CFG, LIS3DH_REG_CLICK_THS, LIS3DH_REG_TIME_LAT, LIS3DH_REG_TIME_LIM, LIS3DH_REG_TIME_WIN, lis3dh_reg_t::raw, set_register(), lis3dh_reg_click_tht_t::THS, lis3dh_reg_click_cfg_t::X_D, lis3dh_reg_click_cfg_t::X_S, lis3dh_reg_click_cfg_t::Y_D, lis3dh_reg_click_cfg_t::Y_S, lis3dh_reg_click_cfg_t::Z_D, and lis3dh_reg_click_cfg_t::Z_S.
{
     lis3dh_reg_t reg;
     // Configure click source
     get_register(&reg.raw, LIS3DH_REG_CLICK_CFG);
     reg.click_cfg.X_S = (sclick && (0x01 & axis_mask));
     reg.click_cfg.X_D = (dclick && (0x01 & axis_mask));
     reg.click_cfg.Y_S = (sclick && (0x02 & axis_mask));
     reg.click_cfg.Y_D = (dclick && (0x02 & axis_mask));
     reg.click_cfg.Z_S = (sclick && (0x04 & axis_mask));
     reg.click_cfg.Z_D = (dclick && (0x04 & axis_mask));
     set_register(reg.raw, LIS3DH_REG_CLICK_CFG);
     // Set threshold and latch
     get_register(&reg.raw, LIS3DH_REG_CLICK_THS);
     reg.click_tht.LIR_CLICK = latch;
     reg.click_tht.THS = ths;
     set_register(reg.raw, LIS3DH_REG_CLICK_THS);
     // Set time parameters
     set_register(tlim, LIS3DH_REG_TIME_LIM);
     set_register(tlat, LIS3DH_REG_TIME_LAT);
     set_register(twin, LIS3DH_REG_TIME_WIN);
 }
click_disable()
void LIS3DH::click_disable (void)
Disable the click driven interruption.
Definition at line 367 of file lis3dh.cpp.
References LIS3DH_DEF_CLICK_CFG, LIS3DH_DEF_CLICK_THS, LIS3DH_DEF_TIME_LAT, LIS3DH_DEF_TIME_LIM, LIS3DH_DEF_TIME_WIN, LIS3DH_REG_CLICK_CFG, LIS3DH_REG_CLICK_THS, LIS3DH_REG_TIME_LAT, LIS3DH_REG_TIME_LIM, LIS3DH_REG_TIME_WIN, and set_register().
{
     // Set click registers as default
     set_register(LIS3DH_DEF_CLICK_CFG, LIS3DH_REG_CLICK_CFG);
     set_register(LIS3DH_DEF_CLICK_THS, LIS3DH_REG_CLICK_THS);
     set_register(LIS3DH_DEF_TIME_LIM, LIS3DH_REG_TIME_LIM);
     set_register(LIS3DH_DEF_TIME_LAT, LIS3DH_REG_TIME_LAT);
     set_register(LIS3DH_DEF_TIME_WIN, LIS3DH_REG_TIME_WIN);
 }
get_click_src()
void LIS3DH::get_click_src (lis3dh_reg_click_src_t * source)
Read the click source register.
Parameters
source Pointer to click source register data.
Definition at line 376 of file lis3dh.cpp.
References get_register(), and LIS3DH_REG_CLICK_SRC.
{
     get_register((uint8_t*)source, LIS3DH_REG_CLICK_SRC);
 }
activity_enable()
void LIS3DH::activity_enable (uint8_t ths, uint8_t dur)
Enable the activity dependent power mode.
Parameters
ths Sleep-Awake, Return-to-Sleep activation threshold.
dur Sleep-Awake, Return-to-Sleep duration.
Definition at line 402 of file lis3dh.cpp.
References LIS3DH_REG_ACT_DUR, LIS3DH_REG_ACT_THS, and set_register().
Referenced by activity_disable().
{
     set_register((0x7F & ths), LIS3DH_REG_ACT_THS);
     set_register((0x7F & dur), LIS3DH_REG_ACT_DUR);
 }
activity_disable()
void LIS3DH::activity_disable (void)
Disable the activity dependent power mode.
Definition at line 407 of file lis3dh.cpp.
References activity_enable(), LIS3DH_DEF_ACT_DUR, and LIS3DH_DEF_ACT_THS.
{
     activity_enable(LIS3DH_DEF_ACT_THS, LIS3DH_DEF_ACT_DUR);
 }
hpf_configure()
void LIS3DH::hpf_configure (lis3dh_hpm_t mode, lis3dh_hpcf_t cf, bool fds, bool click, bool ia1, bool ia2)
Configure the high-pass filter.
Parameters
mode High-pass filter mode.
cf High-pass filter cut frequency.
fds Filtered data selection: Internal filter bypassed(false), internal filter(true).
click Filter enabled for click.
ia1 Filter enabled for event on INT1.
ia2 Filter enabled for event on INT2.
Definition at line 381 of file lis3dh.cpp.
References lis3dh_reg_t::ctrl2, get_register(), lis3dh_reg_ctrl2_t::HP_IA1, lis3dh_reg_ctrl2_t::HP_IA2, lis3dh_reg_ctrl2_t::HPCF, lis3dh_reg_ctrl2_t::HPCLICK, lis3dh_reg_ctrl2_t::HPM, LIS3DH_REG_CTRL2, lis3dh_reg_t::raw, and set_register().
{
     lis3dh_reg_t reg;
     // Configure
     get_register(&reg.raw, LIS3DH_REG_CTRL2);
     reg.ctrl2.HPM = mode;
     reg.ctrl2.HPCF = cf;
     reg.ctrl2.HPCLICK = click;
     reg.ctrl2.HP_IA1 = ia1;
     reg.ctrl2.HP_IA2 = ia2;
     set_register(reg.raw, LIS3DH_REG_CTRL2);
 }
hpd_reset()
void LIS3DH::hpd_reset (void)
Reset to default the filter configurations.
Definition at line 393 of file lis3dh.cpp.
References LIS3DH_DEF_CTRL2, LIS3DH_REG_CTRL2, and set_register().
{
     set_register(LIS3DH_DEF_CTRL2, LIS3DH_REG_CTRL2);
 }
get_reference()
void LIS3DH::get_reference (uint8_t * source)
Get the reference source register.
Parameters
source Pointer to reference source register data.
Definition at line 397 of file lis3dh.cpp.
References get_register(), and LIS3DH_REG_REF.
{
     get_register(source, LIS3DH_REG_REF);
 }
get_accel_conversion()
uint8_t LIS3DH::get_accel_conversion (void) private
Get the compensation value needed to adjust the accelerometer values in dependence with the resolution and power mode of the device.
Returns
Accelerometer conversion value (digit to [mg]).
Definition at line 412 of file lis3dh.cpp.
References _config, LIS3DH_LOWPOWER, LIS3DH_NORMAL, LIS3DH_SCALE_16G, LIS3DH_SCALE_4G, LIS3DH_SCALE_8G, lis3dh_t::resolution, and lis3dh_t::scale.
Referenced by enable(), set_mode(), and set_scale().
{
     uint8_t scale;
     switch(_config.resolution) {
         case LIS3DH_LOWPOWER:   scale = 4; break;   //  8bit mode: raw * 16;
         case LIS3DH_NORMAL:     scale = 2; break;   // 10bit mode: raw * 4;
         default:                scale = 0; break;   // 12bit mode: raw * 1;
     }
     switch(_config.scale) {
         case LIS3DH_SCALE_4G:   scale += 1; break;  //  4G scale: 2G * 2;
         case LIS3DH_SCALE_8G:   scale += 2; break;  //  8G scale: 2G * 4;
         case LIS3DH_SCALE_16G:  scale += 3; break;  // 16G scale: 2G * 8;
         default:                scale += 0; break;  //  2G scale;
     }
     return scale;
 }
set_register()
void LIS3DH::set_register (uint8_t src, uint8_t reg) private
Write "src" to "reg" register.
Parameters
src Source byte.
reg Device register address.
Definition at line 429 of file lis3dh.cpp.
References _is_spi, SPI::Device::begin_transaction(), SPI::Device::end_transaction(), LIS3DH_SPI_W, SPI::Device::write_reg(), and TWI::Device::write_reg().
Referenced by activity_enable(), adc_enable(), click_disable(), click_enable(), fifo_enable(), hpd_reset(), hpf_configure(), int_data_disable(), int_data_enable(), int_event_disable(), int_event_enable(), int_set_parameters(), set_defaults(), and set_mode().
{
     // Write register
     if (_is_spi) {
         // Turn on write mode
         reg |= LIS3DH_SPI_W;
         // Write SPI
         SPI::Device::begin_transaction();
         SPI::Device::write_reg(reg, src);
         SPI::Device::end_transaction();
     } else {
         // Write I2C
         TWI::Device::write_reg(reg, src, true);
     }
 }
get_register()
void LIS3DH::get_register (uint8_t * rec, uint8_t reg) private
LIS3DH::get_register(uint8_t*, uint8_t, uint8_t) handler to get a single byte.
Parameters
rec Receiver byte.
reg Device register address.
Definition at line 444 of file lis3dh.cpp.
References get_registers().
Referenced by adc_enable(), click_enable(), fifo_enable(), fifo_get_state(), get_adc(), get_click_src(), get_int_data_src(), get_int_event_src(), get_reference(), hpf_configure(), int_data_disable(), int_data_enable(), is_available(), is_data_available(), and set_mode().
{
     get_registers(rec, reg, 1);
 }
get_registers()
void LIS3DH::get_registers (uint8_t * rec, uint8_t reg, uint8_t len) private
read a "len" number of registers on "rec" starting from "reg" register.
Parameters
rec Pointer to received byte array.
reg Device register address.
len Number of bytes to read.
Definition at line 448 of file lis3dh.cpp.
References _is_spi, SPI::Device::begin_transaction(), SPI::Device::end_transaction(), LIS3DH_SPI_INC, LIS3DH_SPI_R, LIS3DH_TWI_INC, TWI::Device::read_reg(), and SPI::Device::write_reg().
Referenced by get_accel(), get_adc(), and get_register().
{
     // Read registers
     if (_is_spi) {
         // Turn auto-increment on and read mode
         reg |= (LIS3DH_SPI_INC | LIS3DH_SPI_R);
         // Read SPI
         SPI::Device::begin_transaction();
         SPI::Device::write_reg(reg, rec, len);
         SPI::Device::end_transaction();
     } else {
         // Turn auto-increment on (bit 7)
         reg |= (len > 1)? LIS3DH_TWI_INC : 0x00;
         // Read I2C
         TWI::Device::read_reg(reg, rec, len, true);
     }
 }
configure()
void SPI::Device::configure (uint32_t freq, spi_tx_mode_t tx_mode, spi_ds_mode_t bit_order) inherited
Set the configuration required to communicate with the device.
Parameters
freq SPI SCLK frequency.
tx_mode SPI transmission mode spi_tx_mode_t.
bit_order SPI data transmission mode spi_ds_mode_t.
Definition at line 205 of file spi.cpp.
References SPI::Device::_dev_conf, SPI::Device::_dev_spi, and SPI::get_config().
Referenced by LIS3DH().
{
     _dev_spi->get_config(&_dev_conf, freq, tx_mode, bit_order);
 }
begin_transaction()
void SPI::Device::begin_transaction (void) inherited
Activate the device changing the state of the SS pin.
Definition at line 209 of file spi.cpp.
References SPI::Device::_dev_conf, SPI::Device::_dev_on, SPI::Device::_dev_spi, SPI::Device::_dev_ss, pin_write(), and SPI::start().
Referenced by get_registers(), and set_register().
{
     _dev_spi->start(&_dev_conf);
     pin_write(_dev_ss, _dev_on);
 }
end_transaction()
void SPI::Device::end_transaction (void) inherited
Deactivate the device changing the state of the SS pin.
Definition at line 214 of file spi.cpp.
References SPI::Device::_dev_on, SPI::Device::_dev_ss, and pin_write().
Referenced by get_registers(), and set_register().
{
     pin_write(_dev_ss, !_dev_on);
 }
transfer() [1/2]
uint8_t SPI::Device::transfer (uint8_t data) inherited
The master send a single byte to the slave and returns it's response.
Parameters
data Byte to send.
Returns
Slave response byte.
Definition at line 218 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::transfer().
{
     return _dev_spi->transfer(data);
 }
transfer() [2/2]
void SPI::Device::transfer (uint8_t * src, uint8_t * rec, size_t size, uint8_t off = 0, uint16_t dly = 0) inherited
Perform a data transfer between the SPI master and the slave. Send "size" bytes from "src" and save the responses on "rec". The method allow to start saving the responses after "offset" bytes sent (the master will send "offset" dummy bytes after "src" is transmitted to get the full response) and add delay after each transfer.
Parameters
src Pointer to source byte array.
rec Pointer to received byte array.
size Bytes to be transfered.
off Offset (in bytes).
dly Time to wait between transfers (in [us]).
Definition at line 222 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::transfer().
{
     _dev_spi->transfer(src, rec, size, off, dly);
 }
write() [1/4]
void SPI::Device::write (uint8_t src, uint16_t dly = 0) inherited
write(uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
Parameters
src Source byte.
dly Time to wait after write (in [us]).
Definition at line 226 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::write().
{
     _dev_spi->write(src, dly);
 }
write() [2/4]
void SPI::Device::write (uint8_t * src, size_t size, uint16_t dly = 0) inherited
Write "size" bytes from "src" to the slave.
Parameters
src Pointer to source byte array.
size Bytes to be transmitted.
dly Time to wait between writes (in [us]).
Definition at line 230 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::write().
{
     _dev_spi->write(src, size, dly);
 }
write_reg() [1/4]
void SPI::Device::write_reg (uint8_t reg, uint8_t src, uint16_t dly = 0) inherited
brief write_reg(uint8_t, uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
Parameters
reg Slave register address.
src Source byte.
dly Time to wait after write (in [us]).
Definition at line 234 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::write_reg().
Referenced by get_registers(), and set_register().
{
     _dev_spi->write_reg(reg, src, dly);
 }
write_reg() [2/4]
void SPI::Device::write_reg (uint8_t reg, uint8_t * src, size_t size, uint16_t dly = 0) inherited
Handler of spi_master_write() to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave.
Parameters
reg Slave register address.
src Pointer to source byte array.
size Bytes to be transmitted.
dly Time to wait between writes (in [us]).
Definition at line 238 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::write_reg().
{
     _dev_spi->write_reg(reg, src, size, dly);
 }
read() [1/3]
void SPI::Device::read (uint8_t * rec, size_t size, uint16_t dly = 0) inherited
Read "size" bytes from the slave to "rec".
Parameters
rec Pointer to received byte array.
size Bytes to be read.
dly Time to wait between reads (in [us]).
Definition at line 242 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::read().
{
     _dev_spi->read(rec, size, dly);
 }
read_reg() [1/4]
void SPI::Device::read_reg (uint8_t reg, uint8_t * rec, uint16_t dly = 0) inherited
brief read_reg(uint8_t, uint8_t*, uint8_t, uint16_t) handler for 1 byte "rec".
Parameters
reg Slave register address.
rec Receive byte.
dly Time to wait after write (in [us]).
Definition at line 246 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::read_reg().
{
     _dev_spi->read_reg(reg, rec, dly);
 }
read_reg() [2/4]
void SPI::Device::read_reg (uint8_t reg, uint8_t * rec, size_t size, uint16_t dly = 0) inherited
Handler of spi_master_read() to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave and copy them to "rec".
Parameters
reg Slave register address.
rec Pointer to received byte array.
size Bytes to be read.
dly Time to wait between reads (in [us]).
Definition at line 250 of file spi.cpp.
References SPI::Device::_dev_spi, and SPI::read_reg().
{
     _dev_spi->read_reg(reg, rec, size, dly);
 }
write() [3/4]
uint16_t TWI::Device::write (uint8_t src, bool stop = true) inherited
TWI::write(uint8_t, uint8_t, bool) with the slave address fixed.
Definition at line 192 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write().
{
     return _dev_twi->write(_dev_addr, src, stop);
 }
write() [4/4]
uint16_t TWI::Device::write (uint8_t * src, size_t size, bool stop = true) inherited
TWI::write(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 196 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write().
{
     return _dev_twi->write(_dev_addr, src, size, stop);
 }
write_reg() [3/4]
uint16_t TWI::Device::write_reg (uint8_t reg, uint8_t src, bool stop = true) inherited
TWI::write_reg(uint8_t, uint8_t, uint8_t, bool) with the slave address fixed.
Definition at line 200 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write_reg().
Referenced by DRV2605::set_register(), and set_register().
{
     return _dev_twi->write_reg(_dev_addr, reg, src, stop);
 }
write_reg() [4/4]
uint16_t TWI::Device::write_reg (uint8_t reg, uint8_t * src, size_t size, bool stop = true) inherited
TWI::write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 204 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write_reg().
{
     return _dev_twi->write_reg(_dev_addr, reg, src, size, stop);
 }
read() [2/3]
uint16_t TWI::Device::read (uint8_t * rec, bool stop) inherited
TWI::read(uint8_t, uint8_t*, bool) with the slave address fixed.
Definition at line 208 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read().
{
     return _dev_twi->read(_dev_addr, rec, stop);
 }
read() [3/3]
uint16_t TWI::Device::read (uint8_t * rec, size_t size, bool stop = true) inherited
TWI::read(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 212 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read().
{
     return _dev_twi->read(_dev_addr, rec, size, stop);
 }
read_reg() [3/4]
uint16_t TWI::Device::read_reg (uint8_t reg, uint8_t * rec, bool stop = true) inherited
TWI::read_reg(uint8_t, uint8_t, uint8_t*, bool) with the slave address fixed.
Definition at line 216 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read_reg().
Referenced by DRV2605::get_registers(), and get_registers().
{
     return _dev_twi->read_reg(_dev_addr, reg, rec, stop);
 }
read_reg() [4/4]
uint16_t TWI::Device::read_reg (uint8_t reg, uint8_t * rec, size_t size, bool stop = true) inherited
TWI::read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 220 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read_reg().
{
     return _dev_twi->read_reg(_dev_addr, reg, rec, size, stop);
 }
Member Data Documentation
_is_spi
bool LIS3DH::_is_spi private
TWI/SPI selector.
Definition at line 274 of file lis3dh.h.
Referenced by get_registers(), and set_register().
_config
lis3dh_t LIS3DH::_config private
Sensor configuration.
Definition at line 275 of file lis3dh.h.
Referenced by enable(), get_accel(), get_accel_conversion(), get_resolution(), get_scale(), is_data_available(), set_mode(), and set_scale().
_dev_spi
SPI* SPI::Device::_dev_spi protected inherited
SPI manager.
Definition at line 223 of file spi.h.
Referenced by SPI::Device::begin_transaction(), SPI::Device::configure(), SPI::Device::Device(), SPI::Device::read(), SPI::Device::read_reg(), SPI::Device::transfer(), SPI::Device::write(), and SPI::Device::write_reg().
_dev_conf
spi_conf_t SPI::Device::_dev_conf protected inherited
SPI settings.
Definition at line 224 of file spi.h.
Referenced by SPI::Device::begin_transaction(), SPI::Device::configure(), and SPI::Device::Device().
_dev_ss
pins_t SPI::Device::_dev_ss protected inherited
Device SS.
Definition at line 225 of file spi.h.
Referenced by SPI::Device::begin_transaction(), and SPI::Device::end_transaction().
_dev_on
bool SPI::Device::_dev_on protected inherited
Device on SS status.
Definition at line 226 of file spi.h.
Referenced by SPI::Device::begin_transaction(), SPI::Device::Device(), and SPI::Device::end_transaction().
_dev_twi
TWI* TWI::Device::_dev_twi protected inherited
TWI manager.
Definition at line 246 of file twi.h.
Referenced by TWI::Device::read(), TWI::Device::read_reg(), TWI::Device::write(), and TWI::Device::write_reg().
_dev_addr
uint8_t TWI::Device::_dev_addr protected inherited
Device address.
Definition at line 247 of file twi.h.
Referenced by TWI::Device::read(), TWI::Device::read_reg(), TWI::Device::write(), and TWI::Device::write_reg().
The documentation for this class was generated from the following files:
device/lis3dh.h
device/lis3dh.cpp