AVRLibs: UART Class Reference
UART Class Reference
UART bus general implementation.
#include <uart.h>
Public Member Functions
void enable (uint32_t baudrate)
Enable UART and set baudrate.
void enable (uint32_t baudrate, uart_msgbit_t msgbit, uart_stbit_t stbit, uart_pmode_t pmode)
General implementation for enable UART.
void disable (void)
Finishes the transmission and disable the UART.
int16_t rx_available (void)
Return the number of bytes waiting to be read.
int16_t peek (void)
Peek the next byte available on the RX buffer.
int16_t read (void)
Get a single byte from the RX buffer.
uint8_t tx_available (void)
Return the number of bytes available to be written in the Tx buffer.
void flush (void)
Flush the remaining bytes of the TX buffer.
size_t write (uint8_t byte)
Flush the remaining bytes of the TX buffer.
void _rx_callback (void)
This callback is used to handle the reception of data packets.
void _tx_callback (void)
This callback is used to handle the transmission of data packets.
size_t write (const char *cstr)
Send a bunch of characters from a given buffer.
size_t write (const char *cstr, size_t size)
Send a bunch of characters from a given buffer.
size_t write (const uint8_t *buff, size_t size)
Send a bunch of bytes from a given buffer.
size_t print (char c)
size_t print (const char *cstr)
size_t print (const String &str)
size_t print (const FlashString *pstr)
size_t print (uint32_t num, num_base_t base=NUM_BASE_DEC)
size_t print (uint16_t num, num_base_t base=NUM_BASE_DEC)
size_t print (uint8_t num, num_base_t base=NUM_BASE_DEC)
size_t print (int32_t num, num_base_t base=NUM_BASE_DEC)
size_t print (int16_t num, num_base_t base=NUM_BASE_DEC)
size_t print (int8_t num, num_base_t base=NUM_BASE_DEC)
size_t print (double num, uint8_t p=3)
void set_timeout (uint32_t timeout)
Sets the timeout used to get bytes from the input stream.
uint32_t get_timeout (void)
Get the actual timeout.
int32_t parse_int (char ignore='\x01', stream_look_mode_t skip_mode=SKIP_ALL)
Parse a signed integer number from the input stream.
double parse_double (char ignore='\x01', stream_look_mode_t skip_mode=SKIP_ALL)
Parse a signed double number from the input stream.
size_t read_bytes (uint8_t *buff, size_t size)
Read a 'size' number of bytes from the input stream. It stops when the buffer is full or the timeout is reached.
size_t read_bytes (char *cstr, size_t size)
Variant of Stream::read_bytes(uint8_t*, size_t) for characters.
String read_string (void)
Read a string from the input stream until any more bytes are available.
size_t read_bytes_until (char terminator, uint8_t *buff, size_t size)
Similar to Stream::read_bytes(uint8_t*, size_t) but this method also stops when the terminator character is detected.
size_t read_bytes_until (char terminator, char *cstr, size_t size)
Variant of Stream::read_bytes_until(char, uint8_t*, size_t) for characters.
String read_string_until (char terminator='\n')
Read a string from the input stream until any more bytes are available or the terminator character is reached.
bool ignore_bytes_until (char terminator)
Ignore the input stream until a terminator is detected.
Static Public Member Functions
static UART * get_instance (uart_inst_t uart)
Get an instance for an specific device.
static void delete_instance (uart_inst_t uart)
Deletes the instance of an specific device. Note that this action will turn off the interface and delete all the configurations.
Protected Member Functions
UART (volatile uint8_t *ctrl, volatile uint16_t *baud, volatile uint8_t *data)
UART constructor.
size_t print_uint (uint32_t num, num_base_t base)
Converts a unsigned integer into a string and writes the characters on the TX buffer.
size_t print_int (int32_t num, num_base_t base)
Extends Stream::print_uint(uint32_t, num_base_t) for signed integers.
size_t print_double (double num, uint8_t p)
Converts a double into a string and writes the characters on the TX buffer.
int16_t timed_peek (void)
Peeks the input stream using a timeout.
int16_t timed_read (void)
Reads the input stream using a timeout.
int16_t peek_next_digit (stream_look_mode_t look_mode, bool is_decimal)
Peek the input stream with a timeout. It search if the peeked byte is part of a digit.
Protected Attributes
volatile uart_ctrl_t * _ctrl
UART control registers.
volatile uint16_t * _baud
UART baudrate register.
volatile uint8_t * _data
UART data register.
volatile bool _used
Flag that indicates if the bus was used.
volatile uint8_t _rx_buff [UART_BUFF_SIZE]
RX buffer.
volatile uint8_t _rx_buff_head
RX buffer head index.
volatile uint8_t _rx_buff_tail
RX buffer tail index.
volatile uint8_t _tx_buff [UART_BUFF_SIZE]
TX buffer.
volatile uint8_t _tx_buff_head
TX buffer head index.
volatile uint8_t _tx_buff_tail
TX buffer tail index.
uint32_t _rx_time_start
Timeout measurement start.
uint32_t _rx_timeout
Timeout for "reading" functions.
Detailed Description
UART bus general implementation.
Definition at line 26 of file uart.h.
Constructor & Destructor Documentation
UART()
UART::UART (volatile uint8_t * ctrl, volatile uint16_t * baud, volatile uint8_t * data) inline protected
UART constructor.
Parameters
ctrl UART control registers initial address.
baud UART baudrate register address.
data UART data register address.
Member Function Documentation
get_instance()
static UART* UART::get_instance (uart_inst_t uart) static
Get an instance for an specific device.
Parameters
uart UART device.
Returns
Device singleton.
delete_instance()
static void UART::delete_instance (uart_inst_t uart) static
Deletes the instance of an specific device. Note that this action will turn off the interface and delete all the configurations.
Parameters
uart UART device.
enable() [1/2]
void UART::enable (uint32_t baudrate)
Enable UART and set baudrate.
Parameters
baudrate Specify the baudrate.
enable() [2/2]
void UART::enable (uint32_t baudrate, uart_msgbit_t msgbit, uart_stbit_t stbit, uart_pmode_t pmode)
General implementation for enable UART.
Parameters
baudrate Specify the baudrate.
msgbit Data packet size.
stbit Stop bits.
pmode Parity mode.
disable()
void UART::disable (void)
Finishes the transmission and disable the UART.
rx_available()
int16_t UART::rx_available (void) virtual
Return the number of bytes waiting to be read.
Returns
bytes waiting in the RX buffer.
Implements Stream.
peek()
int16_t UART::peek (void) virtual
Peek the next byte available on the RX buffer.
Returns
Next byte available on the RX buffer.
Implements Stream.
read()
int16_t UART::read (void) virtual
Get a single byte from the RX buffer.
Returns
Next byte available on the RX buffer.
Note
After the byte is retrieved the buffer index will be incremented giving space for more bytes to be read.
Implements Stream.
tx_available()
uint8_t UART::tx_available (void) virtual
Return the number of bytes available to be written in the Tx buffer.
Returns
bytes available to write on the TX buffer.
Implements Stream.
flush()
void UART::flush (void) virtual
Flush the remaining bytes of the TX buffer.
Implements Stream.
write() [1/4]
size_t UART::write (uint8_t byte) virtual
Flush the remaining bytes of the TX buffer.
Implements Stream.
_rx_callback()
void UART::_rx_callback (void) inline
This callback is used to handle the reception of data packets.
_tx_callback()
void UART::_tx_callback (void) inline
This callback is used to handle the transmission of data packets.
write() [2/4]
size_t Stream::write (const char * cstr) inherited
Send a bunch of characters from a given buffer.
Parameters
cstr Pointer to character array (string).
Returns
Number of bytes sent.
Definition at line 14 of file stream.cpp.
References Stream::write().
{
     return write(cstr, strlen(cstr));
 }
write() [3/4]
size_t Stream::write (const char * cstr, size_t size) inherited
Send a bunch of characters from a given buffer.
Parameters
cstr Pointer to character array.
size Number of bytes to be sent.
Returns
Number of bytes sent.
Definition at line 18 of file stream.cpp.
References Stream::write().
{
     return write((const uint8_t*) cstr, size);
 }
write() [4/4]
size_t Stream::write (const uint8_t * buff, size_t size) inherited
Send a bunch of bytes from a given buffer.
Parameters
buff Pointer to byte array.
size Number of bytes to be sent.
Returns
Number of bytes sent.
Definition at line 22 of file stream.cpp.
References Stream::write().
{
     // Check if the buffer is available
     if ((buff == NULL) || (size == 0)) return 0;
     // If it is, send the bytes
     size_t txnum = 0;
     while (size--) {
         if (write(*buff++)) txnum++;
         else break;
     }
     return txnum;
 }
print() [1/11]
size_t Stream::print (char c) inherited
Definition at line 95 of file stream.cpp.
References Stream::write().
Referenced by Stream::print_double().
{
     return write((uint8_t) c);
 }
print() [2/11]
size_t Stream::print (const char * cstr) inherited
Definition at line 99 of file stream.cpp.
References Stream::write().
{
     return write(cstr);
 }
print() [3/11]
size_t Stream::print (const String & str) inherited
Definition at line 103 of file stream.cpp.
References String::begin(), String::get_length(), and Stream::write().
{
     return write(str.begin(), str.get_length());
 }
print() [4/11]
size_t Stream::print (const FlashString * pstr) inherited
Definition at line 107 of file stream.cpp.
References Stream::write().
{
     PGM_P str = reinterpret_cast<PGM_P>(pstr);
     size_t len = 0;
     while (true) {
         uint8_t c = pgm_read_byte(str++);
         if (c == 0) break;
         if (write(c)) len++;
         else break;
     }
     return len;
 }
print() [5/11]
size_t Stream::print (uint32_t num, num_base_t base = NUM_BASE_DEC) inherited
Definition at line 119 of file stream.cpp.
References Stream::print_uint().
{
     return print_uint(num, base);
 }
print() [6/11]
size_t Stream::print (uint16_t num, num_base_t base = NUM_BASE_DEC) inherited
Definition at line 123 of file stream.cpp.
References Stream::print_uint().
{
     return print_uint((uint32_t) num, base);
 }
print() [7/11]
size_t Stream::print (uint8_t num, num_base_t base = NUM_BASE_DEC) inherited
Definition at line 127 of file stream.cpp.
References Stream::print_uint().
{
     return print_uint((uint32_t) num, base);
 }
print() [8/11]
size_t Stream::print (int32_t num, num_base_t base = NUM_BASE_DEC) inherited
Definition at line 131 of file stream.cpp.
References Stream::print_int().
{
     return print_int(num, base);
 }
print() [9/11]
size_t Stream::print (int16_t num, num_base_t base = NUM_BASE_DEC) inherited
Definition at line 135 of file stream.cpp.
References Stream::print_int().
{
     return print_int((int32_t) num, base);
 }
print() [10/11]
size_t Stream::print (int8_t num, num_base_t base = NUM_BASE_DEC) inherited
Definition at line 139 of file stream.cpp.
References Stream::print_int().
{
     return print_int((int32_t) num, base);
 }
print() [11/11]
size_t Stream::print (double num, uint8_t p = 3) inherited
Definition at line 143 of file stream.cpp.
References Stream::print_double().
{
     return print_double(num, p);
 }
set_timeout()
void Stream::set_timeout (uint32_t timeout) inherited
Sets the timeout used to get bytes from the input stream.
Parameters
timeout Time for byte timeout in [ms].
Definition at line 148 of file stream.cpp.
References Stream::_rx_timeout.
{
     _rx_timeout = timeout;
 }
get_timeout()
uint32_t Stream::get_timeout (void) inherited
Get the actual timeout.
Returns
Stream reading timeout in [ms].
Definition at line 152 of file stream.cpp.
References Stream::_rx_timeout.
{
     return _rx_timeout;
 }
parse_int()
int32_t Stream::parse_int (char ignore = '\x01', stream_look_mode_t skip_mode = SKIP_ALL) inherited
Parse a signed integer number from the input stream.
Parameters
ignore Characters to be ignored on the number search.
skip_mode Look ahead modes. Checkout stream_look_mode_t for more info.
Returns
Integer number.
Definition at line 224 of file stream.cpp.
References Stream::peek_next_digit(), Stream::read(), and Stream::timed_peek().
{
     int16_t byte;
     int32_t value = 0;
     bool    is_negative = false;
     // Get the first byte (ignore non numeric bytes)
     byte = peek_next_digit(look_mode, false);
     // If there's an error or timeout the value is returned as 0
     if (byte < 0) return 0;
     // Process the input
     do {
         // Handle the byte
         if (byte == ignore)
             ;
         else if (byte == '-')
             is_negative = true;
         else if ((byte >= '0') && (byte <= '9'))
             value = (10 * value) + (byte - '0');
         // Consume the byte and peek the next one
         read();
         byte = timed_peek();
     } while (                                       // continue if..
             ((byte >= '0') && (byte <= '9'))    ||  // The input is a number
             (byte == ignore)                        // The input will be ignored
             );
     // Apply the sign and return
     if (is_negative)
         value = -value;
     return value;
 }
parse_double()
double Stream::parse_double (char ignore = '\x01', stream_look_mode_t skip_mode = SKIP_ALL) inherited
Parse a signed double number from the input stream.
Parameters
ignore Characters to be ignored on the number search.
skip_mode Look ahead modes. Checkout stream_look_mode_t for more info.
Returns
Double number.
Definition at line 260 of file stream.cpp.
References Stream::peek_next_digit(), Stream::read(), and Stream::timed_peek().
{
     int16_t byte;
     int32_t value = 0;
     double  fraction = 1.0;
     bool    is_fraction = false;
     bool    is_negative = false;
     // Get the first byte (ignore non numeric bytes)
     byte = peek_next_digit(look_mode, true);
     // If there's an error or timeout the value is returned as 0
     if (byte < 0) return 0;
     // Process the input
     do {
         // Handle the byte
         if (byte == ignore)
             ;
         else if (byte == '-')
             is_negative = true;
         else if (byte == '.')
             is_fraction = true;
         else if ((byte >= '0') && (byte <= '9')) {
             value = (10 * value) + (byte - '0');
             fraction *= 0.1;
         }
         // Consume the byte and peek the next one
         read();
         byte = timed_peek();
     } while (                                       // Continue if..
             ((byte >= '0') && (byte <= '9'))    ||  // The input is a number
             (!is_fraction && (byte == '.'))     ||  // The input is a decimal point (only once)
             (byte == ignore)                        // The input is the character to be ignored
             );
     // Apply the sign
     if (is_negative)
         value = -value;
     // Apply the fractionary part
     if (is_fraction)
         return fraction * value;
     return value;
 }
read_bytes() [1/2]
size_t Stream::read_bytes (uint8_t * buff, size_t size) inherited
Read a 'size' number of bytes from the input stream. It stops when the buffer is full or the timeout is reached.
Parameters
buff Pointer to a byte array.
size Number of bytes to be read.
Returns
Number of bytes actually read.
Definition at line 305 of file stream.cpp.
References Stream::timed_read().
Referenced by Stream::read_bytes().
{
     int16_t byte;
     size_t  bytes_read = 0;
     // Check size
     if (size == 0) return 0;
     // Get bytes if there's any error and the buffer has space left
     byte = timed_read();
     while ((bytes_read < size) && (byte >= 0)) {
         *buff++ = (uint8_t) byte;
         bytes_read++;
         byte = timed_read();
     }
     // Return the number of bytes read
     return bytes_read;
 }
read_bytes() [2/2]
size_t Stream::read_bytes (char * cstr, size_t size) inherited
Variant of Stream::read_bytes(uint8_t*, size_t) for characters.
Parameters
cstr Pointer to a character array.
size Number of characters to read.
Returns
Number of characters actually read.
Definition at line 324 of file stream.cpp.
References Stream::read_bytes().
{
     return read_bytes((uint8_t*)cstr, size);
 }
read_string()
String Stream::read_string (void) inherited
Read a string from the input stream until any more bytes are available.
Returns
Input stream string.
Definition at line 328 of file stream.cpp.
References Stream::timed_read().
{
     int16_t byte;
     String  str;
     // Get bytes if there's any error
     byte = timed_read();
     while (byte >= 0) {
         str += (char) byte;
         byte = timed_read();
     }
     // Return a string
     return str;
 }
read_bytes_until() [1/2]
size_t Stream::read_bytes_until (char terminator, uint8_t * buff, size_t size) inherited
Similar to Stream::read_bytes(uint8_t*, size_t) but this method also stops when the terminator character is detected.
Parameters
terminator Character used to terminate the reading.
buff Pointer to a byte array.
size Number of bytes to be read.
Returns
Number of bytes actually read.
Definition at line 344 of file stream.cpp.
References Stream::timed_read().
Referenced by Stream::read_bytes_until().
{
     int16_t byte;
     size_t  bytes_read = 0;
     // Check size
     if (size == 0) return 0;
     // Get bytes while there's any error, the buffer has space available
     // And the incoming byte is different to the terminator
     byte = timed_read();
     while ((bytes_read < size) && (byte >= 0) && (byte != terminator)) {
         *buff++ = (uint8_t) byte;
         bytes_read++;
         byte = timed_read();
     }
     // Return the number of bytes read
     return bytes_read;
 }
read_bytes_until() [2/2]
size_t Stream::read_bytes_until (char terminator, char * cstr, size_t size) inherited
Variant of Stream::read_bytes_until(char, uint8_t*, size_t) for characters.
Parameters
terminator Character used to terminate the reading.
cstr Pointer to a character array.
size Number of bytes to be read.
Returns
Number of characters actually read.
Definition at line 364 of file stream.cpp.
References Stream::read_bytes_until().
{
     return read_bytes_until(terminator, (uint8_t*)cstr, size);
 }
read_string_until()
String Stream::read_string_until (char terminator = '\n') inherited
Read a string from the input stream until any more bytes are available or the terminator character is reached.
Parameters
terminator Character used to terminate the reading.
Returns
Input stream string.
Definition at line 368 of file stream.cpp.
References Stream::timed_read().
{
     int16_t byte;
     String  str;
     // Get bytes if there's any error and the incoming byte is different
     // to the terminator
     byte = timed_read();
     while ((byte >= 0) && (byte != terminator)) {
         str += (char) byte;
         byte = timed_read();
     }
     // Return a string
     return str;
 }
ignore_bytes_until()
bool Stream::ignore_bytes_until (char terminator) inherited
Ignore the input stream until a terminator is detected.
Parameters
terminator Character used to terminate the ignoring.
Returns
True if the next byte is the terminator, False if empty or timed out.
Definition at line 384 of file stream.cpp.
References Stream::read(), and Stream::timed_peek().
{
     int16_t byte;
     byte = timed_peek();
     // Peek the next byte, if the next byte is the terminator or
     // there's no any more bytes, return
     while ((byte >= 0) && (byte != terminator)) {
         byte = read();
     }
     // If timed out or rx empty, false
     return !(byte < 0);
 }
print_uint()
size_t Stream::print_uint (uint32_t num, num_base_t base) protected inherited
Converts a unsigned integer into a string and writes the characters on the TX buffer.
Parameters
num Number to be converted.
base Number desired base: BIN, OCT, DEC, HEX.
Returns
Number of characters written.
Definition at line 35 of file stream.cpp.
References Stream::write().
Referenced by Stream::print(), and Stream::print_int().
{
     char num_str[12];   // Max U32: 4294967295 => 10 digits
     char *str = &num_str[sizeof(num_str) - 1];
     char tmp;
     *str='\0';
     do {
         tmp = num % base;
         num /= base;
         *--str = (tmp < 10)? tmp + '0' : (tmp - 10) + 'A';
     } while (num);
     return write(str);
 }
print_int()
size_t Stream::print_int (int32_t num, num_base_t base) protected inherited
Extends Stream::print_uint(uint32_t, num_base_t) for signed integers.
Parameters
num Number to be converted.
base Number desired base: BIN, OCT, DEC, HEX.
Returns
Number of characters written.
Definition at line 48 of file stream.cpp.
References Stream::print_uint(), and Stream::write().
Referenced by Stream::print().
{
     size_t len = 0;
     // Handle negative numbers
     if (num < 0) {
         len += write('-');
         num = -num;
     }
     // Print integer
     return print_uint(num, base) + len;
 }
print_double()
size_t Stream::print_double (double num, uint8_t p) protected inherited
Converts a double into a string and writes the characters on the TX buffer.
Parameters
num Number to be converted.
p Number of decimal positions.
Returns
Number of characters written.
Definition at line 59 of file stream.cpp.
References F, Stream::print(), and Stream::write().
Referenced by Stream::print().
{
     if (isnan(num)) return print(F("nan"));
     if (isinf(num)) return print(F("inf"));
     if (num > 4294967040.0) return print(F("ovf"));
     if (num <-4294967040.0) return print(F("ovf"));
     size_t len = 0;
     // Handle negative numbers
     if (num < 0.0) {
         len += write('-');
         num = -num;
     }
     // Round
     double round = 0.5;
     for (uint8_t idx=0; idx < p; idx++)
         round /= 10.0;
     num += round;
     // Print the integer part
     uint32_t int_num = (uint32_t) num;
     double   dec_num = num - int_num;
     len += print(int_num);
     // Print the decimal point
     if (p > 0) len += write('.');
     // Print the decimal part
     while (p-- > 0) {
         dec_num *= 10.0;
         uint8_t dec = (uint8_t) dec_num;
         len+= print(dec);
         dec_num -= dec;
     }
     // Return the number of printed characters
     return len;
 }
timed_peek()
int16_t Stream::timed_peek (void) protected inherited
Peeks the input stream using a timeout.
Definition at line 157 of file stream.cpp.
References Stream::_rx_time_start, Stream::_rx_timeout, get_millis(), and Stream::peek().
Referenced by Stream::ignore_bytes_until(), Stream::parse_double(), Stream::parse_int(), and Stream::peek_next_digit().
{
     int16_t byte;
     _rx_time_start = get_millis();
     // While time < timeout
     do {
         byte = peek();
         if (byte >= 0) return byte;
     } while ((get_millis() - _rx_time_start) < _rx_timeout);
     // If no bytes where available before the timeout
     return -1;
 }
timed_read()
int16_t Stream::timed_read (void) protected inherited
Reads the input stream using a timeout.
Definition at line 171 of file stream.cpp.
References Stream::_rx_time_start, Stream::_rx_timeout, get_millis(), and Stream::read().
Referenced by Stream::read_bytes(), Stream::read_bytes_until(), Stream::read_string(), and Stream::read_string_until().
{
     int16_t byte;
     _rx_time_start = get_millis();
     // While time < timeout
     do {
         byte = read();
         if (byte >= 0) return byte;
     } while((get_millis() - _rx_time_start) < _rx_timeout);
     // If no bytes where available before the timeout
     return -1;
 }
peek_next_digit()
int16_t Stream::peek_next_digit (stream_look_mode_t look_mode, bool is_decimal) protected inherited
Peek the input stream with a timeout. It search if the peeked byte is part of a digit.
Parameters
look_mode Look ahead modes. Checkout stream_look_mode_t for more info.
is_decimal Accept the detection of decimal points.
Returns
Return the next numeric byte on the stream or -1 if timeout.
Definition at line 186 of file stream.cpp.
References Stream::read(), SKIP_ALL, SKIP_NONE, SKIP_WHITESPACE, and Stream::timed_peek().
Referenced by Stream::parse_double(), and Stream::parse_int().
{
     int16_t byte;
     while (true) {
         // Get the next byte (if any)
         byte = timed_peek();
         // If there's no byte available or the byte is numeric return the byte
         if (
             (byte < 0) ||                       // No byte or timeout reached (error -1)
             (byte == '-') ||                    // Negative value
             ((byte >= '0') && (byte <= '9')) || // Numeric char
             (is_decimal && (byte == '.'))       // Decimal point
             )
             return byte;
         // If the method reach this point that means that the byte is non numeric.
         // This checks if the detected byte has to be skipped.
         switch (look_mode) {
             case SKIP_NONE: return -1;  break;  // Returns that no numeric byte was detected.
             case SKIP_ALL:              break;  // Just skip the byte (until a numeric byte is detected).
             case SKIP_WHITESPACE: {
                 switch (byte) {
                     case ' ':
                     case '\t':
                     case '\r':
                     case '\n':          break;  // If any of this bytes is detected, skip.
                     default: return -1; break;  // Return that no numeric byte was detected.
                 }
             } break;
         }
         // Reading the buffer will "skip" the byte.
         read();
     }
 }
Member Data Documentation
_ctrl
volatile uart_ctrl_t* UART::_ctrl protected
UART control registers.
Definition at line 118 of file uart.h.
_baud
volatile uint16_t* UART::_baud protected
UART baudrate register.
Definition at line 119 of file uart.h.
_data
volatile uint8_t* UART::_data protected
UART data register.
Definition at line 120 of file uart.h.
_used
volatile bool UART::_used protected
Flag that indicates if the bus was used.
Definition at line 121 of file uart.h.
_rx_buff
volatile uint8_t UART::_rx_buff[UART_BUFF_SIZE] protected
RX buffer.
Definition at line 122 of file uart.h.
_rx_buff_head
volatile uint8_t UART::_rx_buff_head protected
RX buffer head index.
Definition at line 123 of file uart.h.
_rx_buff_tail
volatile uint8_t UART::_rx_buff_tail protected
RX buffer tail index.
Definition at line 124 of file uart.h.
_tx_buff
volatile uint8_t UART::_tx_buff[UART_BUFF_SIZE] protected
TX buffer.
Definition at line 125 of file uart.h.
_tx_buff_head
volatile uint8_t UART::_tx_buff_head protected
TX buffer head index.
Definition at line 126 of file uart.h.
_tx_buff_tail
volatile uint8_t UART::_tx_buff_tail protected
TX buffer tail index.
Definition at line 127 of file uart.h.
_rx_time_start
uint32_t Stream::_rx_time_start protected inherited
Timeout measurement start.
Definition at line 201 of file stream.h.
Referenced by Stream::timed_peek(), and Stream::timed_read().
_rx_timeout
uint32_t Stream::_rx_timeout protected inherited
Timeout for "reading" functions.
Definition at line 202 of file stream.h.
Referenced by Stream::get_timeout(), Stream::set_timeout(), Stream::timed_peek(), and Stream::timed_read().
The documentation for this class was generated from the following file:
hardware/uart.h