AVRLibs: SPI::Device Class Reference
SPI::Device Class Reference
SPI device class. Use this class to simplify the SPI device creation and configuration.
#include <spi.h>
Public Member Functions
Device (void)
Device empty constructor. Useful in the case that one device can be implemented with more than one communication bus.
Device (SPI *spi, pins_t ss_pin, bool dev_on=false)
Device constructor. Initialize a SPI device and assign the SS pin. Also, this method allows to define the level which the device become active.
void configure (uint32_t freq, spi_tx_mode_t tx_mode, spi_ds_mode_t bit_order)
Set the configuration required to communicate with the device.
void begin_transaction (void)
Activate the device changing the state of the SS pin.
void end_transaction (void)
Deactivate the device changing the state of the SS pin.
uint8_t transfer (uint8_t data)
The master send a single byte to the slave and returns it's response.
void transfer (uint8_t *src, uint8_t *rec, size_t size, uint8_t off=0, uint16_t dly=0)
Perform a data transfer between the SPI master and the slave. Send "size" bytes from "src" and save the responses on "rec". The method allow to start saving the responses after "offset" bytes sent (the master will send "offset" dummy bytes after "src" is transmitted to get the full response) and add delay after each transfer.
void write (uint8_t src, uint16_t dly=0)
write(uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
void write (uint8_t *src, size_t size, uint16_t dly=0)
Write "size" bytes from "src" to the slave.
void write_reg (uint8_t reg, uint8_t src, uint16_t dly=0)
void write_reg (uint8_t reg, uint8_t *src, size_t size, uint16_t dly=0)
Handler of spi_master_write() to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave.
void read (uint8_t *rec, size_t size, uint16_t dly=0)
Read "size" bytes from the slave to "rec".
void read_reg (uint8_t reg, uint8_t *rec, uint16_t dly=0)
void read_reg (uint8_t reg, uint8_t *rec, size_t size, uint16_t dly=0)
Handler of spi_master_read() to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave and copy them to "rec".
Protected Attributes
SPI * _dev_spi
SPI manager.
spi_conf_t _dev_conf
SPI settings.
pins_t _dev_ss
Device SS.
bool _dev_on
Device on SS status.
Detailed Description
SPI device class. Use this class to simplify the SPI device creation and configuration.
Definition at line 156 of file spi.h.
Constructor & Destructor Documentation
Device() [1/2]
SPI::Device::Device (void)
Device empty constructor. Useful in the case that one device can be implemented with more than one communication bus.
Definition at line 194 of file spi.cpp.
                      :
         _dev_spi(NULL), _dev_ss(NO_PIN), _dev_on(false) {
 }
Device() [2/2]
SPI::Device::Device (SPI * spi, pins_t ss_pin, bool dev_on = false)
Device constructor. Initialize a SPI device and assign the SS pin. Also, this method allows to define the level which the device become active.
Parameters
spi SPI bus manager.
ss_pin SS pin.
dev_on Level which have to have the SS pin to activate the device. By default is LOW(false).
Definition at line 198 of file spi.cpp.
References _dev_conf, _dev_on, _dev_spi, SPI::get_config(), OUTPUT, pin_mode(), and pin_write().
                                                      :
         _dev_spi(spi), _dev_ss(ss_pin), _dev_on(dev_on) {
     _dev_spi->get_config(&_dev_conf);
     pin_mode(ss_pin, OUTPUT);
     pin_write(ss_pin, !_dev_on);
 }
Member Function Documentation
configure()
void SPI::Device::configure (uint32_t freq, spi_tx_mode_t tx_mode, spi_ds_mode_t bit_order)
Set the configuration required to communicate with the device.
Parameters
freq SPI SCLK frequency.
tx_mode SPI transmission mode spi_tx_mode_t.
bit_order SPI data transmission mode spi_ds_mode_t.
Definition at line 205 of file spi.cpp.
References _dev_conf, _dev_spi, and SPI::get_config().
Referenced by LIS3DH::LIS3DH().
{
     _dev_spi->get_config(&_dev_conf, freq, tx_mode, bit_order);
 }
begin_transaction()
void SPI::Device::begin_transaction (void)
Activate the device changing the state of the SS pin.
Definition at line 209 of file spi.cpp.
References _dev_conf, _dev_on, _dev_spi, _dev_ss, pin_write(), and SPI::start().
Referenced by LIS3DH::get_registers(), and LIS3DH::set_register().
{
     _dev_spi->start(&_dev_conf);
     pin_write(_dev_ss, _dev_on);
 }
end_transaction()
void SPI::Device::end_transaction (void)
Deactivate the device changing the state of the SS pin.
Definition at line 214 of file spi.cpp.
References _dev_on, _dev_ss, and pin_write().
Referenced by LIS3DH::get_registers(), and LIS3DH::set_register().
{
     pin_write(_dev_ss, !_dev_on);
 }
transfer() [1/2]
uint8_t SPI::Device::transfer (uint8_t data)
The master send a single byte to the slave and returns it's response.
Parameters
data Byte to send.
Returns
Slave response byte.
Definition at line 218 of file spi.cpp.
References _dev_spi, and SPI::transfer().
{
     return _dev_spi->transfer(data);
 }
transfer() [2/2]
void SPI::Device::transfer (uint8_t * src, uint8_t * rec, size_t size, uint8_t off = 0, uint16_t dly = 0)
Perform a data transfer between the SPI master and the slave. Send "size" bytes from "src" and save the responses on "rec". The method allow to start saving the responses after "offset" bytes sent (the master will send "offset" dummy bytes after "src" is transmitted to get the full response) and add delay after each transfer.
Parameters
src Pointer to source byte array.
rec Pointer to received byte array.
size Bytes to be transfered.
off Offset (in bytes).
dly Time to wait between transfers (in [us]).
Definition at line 222 of file spi.cpp.
References _dev_spi, and SPI::transfer().
{
     _dev_spi->transfer(src, rec, size, off, dly);
 }
write() [1/2]
void SPI::Device::write (uint8_t src, uint16_t dly = 0)
write(uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
Parameters
src Source byte.
dly Time to wait after write (in [us]).
Definition at line 226 of file spi.cpp.
References _dev_spi, and SPI::write().
{
     _dev_spi->write(src, dly);
 }
write() [2/2]
void SPI::Device::write (uint8_t * src, size_t size, uint16_t dly = 0)
Write "size" bytes from "src" to the slave.
Parameters
src Pointer to source byte array.
size Bytes to be transmitted.
dly Time to wait between writes (in [us]).
Definition at line 230 of file spi.cpp.
References _dev_spi, and SPI::write().
{
     _dev_spi->write(src, size, dly);
 }
write_reg() [1/2]
void SPI::Device::write_reg (uint8_t reg, uint8_t src, uint16_t dly = 0)
brief write_reg(uint8_t, uint8_t*, uint8_t, uint16_t) handler for 1 byte "src".
Parameters
reg Slave register address.
src Source byte.
dly Time to wait after write (in [us]).
Definition at line 234 of file spi.cpp.
References _dev_spi, and SPI::write_reg().
Referenced by LIS3DH::get_registers(), and LIS3DH::set_register().
{
     _dev_spi->write_reg(reg, src, dly);
 }
write_reg() [2/2]
void SPI::Device::write_reg (uint8_t reg, uint8_t * src, size_t size, uint16_t dly = 0)
Handler of spi_master_write() to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave.
Parameters
reg Slave register address.
src Pointer to source byte array.
size Bytes to be transmitted.
dly Time to wait between writes (in [us]).
Definition at line 238 of file spi.cpp.
References _dev_spi, and SPI::write_reg().
{
     _dev_spi->write_reg(reg, src, size, dly);
 }
read()
void SPI::Device::read (uint8_t * rec, size_t size, uint16_t dly = 0)
Read "size" bytes from the slave to "rec".
Parameters
rec Pointer to received byte array.
size Bytes to be read.
dly Time to wait between reads (in [us]).
Definition at line 242 of file spi.cpp.
References _dev_spi, and SPI::read().
{
     _dev_spi->read(rec, size, dly);
 }
read_reg() [1/2]
void SPI::Device::read_reg (uint8_t reg, uint8_t * rec, uint16_t dly = 0)
brief read_reg(uint8_t, uint8_t*, uint8_t, uint16_t) handler for 1 byte "rec".
Parameters
reg Slave register address.
rec Receive byte.
dly Time to wait after write (in [us]).
Definition at line 246 of file spi.cpp.
References _dev_spi, and SPI::read_reg().
{
     _dev_spi->read_reg(reg, rec, dly);
 }
read_reg() [2/2]
void SPI::Device::read_reg (uint8_t reg, uint8_t * rec, size_t size, uint16_t dly = 0)
Handler of spi_master_read() to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave and copy them to "rec".
Parameters
reg Slave register address.
rec Pointer to received byte array.
size Bytes to be read.
dly Time to wait between reads (in [us]).
Definition at line 250 of file spi.cpp.
References _dev_spi, and SPI::read_reg().
{
     _dev_spi->read_reg(reg, rec, size, dly);
 }
Member Data Documentation
_dev_spi
SPI* SPI::Device::_dev_spi protected
SPI manager.
Definition at line 223 of file spi.h.
Referenced by begin_transaction(), configure(), Device(), read(), read_reg(), transfer(), write(), and write_reg().
_dev_conf
spi_conf_t SPI::Device::_dev_conf protected
SPI settings.
Definition at line 224 of file spi.h.
Referenced by begin_transaction(), configure(), and Device().
_dev_ss
pins_t SPI::Device::_dev_ss protected
Device SS.
Definition at line 225 of file spi.h.
Referenced by begin_transaction(), and end_transaction().
_dev_on
bool SPI::Device::_dev_on protected
Device on SS status.
Definition at line 226 of file spi.h.
Referenced by begin_transaction(), Device(), and end_transaction().
The documentation for this class was generated from the following files:
hardware/spi.h
hardware/spi.cpp