AVRLibs: DRV2605 Class Reference
DRV2605 Class Reference
DRV2605 diver class.
#include <drv2605.h>
Public Member Functions
DRV2605 (TWI *twi)
DRV2650 constructor (for devices with no access to the enable pin).
DRV2605 (TWI *twi, pins_t en_pin)
DRV2650 constructor.
void set_defaults (void)
Set the registers to the default values (reset the device).
uint8_t get_ID (void)
Get the device ID. This can be used to check if the I2C comms are working.
void set_motor (bool is_lra, uint8_t v_rat, uint8_t odc_lamp)
Set the motor parameters. Need to execute the auto-calibration afterwards.
void set_motor (bool is_lra, uint8_t v_rat, uint8_t odc_lamp, uint8_t acal_comp, uint8_t acal_bemf, uint8_t acal_fbctrl)
Set the motor parameters and a previous auto-calibration results.
void set_active_mode (void)
Enable the DRV2605 driver.
void set_standby_mode (void)
Disable the DRV2605 driver.
void set_PWM_mode (void)
Configure the driver to work on PWM mode.
void initialize (drv2605_bkfc_t brake_factor, drv2605_lpg_t loop_gain, uint8_t drive_time, bool startup_boost, bool brake_stabilizer, bool bidir_input, bool open_loop, bool pwm_input)
Initialize the DRV2605 with previous auto-calibration results. See DRV2605::set_motor(bool, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t).
bool calibrate (drv2605_bkfc_t brake_factor, drv2605_lpg_t loop_gain, drv2605_acalt_t cal_time, uint8_t drive_time, bool startup_boost, bool brake_stabilizer, bool bidir_input, bool open_loop, bool pwm_input)
Perform an auto-calibration process on the DRV2605.
double get_LRA_period (void)
Get the LRA motor period value.
Protected Member Functions
uint16_t write (uint8_t src, bool stop=true)
TWI::write(uint8_t, uint8_t, bool) with the slave address fixed.
uint16_t write (uint8_t *src, size_t size, bool stop=true)
TWI::write(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t write_reg (uint8_t reg, uint8_t src, bool stop=true)
TWI::write_reg(uint8_t, uint8_t, uint8_t, bool) with the slave address fixed.
uint16_t write_reg (uint8_t reg, uint8_t *src, size_t size, bool stop=true)
TWI::write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t read (uint8_t *rec, bool stop)
TWI::read(uint8_t, uint8_t*, bool) with the slave address fixed.
uint16_t read (uint8_t *rec, size_t size, bool stop=true)
TWI::read(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t read_reg (uint8_t reg, uint8_t *rec, bool stop=true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, bool) with the slave address fixed.
uint16_t read_reg (uint8_t reg, uint8_t *rec, size_t size, bool stop=true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Protected Attributes
TWI * _dev_twi
TWI manager.
uint8_t _dev_addr
Device address.
Private Member Functions
void initialize_values (drv2605_bkfc_t brake_factor, drv2605_lpg_t loop_gain, uint8_t drive_time, bool startup_boost, bool brake_stabilizer, bool bidir_input, bool open_loop, bool pwm_input)
Initialize the DRV2605.
void set_register (uint8_t src, uint8_t reg)
Write a register "reg" with the value given by "src". handler to set a single register.
void get_register (uint8_t *rec, uint8_t reg)
DRV2605::get_register(uint8_t*, uint8_t, uint8_t) handler to get a single byte.
void get_registers (uint8_t *rec, uint8_t reg, size_t size)
read a "size" number of registers on "rec" starting from "reg" register.
Private Attributes
struct {
uint8_t v_rat
Rated voltage register value.
uint8_t odc_lamp
OC Clamp voltage register value.
uint8_t acal_comp
Auto-calibration compensation result.
uint8_t acal_BEMF
Auto-calibration back-EMF value.
uint8_t acal_feedback
Auto-calibration feedback control register value.
bool is_LRA
Motor type.
} _motor
pins_t _en_pin
Detailed Description
DRV2605 diver class.
Definition at line 17 of file drv2605.h.
Constructor & Destructor Documentation
DRV2605() [1/2]
DRV2605::DRV2605 (TWI * twi)
DRV2650 constructor (for devices with no access to the enable pin).
Parameters
twi TWI bus manager.
Definition at line 15 of file drv2605.cpp.
References timing_enable().
                         : TWI::Device(twi, DRV2605_ADDR), _en_pin(NO_PIN) {
     // Start the timing functions
     timing_enable();
 }
DRV2605() [2/2]
DRV2605::DRV2605 (TWI * twi, pins_t en_pin)
DRV2650 constructor.
Parameters
twi TWI bus manager.
en_pin Enable pin.
Definition at line 20 of file drv2605.cpp.
References _en_pin, OUTPUT, pin_mode(), and timing_enable().
                                        : TWI::Device(twi, DRV2605_ADDR), _en_pin(en_pin) {
     // Configure the enable pin
     pin_mode(_en_pin, OUTPUT);
     // Start the timing functions
     timing_enable();
 }
Member Function Documentation
set_defaults()
void DRV2605::set_defaults (void)
Set the registers to the default values (reset the device).
Definition at line 28 of file drv2605.cpp.
References delay_micros(), DRV2605_REG_MODE, set_active_mode(), and update_field.
Referenced by calibrate(), and initialize().
{
     drv2605_reg_t reg;
     // Reset the device
     update_field(reg, DRV2605_REG_MODE, mode, DEV_RST, 1);
     // Give the device time to restart
     delay_micros(300);
     // Activate the module again
     set_active_mode();
 }
get_ID()
uint8_t DRV2605::get_ID (void)
Get the device ID. This can be used to check if the I2C comms are working.
Returns
Device ID code (see datasheet).
Definition at line 38 of file drv2605.cpp.
References drv2605_reg_stat_t::DEV_ID, DRV2605_REG_STAT, get_register(), drv2605_reg_t::raw, and drv2605_reg_t::stat.
{
     drv2605_reg_t reg;
     get_register(&reg.raw, DRV2605_REG_STAT);
     return reg.stat.DEV_ID;
 }
set_motor() [1/2]
void DRV2605::set_motor (bool is_lra, uint8_t v_rat, uint8_t odc_lamp)
Set the motor parameters. Need to execute the auto-calibration afterwards.
Parameters
is_lra Motor type (LRA or ERM).
v_rat Motor rated voltage.
odc_lamp Motor over-drive voltage.
Definition at line 45 of file drv2605.cpp.
Referenced by set_motor().
{
     _motor.v_rat = v_rat;
     _motor.odc_lamp = odc_lamp;
     _motor.is_LRA = is_lra;
 }
set_motor() [2/2]
void DRV2605::set_motor (bool is_lra, uint8_t v_rat, uint8_t odc_lamp, uint8_t acal_comp, uint8_t acal_bemf, uint8_t acal_fbctrl)
Set the motor parameters and a previous auto-calibration results.
Parameters
is_lra Motor type (LRA or ERM).
v_rat Motor rated voltage.
odc_lamp Motor over-drive voltage.
acal_comp Auto-calibration compensation result.
acal_bemf Auto-calibration back-EMF result.
acal_fbctrl Auto-calibration back-EMF gain (feedback control register).
Definition at line 51 of file drv2605.cpp.
References set_motor().
{
     set_motor(is_lra, v_rat, odc_lamp);
     _motor.acal_comp = acal_comp;
     _motor.acal_BEMF = acal_bemf;
     _motor.acal_feedback = acal_fbctrl;
 }
set_active_mode()
void DRV2605::set_active_mode (void)
Enable the DRV2605 driver.
Definition at line 60 of file drv2605.cpp.
References _en_pin, DRV2605_REG_MODE, pin_write(), and update_field.
Referenced by set_defaults().
{
     drv2605_reg_t reg;
     // If possible, set enable HIGH
     pin_write(_en_pin, true);
     // Set mode: Active
     update_field(reg, DRV2605_REG_MODE, mode, SBY, 0);
 }
set_standby_mode()
void DRV2605::set_standby_mode (void)
Disable the DRV2605 driver.
Definition at line 68 of file drv2605.cpp.
References _en_pin, DRV2605_REG_MODE, pin_write(), and update_field.
{
     drv2605_reg_t reg;
     // Set mode: Standby
     update_field(reg, DRV2605_REG_MODE, mode, SBY, 1);
     // If possible, set enable LOW
     pin_write(_en_pin, false);
 }
set_PWM_mode()
void DRV2605::set_PWM_mode (void)
Configure the driver to work on PWM mode.
Definition at line 77 of file drv2605.cpp.
References DRV2605_REG_MODE, and update_field.
{
     drv2605_reg_t reg;
     // Set mode as PWM/Analog input
     update_field(reg, DRV2605_REG_MODE, mode, MODE, 0x03);
 }
initialize()
void DRV2605::initialize (drv2605_bkfc_t brake_factor, drv2605_lpg_t loop_gain, uint8_t drive_time, bool startup_boost, bool brake_stabilizer, bool bidir_input, bool open_loop, bool pwm_input)
Initialize the DRV2605 with previous auto-calibration results. See DRV2605::set_motor(bool, uint8_t, uint8_t, uint8_t, uint8_t, uint8_t).
Parameters
brake_factor Set the gain ratio between the braking gain and the driving gain.
loop_gain Set how fast the driver attempts to make the BEMF match the input signal.
drive_time Set the sample rate for the BEMF detection.
startup_boost Define if startup boost is active: Active(true), Inactive(false).
brake_stabilizer Define if brake stabilizer is active: Active(true), Inactive(false).
bidir_input Define how the engine interprets data: bidirectional(true), unidirectional(false).
open_loop Define the operation mode: open-loop(true), closed-loop(false).
pwm_input Define if the input type: PWM(true), Analog(false).
Definition at line 84 of file drv2605.cpp.
References DRV2605_REG_ACAL_BEMF, DRV2605_REG_ACAL_COMP, DRV2605_REG_FB_CTRL, initialize_values(), set_defaults(), set_register(), and update_field.
{
     drv2605_reg_t reg;
     // Set defaults
     set_defaults();
     // Set auto-calibration compensation results
     set_register(_motor.acal_comp, DRV2605_REG_ACAL_COMP);
     // Set auto-calibration BEMF results
     set_register(_motor.acal_BEMF, DRV2605_REG_ACAL_BEMF);
     // Initialize values
     initialize_values(brake_factor, loop_gain, drive_time, startup_boost,
                 brake_stabilizer, bidir_input, open_loop, pwm_input);
     // Set auto-calibration BEMF gain result
     update_field(reg, DRV2605_REG_FB_CTRL, fb_ctrl, BEMF_GN, (0x03 & _motor.acal_feedback));
 }
calibrate()
bool DRV2605::calibrate (drv2605_bkfc_t brake_factor, drv2605_lpg_t loop_gain, drv2605_acalt_t cal_time, uint8_t drive_time, bool startup_boost, bool brake_stabilizer, bool bidir_input, bool open_loop, bool pwm_input)
Perform an auto-calibration process on the DRV2605.
Parameters
cal_time Time used to perform the auto-calibration process.
brake_factor Set the gain ratio between the braking gain and the driving gain.
loop_gain Set how fast the driver attempts to make the BEMF match the input signal.
drive_time Set the sample rate for the BEMF detection.
startup_boost Define if startup boost is active: Active(true), Inactive(false).
brake_stabilizer Define if brake stabilizer is active: Active(true), Inactive(false).
bidir_input Define how the engine interprets data: bidirectional(true), unidirectional(false).
open_loop Define the operation mode: open-loop(true), closed-loop(false).
pwm_input Define if the input type: PWM(true), Analog(false).
Returns
True if calibration process was succesful, False otherwise.
Definition at line 101 of file drv2605.cpp.
References delay_millis(), drv2605_reg_stat_t::DIAG_RES, DRV2605_REG_ACAL_BEMF, DRV2605_REG_ACAL_COMP, DRV2605_REG_CTRL4, DRV2605_REG_FB_CTRL, DRV2605_REG_GO, DRV2605_REG_MODE, DRV2605_REG_STAT, get_register(), drv2605_reg_go_t::GO, drv2605_reg_t::go, initialize_values(), drv2605_reg_t::raw, set_defaults(), set_register(), drv2605_reg_t::stat, and update_field.
{
     uint8_t time = 0;
     drv2605_reg_t reg;
     // Set defaults
     set_defaults();
     // Initialize values
     initialize_values(brake_factor, loop_gain, drive_time, startup_boost,
             brake_stabilizer, bidir_input, open_loop, pwm_input);
     // Set mode
     set_register(0x07, DRV2605_REG_MODE);                                           // Auto-calibration mode
     // Set auto-calibration memory
     update_field(reg, DRV2605_REG_CTRL4, ctrl4, A_CAL_TM, cal_time);
     // Run auto-calibration
     update_field(reg, DRV2605_REG_GO, go, GO, 1);
     // Wait until it's ready... GO = 0
     // Maximum time: 2500[ms]
     do {
         delay_millis(10);
         get_register(&reg.raw, DRV2605_REG_GO);
         time++;
     } while (reg.go.GO && (time < 250));
     // Check for errors
     get_register(&reg.raw, DRV2605_REG_STAT);
     if (reg.stat.DIAG_RES)
         return false;
     // Get compensation, backEMF and feedback values
     get_register(&_motor.acal_comp, DRV2605_REG_ACAL_COMP);
     get_register(&_motor.acal_BEMF, DRV2605_REG_ACAL_BEMF);
     get_register(&_motor.acal_feedback, DRV2605_REG_FB_CTRL);
     // Process complete
     return true;
 }
get_LRA_period()
double DRV2605::get_LRA_period (void)
Get the LRA motor period value.
Returns
LRA period.
Definition at line 141 of file drv2605.cpp.
References DRV2605_REG_LRA_RES, and get_register().
{
     uint8_t lra_period;
     // Read the LRA period register (1 byte)
     get_register(&lra_period, DRV2605_REG_LRA_RES);
     // Return the LRA period:
     return 98.46 * (double)lra_period;
 }
initialize_values()
void DRV2605::initialize_values (drv2605_bkfc_t brake_factor, drv2605_lpg_t loop_gain, uint8_t drive_time, bool startup_boost, bool brake_stabilizer, bool bidir_input, bool open_loop, bool pwm_input) private
Initialize the DRV2605.
Parameters
brake_factor Set the gain ratio between the braking gain and the driving gain.
loop_gain Set how fast the driver attempts to make the BEMF match the input signal.
drive_time Set the sample rate for the BEMF detection.
startup_boost Define if startup boost is active: Active(true), Inactive(false).
brake_stabilizer Define if brake stabilizer is active: Active(true), Inactive(false).
bidir_input Define how the engine interprets data: bidirectional(true), unidirectional(false).
open_loop Define the operation mode: open-loop(true), closed-loop(false).
pwm_input Define if the input type: PWM(true), Analog(false).
Definition at line 150 of file drv2605.cpp.
References drv2605_reg_ctrl2_t::BDIR_IN, drv2605_reg_fbctrl_t::BK_FCTR, drv2605_reg_ctrl2_t::BK_STB, drv2605_reg_t::ctrl1, drv2605_reg_t::ctrl2, drv2605_reg_t::ctrl3, DRV2605_REG_CLAMPV, DRV2605_REG_CTRL1, DRV2605_REG_CTRL2, DRV2605_REG_CTRL3, DRV2605_REG_FB_CTRL, DRV2605_REG_RATEDV, drv2605_reg_ctrl1_t::DRV_TM, drv2605_reg_ctrl3_t::ERM_O_LP, drv2605_reg_t::fb_ctrl, get_register(), drv2605_reg_fbctrl_t::IS_LRA, drv2605_reg_fbctrl_t::LP_GN, drv2605_reg_ctrl3_t::LRA_O_LP, drv2605_reg_ctrl3_t::PWM_IN, drv2605_reg_t::raw, set_register(), and drv2605_reg_ctrl1_t::ST_BST.
Referenced by calibrate(), and initialize().
{
     drv2605_reg_t reg;
     // Set rated voltage
     set_register(_motor.v_rat, DRV2605_REG_RATEDV);
     // Set over-drive voltage
     set_register(_motor.odc_lamp, DRV2605_REG_CLAMPV);
     // Set feedback control
     get_register(&reg.raw, DRV2605_REG_FB_CTRL);
     reg.fb_ctrl.LP_GN = loop_gain;
     reg.fb_ctrl.IS_LRA = _motor.is_LRA;
     reg.fb_ctrl.BK_FCTR = brake_factor;
     set_register(reg.raw, DRV2605_REG_FB_CTRL);
     // Set control registers
     // Control 1
     get_register(&reg.raw, DRV2605_REG_CTRL1);
     reg.ctrl1.DRV_TM = drive_time;
     reg.ctrl1.ST_BST = startup_boost;
     set_register(reg.raw, DRV2605_REG_CTRL1);
     // Control 2
     get_register(&reg.raw, DRV2605_REG_CTRL2);
     reg.ctrl2.BDIR_IN = bidir_input;
     reg.ctrl2.BK_STB = brake_stabilizer;
     set_register(reg.raw, DRV2605_REG_CTRL2);
     // Control 3
     get_register(&reg.raw, DRV2605_REG_CTRL3);
     reg.ctrl3.PWM_IN = !pwm_input;
     if (_motor.is_LRA)
         reg.ctrl3.LRA_O_LP = open_loop;
     else
         reg.ctrl3.ERM_O_LP = open_loop;
     set_register(reg.raw, DRV2605_REG_CTRL3);
 }
set_register()
void DRV2605::set_register (uint8_t src, uint8_t reg) private
Write a register "reg" with the value given by "src". handler to set a single register.
Parameters
src Source byte.
reg Device register address.
Definition at line 186 of file drv2605.cpp.
References TWI::Device::write_reg().
Referenced by calibrate(), initialize(), and initialize_values().
{
     write_reg(reg, src, true);
 }
get_register()
void DRV2605::get_register (uint8_t * rec, uint8_t reg) private
DRV2605::get_register(uint8_t*, uint8_t, uint8_t) handler to get a single byte.
Parameters
rec Receiver byte.
reg Device register address.
Definition at line 190 of file drv2605.cpp.
References get_registers().
Referenced by calibrate(), get_ID(), get_LRA_period(), and initialize_values().
{
     get_registers(rec, reg, 1);
 }
get_registers()
void DRV2605::get_registers (uint8_t * rec, uint8_t reg, size_t size) private
read a "size" number of registers on "rec" starting from "reg" register.
Parameters
rec Pointer to received byte array.
reg Device register address.
size Number of bytes to read.
Definition at line 194 of file drv2605.cpp.
References TWI::Device::read_reg().
Referenced by get_register().
{
     read_reg(reg, rec, size);
 }
write() [1/2]
uint16_t TWI::Device::write (uint8_t src, bool stop = true) inherited
TWI::write(uint8_t, uint8_t, bool) with the slave address fixed.
Definition at line 192 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write().
{
     return _dev_twi->write(_dev_addr, src, stop);
 }
write() [2/2]
uint16_t TWI::Device::write (uint8_t * src, size_t size, bool stop = true) inherited
TWI::write(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 196 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write().
{
     return _dev_twi->write(_dev_addr, src, size, stop);
 }
write_reg() [1/2]
uint16_t TWI::Device::write_reg (uint8_t reg, uint8_t src, bool stop = true) inherited
TWI::write_reg(uint8_t, uint8_t, uint8_t, bool) with the slave address fixed.
Definition at line 200 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write_reg().
Referenced by set_register(), and LIS3DH::set_register().
{
     return _dev_twi->write_reg(_dev_addr, reg, src, stop);
 }
write_reg() [2/2]
uint16_t TWI::Device::write_reg (uint8_t reg, uint8_t * src, size_t size, bool stop = true) inherited
TWI::write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 204 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::write_reg().
{
     return _dev_twi->write_reg(_dev_addr, reg, src, size, stop);
 }
read() [1/2]
uint16_t TWI::Device::read (uint8_t * rec, bool stop) inherited
TWI::read(uint8_t, uint8_t*, bool) with the slave address fixed.
Definition at line 208 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read().
{
     return _dev_twi->read(_dev_addr, rec, stop);
 }
read() [2/2]
uint16_t TWI::Device::read (uint8_t * rec, size_t size, bool stop = true) inherited
TWI::read(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 212 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read().
{
     return _dev_twi->read(_dev_addr, rec, size, stop);
 }
read_reg() [1/2]
uint16_t TWI::Device::read_reg (uint8_t reg, uint8_t * rec, bool stop = true) inherited
TWI::read_reg(uint8_t, uint8_t, uint8_t*, bool) with the slave address fixed.
Definition at line 216 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read_reg().
Referenced by get_registers(), and LIS3DH::get_registers().
{
     return _dev_twi->read_reg(_dev_addr, reg, rec, stop);
 }
read_reg() [2/2]
uint16_t TWI::Device::read_reg (uint8_t reg, uint8_t * rec, size_t size, bool stop = true) inherited
TWI::read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 220 of file twi.cpp.
References TWI::Device::_dev_addr, TWI::Device::_dev_twi, and TWI::read_reg().
{
     return _dev_twi->read_reg(_dev_addr, reg, rec, size, stop);
 }
Member Data Documentation
_motor
struct { ... } DRV2605::_motor
_en_pin
pins_t DRV2605::_en_pin private
Enable pin
Definition at line 125 of file drv2605.h.
Referenced by DRV2605(), set_active_mode(), and set_standby_mode().
_dev_twi
TWI* TWI::Device::_dev_twi protected inherited
TWI manager.
Definition at line 246 of file twi.h.
Referenced by TWI::Device::read(), TWI::Device::read_reg(), TWI::Device::write(), and TWI::Device::write_reg().
_dev_addr
uint8_t TWI::Device::_dev_addr protected inherited
Device address.
Definition at line 247 of file twi.h.
Referenced by TWI::Device::read(), TWI::Device::read_reg(), TWI::Device::write(), and TWI::Device::write_reg().
The documentation for this class was generated from the following files:
device/drv2605.h
device/drv2605.cpp