AVRLibs: TWI::Device Class Reference
TWI::Device Class Reference
TWI device class. Use this class to simplify the TWI device creation and configuration.
#include <twi.h>
Public Member Functions
Device (void)
Device empty constructor. Useful in the case that one device can be implemented with more than one communication bus.
Device (TWI *twi, uint8_t addr)
device constructor. Initialize a TWI device and assign it's address.
uint16_t write (uint8_t src, bool stop=true)
TWI::write(uint8_t, uint8_t, bool) with the slave address fixed.
uint16_t write (uint8_t *src, size_t size, bool stop=true)
TWI::write(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t write_reg (uint8_t reg, uint8_t src, bool stop=true)
TWI::write_reg(uint8_t, uint8_t, uint8_t, bool) with the slave address fixed.
uint16_t write_reg (uint8_t reg, uint8_t *src, size_t size, bool stop=true)
TWI::write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t read (uint8_t *rec, bool stop)
TWI::read(uint8_t, uint8_t*, bool) with the slave address fixed.
uint16_t read (uint8_t *rec, size_t size, bool stop=true)
TWI::read(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
uint16_t read_reg (uint8_t reg, uint8_t *rec, bool stop=true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, bool) with the slave address fixed.
uint16_t read_reg (uint8_t reg, uint8_t *rec, size_t size, bool stop=true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Protected Attributes
TWI * _dev_twi
TWI manager.
uint8_t _dev_addr
Device address.
Detailed Description
TWI device class. Use this class to simplify the TWI device creation and configuration.
Definition at line 181 of file twi.h.
Constructor & Destructor Documentation
Device() [1/2]
TWI::Device::Device (void)
Device empty constructor. Useful in the case that one device can be implemented with more than one communication bus.
Definition at line 186 of file twi.cpp.
                      : _dev_twi(NULL), _dev_addr(0x00) {
 }
Device() [2/2]
TWI::Device::Device (TWI * twi, uint8_t addr)
device constructor. Initialize a TWI device and assign it's address.
Parameters
twi TWI bus manager.
addr Device address.
Definition at line 189 of file twi.cpp.
                                        : _dev_twi(twi), _dev_addr(addr) {
 }
Member Function Documentation
write() [1/2]
uint16_t TWI::Device::write (uint8_t src, bool stop = true)
TWI::write(uint8_t, uint8_t, bool) with the slave address fixed.
Definition at line 192 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::write().
{
     return _dev_twi->write(_dev_addr, src, stop);
 }
write() [2/2]
uint16_t TWI::Device::write (uint8_t * src, size_t size, bool stop = true)
TWI::write(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 196 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::write().
{
     return _dev_twi->write(_dev_addr, src, size, stop);
 }
write_reg() [1/2]
uint16_t TWI::Device::write_reg (uint8_t reg, uint8_t src, bool stop = true)
TWI::write_reg(uint8_t, uint8_t, uint8_t, bool) with the slave address fixed.
Definition at line 200 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::write_reg().
Referenced by DRV2605::set_register(), and LIS3DH::set_register().
{
     return _dev_twi->write_reg(_dev_addr, reg, src, stop);
 }
write_reg() [2/2]
uint16_t TWI::Device::write_reg (uint8_t reg, uint8_t * src, size_t size, bool stop = true)
TWI::write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 204 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::write_reg().
{
     return _dev_twi->write_reg(_dev_addr, reg, src, size, stop);
 }
read() [1/2]
uint16_t TWI::Device::read (uint8_t * rec, bool stop)
TWI::read(uint8_t, uint8_t*, bool) with the slave address fixed.
Definition at line 208 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::read().
{
     return _dev_twi->read(_dev_addr, rec, stop);
 }
read() [2/2]
uint16_t TWI::Device::read (uint8_t * rec, size_t size, bool stop = true)
TWI::read(uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 212 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::read().
{
     return _dev_twi->read(_dev_addr, rec, size, stop);
 }
read_reg() [1/2]
uint16_t TWI::Device::read_reg (uint8_t reg, uint8_t * rec, bool stop = true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, bool) with the slave address fixed.
Definition at line 216 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::read_reg().
Referenced by DRV2605::get_registers(), and LIS3DH::get_registers().
{
     return _dev_twi->read_reg(_dev_addr, reg, rec, stop);
 }
read_reg() [2/2]
uint16_t TWI::Device::read_reg (uint8_t reg, uint8_t * rec, size_t size, bool stop = true)
TWI::read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) with the slave address fixed.
Definition at line 220 of file twi.cpp.
References _dev_addr, _dev_twi, and TWI::read_reg().
{
     return _dev_twi->read_reg(_dev_addr, reg, rec, size, stop);
 }
Member Data Documentation
_dev_twi
TWI* TWI::Device::_dev_twi protected
TWI manager.
Definition at line 246 of file twi.h.
Referenced by read(), read_reg(), write(), and write_reg().
_dev_addr
uint8_t TWI::Device::_dev_addr protected
Device address.
Definition at line 247 of file twi.h.
Referenced by read(), read_reg(), write(), and write_reg().
The documentation for this class was generated from the following files:
hardware/twi.h
hardware/twi.cpp