AVRLibs: TWI Class Reference
TWI Class Reference
TWI bus general implementation.
#include <twi.h>
Classes
class Device
TWI device class. Use this class to simplify the TWI device creation and configuration.
Public Member Functions
void disable (void)
Disable the TWI bus and clean, if slave operation was used, the slave RX buffer.
void set_clock (uint16_t freq=TWI_DEF_FREQ_KHZ)
Set the SCL clock frequency.
void enable (void)
Configure the TWI bus to support master operation. This function initialize the bus with the default frequency (100KHz).
uint16_t write (uint8_t addr, uint8_t src, bool stop=true)
write(uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "src".
uint16_t write (uint8_t addr, uint8_t *src, size_t size, bool stop=true)
Write "size" bytes from "src" on the slave given by the "addr" address.
uint16_t write_reg (uint8_t addr, uint8_t reg, uint8_t src, bool stop=true)
write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "src".
uint16_t write_reg (uint8_t addr, uint8_t reg, uint8_t *src, size_t size, bool stop=true)
Handler of write(uint8_t, uint8_t*, uint8_t, bool) to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave given by the "addr" address.
uint16_t read (uint8_t addr, uint8_t *rec, bool stop=true)
read(uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "rec".
uint16_t read (uint8_t addr, uint8_t *rec, size_t size, bool stop=true)
Read "size" bytes from the slave given by the "addr" address and copy them to "rec".
uint16_t read_reg (uint8_t addr, uint8_t reg, uint8_t *rec, bool stop=true)
read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "rec".
uint16_t read_reg (uint8_t addr, uint8_t reg, uint8_t *rec, size_t size, bool stop=true)
Handler of read(uint8_t, uint8_t*, uint8_t, bool) to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave given by the "addr" address and copy them to "rec".
void enable (uint8_t addr, uint8_t rx_buff_len)
Configure the TWI buss to support slave operation. This function initialize the bus whit a given address and create a buffer to receive the bytes sent by the master.
void on_receive (fun_ptr_vd_u8 fun)
Configure the behavior of the slave when receive data from the master. This function will be executed after the reception of all the bytes. The input will be the number of bytes received.
uint8_t get_rx_buff (uint8_t idx)
Return the byte located on the "idx" position on the slave RX buffer.
void on_request (fun_ptr_vd_vd fun)
Configure the behavior of the slave when data is requested from the master. This function will be executed before send data to the master. The user need to prepare the response in this callback and prepare the TX slave buffer with the function send_response().
void send_response (uint8_t *tx_buff, uint8_t tx_buff_size)
This function is used to set and prepare the slave TX buffer before sending data to the master.
Static Public Member Functions
static TWI * get_instance (void)
Get this class instance.
static void delete_instance (void)
Deletes the actual instance. This action turns off the interface and reset its configurations.
Private Types
enum twi_state_t {
TWI_READY, TWI_MTX, TWI_MRX, TWI_STX,
TWI_SRX
}
TWI state machine states.
Private Member Functions
TWI (void)
TWI constructor.
uint8_t freq_sel (uint32_t xtal_cpu, uint32_t freq)
TWI baudrate expression.
void init (void)
Used internally to initialize the TWI bus (common to master and slave modes).
void start (void)
Used internally to start the TWI transaction or send a repeated start condition.
void stop (void)
Used internally to stop the TWI transaction.
void release_bus (void)
Used internally to release the bus.
void reply (bool ack)
Used internally to send ACK/NACK replies.
void state_machine (void)
Callback used to execute the TWI state machine on the ISR.
Static Private Member Functions
static void on_receive_callback (uint8_t last_rx_idx)
Internal slave on receive ISR callback.
static void on_request_callback (void)
Internal slave on request ISR callback.
Private Attributes
volatile twi_state_t _state
TWI state machine state.
volatile uint8_t _slarw
TWI slave address.
volatile uint8_t _error
TWI transaction error.
volatile bool _send_stop
TWI send stop flag.
volatile bool _rep_start
TWI send rep. start flag.
uint8_t *volatile _mx_buff
Master buffer.
volatile uint8_t _mx_buff_idx
Master buffer index.
volatile uint8_t _mx_buff_size
Master buffer size.
uint8_t *volatile _srx_buff
Slave RX buffer.
volatile uint8_t _srx_buff_idx
Slave RX buffer index.
volatile uint8_t _srx_buff_size
Slave RX buffer size.
uint8_t *volatile _stx_buff
Slave TX buffer.
volatile uint8_t _stx_buff_idx
Slave TX buffer index.
volatile uint8_t _stx_buff_size
Slave TX buffer size.
Static Private Attributes
static TWI * _inst = NULL
Device Singleton.
static fun_ptr_vd_u8 _user_on_receive
Slave on receive ISR callback.
static fun_ptr_vd_vd _user_on_request
Slave on request ISR callback.
Friends
void TWI_vect ()
Used to make available private SPI methods on the ISR.
Detailed Description
TWI bus general implementation.
Definition at line 19 of file twi.h.
Member Enumeration Documentation
twi_state_t
enum TWI::twi_state_t private
TWI state machine states.
Enumerator
TWI_READY
TWI bus available (operation finished).
TWI_MTX
TWI master on write mode.
TWI_MRX
TWI master in read mode.
TWI_STX
TWI slave on write mode.
TWI_SRX
TWI slave on read mode.
Definition at line 307 of file twi.h.
                  {
         TWI_READY,
         TWI_MTX,
         TWI_MRX,
         TWI_STX,
         TWI_SRX
     } twi_state_t;
Constructor & Destructor Documentation
TWI()
TWI::TWI (void) private
TWI constructor.
Definition at line 270 of file twi.cpp.
References _mx_buff, _srx_buff, _stx_buff, _user_on_receive, _user_on_request, fun_vd_u8_dummy(), and fun_vd_vd_dummy().
Referenced by get_instance().
              {
     _mx_buff = NULL;
     _srx_buff = NULL;
     _stx_buff = NULL;
     _user_on_receive = fun_vd_u8_dummy;
     _user_on_request = fun_vd_vd_dummy;
 }
Member Function Documentation
get_instance()
TWI * TWI::get_instance (void) static
Get this class instance.
Returns
Device singleton.
Definition at line 15 of file twi.cpp.
References _inst, and TWI().
{
     if (!_inst) _inst = new TWI();
     return _inst;
 }
delete_instance()
void TWI::delete_instance (void) static
Deletes the actual instance. This action turns off the interface and reset its configurations.
Definition at line 20 of file twi.cpp.
References _inst, and disable().
{
     if (!_inst) return;
     _inst->disable();
     delete _inst;
     _inst = NULL;
 }
disable()
void TWI::disable (void)
Disable the TWI bus and clean, if slave operation was used, the slave RX buffer.
Definition at line 28 of file twi.cpp.
References _BV, _srx_buff, _srx_buff_size, ATOMIC, and pin_write().
Referenced by delete_instance().
                       {
     // Disable TWI
     ATOMIC({
         // Disable slave (clear address)
         TWAR = 0x00;
         // Disable bus, interrupts and ACK generation
         TWCR &= ~(_BV(TWEN) | _BV(TWIE) | _BV(TWEA));
     });
     // Deactivate bus pins
     pin_write(SDA, false);
     pin_write(SCL, false);
     // Clear slave RX buffer (if any)
     if (_srx_buff_size > 0) {
         free(_srx_buff);
         _srx_buff = NULL;
         _srx_buff_size = 0;
     }
 }
set_clock()
void TWI::set_clock (uint16_t freq = TWI_DEF_FREQ_KHZ)
Set the SCL clock frequency.
Parameters
freq Desired bus frequency in KHz.
Definition at line 48 of file twi.cpp.
References ATOMIC, and freq_sel().
{
     // Calculate the new TWI clock
     uint8_t twbr = freq_sel(F_CPU, freq);
     // Set the new value
     ATOMIC({
         TWBR = twbr;
     })
 }
enable() [1/2]
void TWI::enable (void)
Configure the TWI bus to support master operation. This function initialize the bus with the default frequency (100KHz).
Definition at line 58 of file twi.cpp.
References _BV, ATOMIC, and init().
                      {
     // Initialize TWI state machine, bus pins and clock
     init();
     // Configure master
     ATOMIC({
         // Enable bus, interrupts and ACK generation
         TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWEA));
     });
 }
write() [1/2]
uint16_t TWI::write (uint8_t addr, uint8_t src, bool stop = true)
write(uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "src".
Parameters
addr Slave address.
src Source byte.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes written (msb) and error code (lsb). See write(uint8_t, uint8_t*, uint8_t, bool).
Definition at line 69 of file twi.cpp.
Referenced by read_reg(), TWI::Device::write(), and write_reg().
{
     return write(addr, &src, 1, stop);
 }
write() [2/2]
uint16_t TWI::write (uint8_t addr, uint8_t * src, size_t size, bool stop = true)
Write "size" bytes from "src" on the slave given by the "addr" address.
Parameters
addr Slave address.
src Pointer to byte source array.
size Number of bytes to send.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes written (msb) and error code (lsb).
Code Error
0 Succeed
1 Address sent, NACK received
2 Data sent, NACK received
3 Arbitration lost
4 Other TWI error (bus error, etc.)
5 No buffer available or size not supported
Definition at line 73 of file twi.cpp.
References _error, _mx_buff, _mx_buff_idx, _mx_buff_size, _send_stop, _slarw, _state, start(), stop(), TWI_ERR_NONE, TWI_MTX, and TWI_READY.
{
     // Check if the buffer is available
     if ((size == 0) || (src == NULL))
         return 0x0005;
     // Result aux.
     uint16_t result;
     // Wait until TWI is ready
     while (_state != TWI_READY);
     // Set TWI state machine
     _state = TWI_MTX;
     _error = TWI_ERR_NONE;
     _send_stop = stop;
     // Initialize master buffer vars.
     _mx_buff = src;
     _mx_buff_idx = 0;
     _mx_buff_size = size;
     // Build slave address
     _slarw = (addr << 1) | TW_WRITE;
     // Start TWI state machine
     start();
     // Wait until ready
     while (_state == TWI_MTX);
     // Get bytes transmitted
     result = (_mx_buff_idx << 8);
     // Handle errors
     switch (_error) {
         case TWI_ERR_NONE:      result |= 0x00;     break;
         case TW_MT_SLA_NACK:    result |= 0x01;     break;
         case TW_MT_DATA_NACK:   result |= 0x02;     break;
         case TW_MT_ARB_LOST:    result |= 0x03;     break;
         default:                result |= 0x04;     break;
     }
     // Return result
     return result;
 }
write_reg() [1/2]
uint16_t TWI::write_reg (uint8_t addr, uint8_t reg, uint8_t src, bool stop = true)
write_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "src".
Parameters
addr Slave address.
reg Slave register address.
src Source byte.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes written (msb) and error code (lsb). See write(uint8_t, uint8_t*, uint8_t, bool).
Definition at line 109 of file twi.cpp.
Referenced by TWI::Device::write_reg().
{
     return write_reg(addr, reg, &src, 1, stop);
 }
write_reg() [2/2]
uint16_t TWI::write_reg (uint8_t addr, uint8_t reg, uint8_t * src, size_t size, bool stop = true)
Handler of write(uint8_t, uint8_t*, uint8_t, bool) to simplify the process of write data into a given register on the slave device. It writes "size" bytes from "src" to the "reg" register on the slave given by the "addr" address.
Parameters
addr Slave address.
reg Slave register address.
src Pointer to source byte array.
size Number of bytes to send.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes written (msb) and error code (lsb). See write(uint8_t, uint8_t*, uint8_t, bool).
Definition at line 113 of file twi.cpp.
References write().
{
     // Check if the buffer is available
     if ((size == 0) || (src == NULL))
         return 0x05;
     // Put the "reg" and "src" in one auxiliary array and send
     uint8_t* reg_src = (uint8_t*) malloc((size + 1));
     memcpy(reg_src, &reg, 1);
     memcpy((reg_src + 1), src, size);
     // Write the register
     uint8_t result = write(addr, reg_src, (size + 1), stop);
     // Free the auxiliary space
     free(reg_src);
     // Return the result
     return result;
 }
read() [1/2]
uint16_t TWI::read (uint8_t addr, uint8_t * rec, bool stop = true)
read(uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "rec".
Parameters
addr Slave address.
rec Receive byte.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes read (msb) and error code (lsb). See read(uint8_t, uint8_t*, uint8_t, bool).
Definition at line 130 of file twi.cpp.
Referenced by TWI::Device::read(), and read_reg().
{
     return read(addr, rec, 1, stop);
 }
read() [2/2]
uint16_t TWI::read (uint8_t addr, uint8_t * rec, size_t size, bool stop = true)
Read "size" bytes from the slave given by the "addr" address and copy them to "rec".
Parameters
addr Slave address.
rec Pointer to received byte array.
size Number of bytes to read.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes read (msb) and error code (lsb).
Code Error
0 Succeed
1 Address sent, NACK received
3 Arbitration lost
4 Other TWI error (bus error, etc.)
5 No buffer available or size not supported
Definition at line 134 of file twi.cpp.
References _error, _mx_buff, _mx_buff_idx, _mx_buff_size, _send_stop, _slarw, _state, start(), stop(), TWI_ERR_NONE, TWI_MRX, and TWI_READY.
{
     // Check if the buffer is available
     if ((size == 0) || (rec == NULL))
         return 0x0005;
     // Result aux.
     uint16_t result;
     // Wait until TWI is ready
     while (_state != TWI_READY);
     // Set TWI state machine
     _state = TWI_MRX;
     _error = TWI_ERR_NONE;
     _send_stop = stop;
     // Initialize master buffer vars.
     _mx_buff = rec;
     _mx_buff_idx = 0;
     _mx_buff_size = size - 1;       // See note *(2)
     // Build slave address
     _slarw = (addr << 1) | TW_READ;
     // Start TWI state machine
     start();
     // Wait until ready
     while (_state == TWI_MRX);
     // Get bytes transmitted
     result = (_mx_buff_idx << 8);
     // Handle errors
     switch (_error) {
         case TWI_ERR_NONE:      result |= 0x00;     break;
         case TW_MR_SLA_NACK:    result |= 0x01;     break;
         case TW_MR_ARB_LOST:    result |= 0x03;     break;
         default:                result |= 0x04;     break;
     }
     // Return result
     return result;
 }
read_reg() [1/2]
uint16_t TWI::read_reg (uint8_t addr, uint8_t reg, uint8_t * rec, bool stop = true)
read_reg(uint8_t, uint8_t, uint8_t*, uint8_t, bool) handler for 1 byte "rec".
Parameters
addr Slave address.
reg Slave register address.
rec Receive byte.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes read (msb) and error code (lsb). See read(uint8_t, uint8_t*, uint8_t, bool).
Definition at line 169 of file twi.cpp.
Referenced by TWI::Device::read_reg().
{
     return read_reg(addr, reg, rec, 1, stop);
 }
read_reg() [2/2]
uint16_t TWI::read_reg (uint8_t addr, uint8_t reg, uint8_t * rec, size_t size, bool stop = true)
Handler of read(uint8_t, uint8_t*, uint8_t, bool) to simplify the process of read data from a given register on the slave device. It reads "size" bytes from the "reg" register on the slave given by the "addr" address and copy them to "rec".
Parameters
addr Slave address.
reg Slave register address.
rec Pointer to received byte array.
size Number of bytes to read.
stop Used to send a stop condition after the task is completed.
Returns
Number of bytes read (msb) and error code (lsb). See read(uint8_t, uint8_t*, uint8_t, bool).
Definition at line 173 of file twi.cpp.
References read(), and write().
{
     // Locate the register
     uint16_t result = write(addr, &reg, 1, false);
     // If an error is detected, return
     if ((result & 0x0F) != 0)
         return result;
     // Read bytes
     result = read(addr, rec, size, stop);
     // Return the result
     return result;
 }
enable() [2/2]
void TWI::enable (uint8_t addr, uint8_t rx_buff_len)
Configure the TWI buss to support slave operation. This function initialize the bus whit a given address and create a buffer to receive the bytes sent by the master.
Parameters
addr Slave address.
rx_buff_len Size of the slave RX buffer.
Definition at line 225 of file twi.cpp.
References _BV, _srx_buff, _srx_buff_size, _user_on_receive, _user_on_request, ATOMIC, fun_vd_u8_dummy(), fun_vd_vd_dummy(), and init().
{
     // Check the desired buffer length
     if (rx_buff_size == 0)
         return;
     // Set the slave RX buffer
     _srx_buff_size = rx_buff_size;
     _srx_buff = (uint8_t *)malloc((rx_buff_size * sizeof(uint8_t)));
     // Set callbacks
     _user_on_receive = fun_vd_u8_dummy;
     _user_on_request = fun_vd_vd_dummy;
     // Initialize state machine, pins and clock
     init();
     // Configure slave
     ATOMIC({
         // Set TWI address (Activate slave mode)
         TWAR = addr << 1;
         // Enable bus, interrupts and ACK generation
         TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWEA));
     });
 }
on_receive()
void TWI::on_receive (fun_ptr_vd_u8 fun)
Configure the behavior of the slave when receive data from the master. This function will be executed after the reception of all the bytes. The input will be the number of bytes received.
Parameters
fun On receive ISR callback.
Definition at line 247 of file twi.cpp.
References _user_on_receive, and fun_vd_u8_dummy().
{
     _user_on_receive = (fun)? fun : fun_vd_u8_dummy;
 }
get_rx_buff()
uint8_t TWI::get_rx_buff (uint8_t idx)
Return the byte located on the "idx" position on the slave RX buffer.
Parameters
idx Index on the slave RX buffer.
Returns
Byte.
Definition at line 251 of file twi.cpp.
References _srx_buff.
{
     return _srx_buff[idx];
 }
on_request()
void TWI::on_request (fun_ptr_vd_vd fun)
Configure the behavior of the slave when data is requested from the master. This function will be executed before send data to the master. The user need to prepare the response in this callback and prepare the TX slave buffer with the function send_response().
Parameters
fun On request ISR callback.
Definition at line 256 of file twi.cpp.
References _user_on_request, and fun_vd_vd_dummy().
{
     _user_on_request = (fun)? fun : fun_vd_vd_dummy;
 }
send_response()
void TWI::send_response (uint8_t * tx_buff, uint8_t tx_buff_size)
This function is used to set and prepare the slave TX buffer before sending data to the master.
Parameters
tx_buff Pointer to source byte array.
tx_buff_size Number of bytes to send.
Definition at line 260 of file twi.cpp.
References _stx_buff, and _stx_buff_size.
{
     // Check if the buffer is available
     if ((tx_buff == NULL) || (tx_buff_size == 0))
         return;
     // Set slave TX buffer
     _stx_buff = tx_buff;
     _stx_buff_size = tx_buff_size;
 }
freq_sel()
uint8_t TWI::freq_sel (uint32_t xtal_cpu, uint32_t freq) private
TWI baudrate expression.
Parameters
xtal_cpu System clock in MHz.
freq SCL frequency in KHz.
Returns
TWBR value.
Definition at line 279 of file twi.cpp.
Referenced by init(), and set_clock().
{
     return (uint8_t)((xtal_cpu / (2UL * freq * 1000UL)) - 8UL);
 }
init()
void TWI::init (void) private
Used internally to initialize the TWI bus (common to master and slave modes).
Definition at line 284 of file twi.cpp.
References _rep_start, _send_stop, _state, ATOMIC, freq_sel(), pin_write(), TWI_DEF_FREQ_KHZ, and TWI_READY.
Referenced by enable().
                    {
     // Set initial TWI SM state
     _state = TWI_READY;
     _send_stop = true;
     _rep_start = false;
     // Activate pullups for TWI
     pin_write(SDA, true);
     pin_write(SCL, true);
     // Configure basics
     ATOMIC({
         // Clean TWI control register
         TWCR = 0x00;
         // Initialize TWI prescaler as 1
         TWBR = 0x00;
         // Set default frequency
         TWBR = freq_sel(F_CPU, TWI_DEF_FREQ_KHZ);
     });
 }
start()
void TWI::start (void) private
Used internally to start the TWI transaction or send a repeated start condition.
Definition at line 303 of file twi.cpp.
References _BV, _rep_start, and _slarw.
Referenced by read(), and write().
                     {
     if (_rep_start) {
         // Clear rep_start flag.
         _rep_start = false;
         // Write slave address on data register
         do {
             TWDR = _slarw;
         } while (TWCR & _BV(TWWC));     // Handle collisions
         // Enable interruptions and send address (start already set, see *(1)).
         TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWINT) | _BV(TWEA));
     } else {
         // Send start condition
         TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWINT) | _BV(TWEA) | _BV(TWSTA));
     }
 }
stop()
void TWI::stop (void) private
Used internally to stop the TWI transaction.
Definition at line 319 of file twi.cpp.
References _BV, _state, and TWI_READY.
Referenced by read(), state_machine(), and write().
                    {
     // Transmit stop condition
     TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWINT) | _BV(TWEA) | _BV(TWSTO));
     // Wait to stop condition to be executed
     loop_until_bit_is_clear(TWCR, TWSTO);
     // Update TWI SM state
     _state = TWI_READY;
 }
release_bus()
void TWI::release_bus (void) private
Used internally to release the bus.
Definition at line 328 of file twi.cpp.
References _BV, _state, and TWI_READY.
Referenced by state_machine().
{
     // Release bus
     TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWINT) | _BV(TWEA));
     // Update TWI SM state
     _state = TWI_READY;
 }
reply()
void TWI::reply (bool ack) private
Used internally to send ACK/NACK replies.
Parameters
ack ACK/NACK selector
Definition at line 335 of file twi.cpp.
References _BV.
Referenced by state_machine().
{
     if (ack) {
         TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWINT) | _BV(TWEA));
     } else {
         TWCR = (_BV(TWEN) | _BV(TWIE) | _BV(TWINT));
     }
 }
on_receive_callback()
void TWI::on_receive_callback (uint8_t last_rx_idx) static private
Internal slave on receive ISR callback.
Definition at line 344 of file twi.cpp.
References _user_on_receive.
Referenced by state_machine().
{
     _user_on_receive(last_rx_idx);
 }
on_request_callback()
void TWI::on_request_callback (void) static private
Internal slave on request ISR callback.
Definition at line 348 of file twi.cpp.
References _user_on_request.
Referenced by state_machine().
{
     _user_on_request();
 }
state_machine()
void TWI::state_machine (void) inline private
Callback used to execute the TWI state machine on the ISR.
Definition at line 353 of file twi.cpp.
References _BV, _error, _mx_buff, _mx_buff_idx, _mx_buff_size, _rep_start, _send_stop, _slarw, _srx_buff, _srx_buff_idx, _srx_buff_size, _state, _stx_buff, _stx_buff_idx, _stx_buff_size, on_receive_callback(), on_request_callback(), release_bus(), reply(), stop(), TWI_READY, TWI_SRX, and TWI_STX.
Referenced by ISR().
{
     /* TWI state machine */
     switch (TW_STATUS) {
         /****************************************
          * MASTER:
          * 1.- Start / Rep. Start:
          *      1.1.- Copy slave address to buffer.
          *      1.2.- Send address (expect ACK).
          ***************************************/
         case TW_START:
         case TW_REP_START: {
             TWDR = _slarw;
             reply(true);
         } break;
         /****************************************
          * MASTER TRANSMITTER:
          * 1.- Slave address/data sent, ACK received:
          *      1.1.- If there's data to send (idx < len):
          *          1.1.1.- Copy byte to buffer.
          *          1.1.2.- Send byte (expect ACK).
          *      1.2.- Otherwise, go to "Master End Transaction Handler"
          ***************************************/
         case TW_MT_SLA_ACK:
         case TW_MT_DATA_ACK: {
             if (_mx_buff_idx < _mx_buff_size) {
                 TWDR = _mx_buff[_mx_buff_idx++];
                 reply(true);
             } else {
                 goto _tw_meth;
             }
         } break;
         /****************************************
          * MASTER RECEIVER:
          * 1.- Slave address sent, ACK received:
          *      1.1.- If data is expected (idx < len), send ACK (prepare bus for reception).
          *      1.2.- Otherwise, send NACK.
          ***************************************/
         case TW_MR_SLA_ACK: {
             _tw_mrgdh:      // Master Receiver Get Data Handler
             if (_mx_buff_idx < _mx_buff_size) {
                 reply(true);
             } else {
                 reply(false);
             }
         } break;
         /* 2.- Slave data received, ACK sent:
          *      2.1.- Copy byte from buffer.
          *      2.2.- Go to "Master Receiver Get Data Handler" (MR 1.-)
          ***************************************/
         case TW_MR_DATA_ACK: {
             _mx_buff[_mx_buff_idx++] = TWDR;
             goto _tw_mrgdh;
         } break;
         /* 3.- Slave data received, NACK sent:
          *      3.1.- Copy final byte from buffer.
          *      3.2.- Go to "Master End Transaction Handler"
          ***************************************/
         case TW_MR_DATA_NACK: {
             _mx_buff[_mx_buff_idx] = TWDR;
             goto _tw_meth;
         } break;
         /****************************************
          * If "Bus Error" or "Slave address sent, NACK received" (MT/MR)
          * or "Data sent, NACK received" (MT):
          *      1.- Save error.
          *      2.- Stop transaction.
          ***************************************/
         case TW_MT_SLA_NACK:
         case TW_MR_SLA_NACK:
         case TW_MT_DATA_NACK: {
             _error = TW_STATUS;
             stop();
         } break;
         /****************************************
          * If "Arbitration lost" (MT/MR):
          *      1.- Save error.
          *      2.- Release bus.
          ***************************************/
         case TW_MT_ARB_LOST: {
             _error = TW_STATUS;
             release_bus();
         } break;
         /****************************************
          * SLAVE TRANSMITTER
          * 1.- Adressed / Arbitration lost, ACK sent:
          *      1.1.- Enter slave TX mode (STX).
          *      1.2.- Reset TX data size and index.
          *      1.3.- Execute slave TX event: Must prepare data to send using
          *          twi_slave_write(uint8_t* data, size_t size). If data is
          *          not set, prepare to send 0x00.
          *      1.4.- Go to "Slave Transmitter Send Data Handler" (ST 2.-)
          ***************************************/
         case TW_ST_SLA_ACK:
         case TW_ST_ARB_LOST_SLA_ACK: {
             _state = TWI::TWI_STX;
             _stx_buff_idx = 0;
             _stx_buff_size = 0;
             on_request_callback();
             if (_stx_buff_size == 0) {
                 _stx_buff_size = 1;
                 *_stx_buff = 0x00;
             }
             goto _tw_stsdh;
         } break;
         /* 2.- Data sent, ACK received:
          *      2.1.- Put byte on buffer.
          *      2.3.- If there's data to send (idx < len), send byte (expect ACK).
          *      2.4.- Otherwise, send byte (expect NACK).
          ***************************************/
         case TW_ST_DATA_ACK: {
             _tw_stsdh:      // Slave Transmitter Send Data Handler
             TWDR = _stx_buff[_stx_buff_idx++];
             if (_stx_buff_idx < _stx_buff_size) {
                 reply(true);
             } else {
                 reply(false);
             }
         } break;
         /* 3.- Data sent / Last data sent, NACK received:
          *      3.1.- ACK future responses.
          *      3.2.- Leave slave TX state.
          ***************************************/
         case TW_ST_DATA_NACK:
         case TW_ST_LAST_DATA: {
             reply(true);
             _state = TWI::TWI_READY;
         } break;
         /****************************************
          * SLAVE RECEIVER
          * 1.- Adressed / Arbitration lost, ACK sent:
          *      1.1.- Enter slave RX mode (SRX).
          *      1.2.- Reset RX data index.
          *      1.3.- Prepare line for reception (send ACK).
          ***************************************/
         case TW_SR_SLA_ACK:
         case TW_SR_GCALL_ACK:
         case TW_SR_ARB_LOST_SLA_ACK:
         case TW_SR_ARB_LOST_GCALL_ACK: {
             _state = TWI::TWI_SRX;
             _srx_buff_idx = 0;
             reply(true);
         } break;
         /* 2.- Data received, ACK sent:
          *      2.1.- If there's space on buffer:
          *          2.1.1.- Copy byte from buffer.
          *          2.1.2.- Send ACK (expect more data).
          *      2.2.- Otherwise, send NACK.
          ***************************************/
         case TW_SR_DATA_ACK:
         case TW_SR_GCALL_DATA_ACK: {
             if (_srx_buff_idx < _srx_buff_size) {
                 _srx_buff[_srx_buff_idx++] = TWDR;
                 reply(true);
             } else {
                 reply(false);
             }
         } break;
         /* 3.- Data received, NACK sent:
          *      3.1.- Send NACK.
          ***************************************/
         case TW_SR_DATA_NACK:
         case TW_SR_GCALL_DATA_NACK: {
             reply(false);
         } break;
         /* 4.- Stop / Rep. start received:
          *      4.1.- Release bus.
          *      4.2.- If there's space, put a termination value on Rx buffer ('\0').
          *      4.3.- Execute slave RX event: Must handle input data using
          *          twi_slave_rx_event(uint8_t last_idx). Where last_idx points the
          *          last index used on the RX buffer.
          *      4.4.- Reset RX buffer index.
          ***************************************/
         case TW_SR_STOP: {
             release_bus();
             if (_srx_buff_idx < _srx_buff_size) {
                 _srx_buff[_srx_buff_idx] = '\0';
             }
             on_receive_callback(_srx_buff_idx);
             _srx_buff_idx = 0;
         } break;
         /****************************************
          * If "Slave address sent, NACK received" (MT/MR)
          * or "Data sent, NACK received" (MT):
          *      1.- Save error.
          *      2.- Stop transaction.
          ***************************************/
         case TW_BUS_ERROR: {
             _error = TW_STATUS;
             stop();
         } break;
         /****************************************
          * If "No state information" (any):
          *      1.- Do nothing.
          ***************************************/
         case TW_NO_INFO: {
         } break;
     }
     /* End of ISR */
     return;
     /********************************************
      * Master End Transaction Handler
      *      1.1.- If send_stop flag is active:
      *          1.1.1.- Stop transaction.
      *      1.2.- Otherwise, prepare rep. start.
      *          1.2.1.- Put rep_start flag active.
      *          1.2.2.- Send start but disable interruptions*(1).
      *          1.2.3.- Set TWI state machine as ready.
      ********************************************/
     _tw_meth: {
         if (_send_stop) {
             stop();
         } else {
             _rep_start = true;
             TWCR = _BV(TWEN) | _BV(TWINT) | _BV(TWSTA);
             _state = TWI::TWI_READY;
         }
     } return;
 }
Friends And Related Function Documentation
TWI_vect
void TWI_vect () friend
Used to make available private SPI methods on the ISR.
Member Data Documentation
_inst
TWI * TWI::_inst = NULL static private
Device Singleton.
Device singleton initialization.
Definition at line 299 of file twi.h.
Referenced by delete_instance(), and get_instance().
_state
volatile twi_state_t TWI::_state private
TWI state machine state.
Definition at line 316 of file twi.h.
Referenced by init(), read(), release_bus(), state_machine(), stop(), and write().
_slarw
volatile uint8_t TWI::_slarw private
TWI slave address.
Definition at line 317 of file twi.h.
Referenced by read(), start(), state_machine(), and write().
_error
volatile uint8_t TWI::_error private
TWI transaction error.
Definition at line 318 of file twi.h.
Referenced by read(), state_machine(), and write().
_send_stop
volatile bool TWI::_send_stop private
TWI send stop flag.
Definition at line 319 of file twi.h.
Referenced by init(), read(), state_machine(), and write().
_rep_start
volatile bool TWI::_rep_start private
TWI send rep. start flag.
Definition at line 320 of file twi.h.
Referenced by init(), start(), and state_machine().
_mx_buff
uint8_t* volatile TWI::_mx_buff private
Master buffer.
Definition at line 321 of file twi.h.
Referenced by read(), state_machine(), TWI(), and write().
_mx_buff_idx
volatile uint8_t TWI::_mx_buff_idx private
Master buffer index.
Definition at line 322 of file twi.h.
Referenced by read(), state_machine(), and write().
_mx_buff_size
volatile uint8_t TWI::_mx_buff_size private
Master buffer size.
Definition at line 323 of file twi.h.
Referenced by read(), state_machine(), and write().
_srx_buff
uint8_t* volatile TWI::_srx_buff private
Slave RX buffer.
Definition at line 324 of file twi.h.
Referenced by disable(), enable(), get_rx_buff(), state_machine(), and TWI().
_srx_buff_idx
volatile uint8_t TWI::_srx_buff_idx private
Slave RX buffer index.
Definition at line 325 of file twi.h.
Referenced by state_machine().
_srx_buff_size
volatile uint8_t TWI::_srx_buff_size private
Slave RX buffer size.
Definition at line 326 of file twi.h.
Referenced by disable(), enable(), and state_machine().
_stx_buff
uint8_t* volatile TWI::_stx_buff private
Slave TX buffer.
Definition at line 327 of file twi.h.
Referenced by send_response(), state_machine(), and TWI().
_stx_buff_idx
volatile uint8_t TWI::_stx_buff_idx private
Slave TX buffer index.
Definition at line 328 of file twi.h.
Referenced by state_machine().
_stx_buff_size
volatile uint8_t TWI::_stx_buff_size private
Slave TX buffer size.
Definition at line 329 of file twi.h.
Referenced by send_response(), and state_machine().
_user_on_receive
fun_ptr_vd_u8 TWI::_user_on_receive static private
Slave on receive ISR callback.
Definition at line 330 of file twi.h.
Referenced by enable(), on_receive(), on_receive_callback(), and TWI().
_user_on_request
fun_ptr_vd_vd TWI::_user_on_request static private
Slave on request ISR callback.
Definition at line 331 of file twi.h.
Referenced by enable(), on_request(), on_request_callback(), and TWI().
The documentation for this class was generated from the following files:
hardware/twi.h
hardware/twi.cpp