AVRLibs: hardware/gpio.h File Reference
gpio.h File Reference
General Purpose Digital I/O library.
#include <hardware/atomic.h>
#include <hardware/board.h>
Classes
struct gpio_reg_t
Pin control registers.
Macros
#define GPIO_PORT(brd_val) ((brd_val >> 8) & 0xFF)
Return the port control register address from a given board port/pin value.
#define GPIO_PORT_MASK(port) (port & 0xFF)
Return the port available pins mask from a given board port value.
#define GPIO_PIN_BIT(pin) (pin & 0xFF)
Return the pin bit position from a given board pin value.
#define GPIO_PIN_MASK(pin) _BV(GPIO_PIN_BIT(pin))
Return the pin mask from a given board pin value.
Enumerations
enum gpio_mode_t { INPUT, OUTPUT, INPUT_PULLUP }
GPIO operation modes.
Functions
gpio_reg_t * port_sfr (ports_t port)
Return the port control registers from a given board port value.
gpio_reg_t * pin_sfr (pins_t pin)
Return the port control registers from a given board pin value.
void pin_mode (pins_t pin, gpio_mode_t mode)
Initialize a pin with a certain mode (INPUT, INPUT_PULLUP, OUTPUT).
void pin_write (pins_t pin, bool value)
Write a digital value on the selected pin.
void pin_toggle (pins_t pin)
Toggle the pin value.
bool pin_read (pins_t pin)
Return the pin value.
void port_mode (ports_t port, uint8_t mask, gpio_mode_t mode)
Initialize a port with a certain mode (INPUT, INPUT_PULLUP, OUTPUT).
void port_write (ports_t port, uint8_t value)
Write a given value over a port (only on the pins selected as outputs).
void port_toggle (ports_t port)
Toggle the state of the pins selected as output on the given port.
uint8_t port_read (ports_t port)
Return the value of the pins selected as input on the given port.
Detailed Description
General Purpose Digital I/O library.
#include "hardware/gpio.h"
Definition in file gpio.h.
Class Documentation
gpio_reg_t
struct gpio_reg_t
Pin control registers.
Definition at line 49 of file gpio.h.
Class Members
volatile uint8_t PIN Pin input register (Read pin value)
volatile uint8_t DDR Pin direction register (I/O selection)
volatile uint8_t PORT PORT register (Set pin value)
Macro Definition Documentation
GPIO_PORT
#define GPIO_PORT (brd_val) ((brd_val >> 8) & 0xFF)
Return the port control register address from a given board port/pin value.
Parameters
brd_val Board port/pin value.
Returns
Port control register.
Definition at line 20 of file gpio.h.
Referenced by get_int_pc_from_pin(), pin_sfr(), and port_sfr().
GPIO_PORT_MASK
#define GPIO_PORT_MASK (port) (port & 0xFF)
Return the port available pins mask from a given board port value.
Parameters
port Board port value.
Returns
Available pins mask.
Definition at line 28 of file gpio.h.
Referenced by port_mode(), port_read(), port_toggle(), and port_write().
GPIO_PIN_BIT
#define GPIO_PIN_BIT (pin) (pin & 0xFF)
Return the pin bit position from a given board pin value.
Parameters
pin Board pin value.
Returns
Pin bit position.
Definition at line 35 of file gpio.h.
Referenced by get_int_pc_from_pin().
GPIO_PIN_MASK
#define GPIO_PIN_MASK (pin) _BV(GPIO_PIN_BIT(pin))
Return the pin mask from a given board pin value.
Parameters
pin Board pin value.
Returns
Pin bit mask.
Definition at line 42 of file gpio.h.
Referenced by pin_mode(), pin_read(), pin_toggle(), and pin_write().
Enumeration Type Documentation
gpio_mode_t
enum gpio_mode_t
GPIO operation modes.
Enumerator
INPUT
Pin configured as input (DDR(0))
OUTPUT
Pin configured as output (DDR(1))
INPUT_PULLUP
Pin configured as input with pullup (DDR(0), PORT(1))
Definition at line 59 of file gpio.h.
              {
     INPUT,
     OUTPUT,
     INPUT_PULLUP
 } gpio_mode_t;
Function Documentation
port_sfr()
gpio_reg_t* port_sfr (ports_t port) inline
Return the port control registers from a given board port value.
Parameters
port Board port value.
Returns
Port control registers.
Definition at line 71 of file gpio.h.
References GPIO_PORT.
Referenced by port_mode(), port_read(), port_toggle(), and port_write().
{
     return (gpio_reg_t*)GPIO_PORT(port);
 }
pin_sfr()
gpio_reg_t* pin_sfr (pins_t pin) inline
Return the port control registers from a given board pin value.
Parameters
pin Board pin value.
Returns
Port control registers.
Definition at line 80 of file gpio.h.
References GPIO_PORT.
Referenced by pin_mode(), pin_read(), pin_toggle(), and pin_write().
{
     return (gpio_reg_t*)GPIO_PORT(pin);
 }
pin_mode()
void pin_mode (pins_t pin, gpio_mode_t mode) inline
Initialize a pin with a certain mode (INPUT, INPUT_PULLUP, OUTPUT).
Parameters
pin Board pin value.
mode Pin operation mode.
Definition at line 91 of file gpio.h.
References ATOMIC, gpio_reg_t::DDR, GPIO_PIN_MASK, INPUT, INPUT_PULLUP, pin_sfr(), and gpio_reg_t::PORT.
Referenced by SPI::Device::Device(), DRV2605::DRV2605(), and SPI::enable().
{
     if (pin == NO_PIN)
         return;
     ATOMIC({
         if (mode == INPUT) {
             pin_sfr(pin)->DDR &= ~GPIO_PIN_MASK(pin);
         } else if (mode == INPUT_PULLUP) {
             pin_sfr(pin)->DDR &= ~GPIO_PIN_MASK(pin);
             pin_sfr(pin)->PORT |= GPIO_PIN_MASK(pin);
         } else {
             pin_sfr(pin)->DDR |= GPIO_PIN_MASK(pin);
         }
     });
 }
pin_write()
void pin_write (pins_t pin, bool value) inline
Write a digital value on the selected pin.
Parameters
pin Board pin value.
value State of the pin: on(true), off(false).
Definition at line 111 of file gpio.h.
References ATOMIC, GPIO_PIN_MASK, pin_sfr(), and gpio_reg_t::PORT.
Referenced by SPI::Device::begin_transaction(), SPI::Device::Device(), TWI::disable(), SPI::enable(), SPI::Device::end_transaction(), TWI::init(), DRV2605::set_active_mode(), and DRV2605::set_standby_mode().
{
     if (pin == NO_PIN)
         return;
     ATOMIC({
         if (value) {
             pin_sfr(pin)->PORT |= GPIO_PIN_MASK(pin);
         } else {
             pin_sfr(pin)->PORT &= ~GPIO_PIN_MASK(pin);
         }
     });
 }
pin_toggle()
void pin_toggle (pins_t pin) inline
Toggle the pin value.
Parameters
pin Board pin value.
Definition at line 127 of file gpio.h.
References ATOMIC, GPIO_PIN_MASK, gpio_reg_t::PIN, and pin_sfr().
{
     if (pin == NO_PIN)
         return;
     ATOMIC({
         pin_sfr(pin)->PIN |= GPIO_PIN_MASK(pin);
     });
 }
pin_read()
bool pin_read (pins_t pin) inline
Return the pin value.
Parameters
pin Board pin value.
Returns
Pin state: on(true), off(false).
Definition at line 140 of file gpio.h.
References GPIO_PIN_MASK, and pin_sfr().
Referenced by int_pc_attach(), and SPI::on_request_callback().
{
     if (pin == NO_PIN)
         return false;
     return ((pin_sfr(pin)->PIN & GPIO_PIN_MASK(pin)) != 0);
 }
port_mode()
void port_mode (ports_t port, uint8_t mask, gpio_mode_t mode) inline
Initialize a port with a certain mode (INPUT, INPUT_PULLUP, OUTPUT).
Parameters
port Board port value.
mask Pins to be configured.
mode Pins operation mode.
Definition at line 154 of file gpio.h.
References ATOMIC, gpio_reg_t::DDR, GPIO_PORT_MASK, INPUT, INPUT_PULLUP, gpio_reg_t::PORT, and port_sfr().
{
     if (port == NO_PORT)
         return;
     gpio_reg_t* sfr = port_sfr(port);
     ATOMIC({
         mask = GPIO_PORT_MASK(port) & mask;
         if (mode == INPUT) {
             sfr->DDR &= ~mask;
         } else if (mode == INPUT_PULLUP) {
             sfr->DDR &= ~mask;
             sfr->PORT |= mask;
         } else {
             sfr->DDR |= mask;
         }
     });
 }
port_write()
void port_write (ports_t port, uint8_t value) inline
Write a given value over a port (only on the pins selected as outputs).
Parameters
port Board port value.
value Pin values: on(1), off(0).
Definition at line 177 of file gpio.h.
References ATOMIC, gpio_reg_t::DDR, GPIO_PORT_MASK, gpio_reg_t::PORT, and port_sfr().
{
     if (port == NO_PORT)
         return;
     gpio_reg_t* sfr = port_sfr(port);
     ATOMIC({
         value &= GPIO_PORT_MASK(port);
         value = ((sfr->PORT & ~sfr->DDR) | (value & sfr->DDR));
         sfr->PORT = value;
     });
 }
port_toggle()
void port_toggle (ports_t port) inline
Toggle the state of the pins selected as output on the given port.
Parameters
port Board port value.
Definition at line 193 of file gpio.h.
References ATOMIC, gpio_reg_t::DDR, GPIO_PORT_MASK, gpio_reg_t::PIN, and port_sfr().
{
     if (port == NO_PORT)
         return;
     gpio_reg_t* sfr = port_sfr(port);
     uint8_t     mask = GPIO_PORT_MASK(port);
     ATOMIC({
         mask &= sfr->DDR;
         sfr->PIN |= mask;
     });
 }
port_read()
uint8_t port_read (ports_t port) inline
Return the value of the pins selected as input on the given port.
Parameters
port Board port value.
Returns
Port state: on(1), off(0).
Definition at line 210 of file gpio.h.
References gpio_reg_t::DDR, GPIO_PORT_MASK, gpio_reg_t::PIN, and port_sfr().
{
     if (port == NO_PORT)
         return 0x00;
     gpio_reg_t* sfr = port_sfr(port);
     return ((sfr->PIN & GPIO_PORT_MASK(port)) & ~sfr->DDR);
 }