AVRLibs: hardware/int_pc.cpp File Reference
int_pc.cpp File Reference
Pin change interrupt library.
#include <hardware/int_pc.h>
Classes
struct int_pc_t
Structure that holds all the pin-change interrupt info for a given port.
struct int_pc_pin_t
Structure that holds all the pin-change interrupt info for a given pin.
Macros
#define INT_PC_ISR(vect, int_pc, pcmsk, input)
Used to simplify the pin change interrupt ISR definition.
Functions
int_pc_pin_t * get_int_pc_from_pin (pins_t pin)
Private function. Returns the pin-change interrupt info.
bool int_pc_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable a pin change interrupt and attach its ISR callback function.
void int_pc_detach (pins_t pin)
Disable a pin change interrupt and detach its ISR callback function.
Detailed Description
Pin change interrupt library.
Definition in file int_pc.cpp.
Class Documentation
int_pc_t
struct int_pc_t
Structure that holds all the pin-change interrupt info for a given port.
Definition at line 36 of file int_pc.cpp.
Class Members
uint8_t rising Port interrupt on rising mask.
uint8_t falling Port interrupt on falling mask.
volatile uint8_t old_state Port old state.
volatile fun_ptr_vd_vd callbacks[8] Port pin change interrupt callbacks.
int_pc_pin_t
struct int_pc_pin_t
Structure that holds all the pin-change interrupt info for a given pin.
Definition at line 48 of file int_pc.cpp.
Class Members
uint8_t idx_pin Pin position in the port.
uint8_t idx_int Interrupt number.
volatile uint8_t * pcicr Interrupt enable register.
volatile uint8_t * pcmsk Interrupt mask register.
int_pc_t * config Pin change port configuration.
Macro Definition Documentation
INT_PC_ISR
#define INT_PC_ISR (vect, int_pc, pcmsk, input)
Value:
ISR(vect) {                                                                     \
        uint8_t new_state = input;                                                  \
        uint8_t pin_trigs = (pcmsk & (int_pc.old_state ^ new_state) & ((int_pc.rising & new_state) | (int_pc.falling & ~new_state))); \
        int_pc.old_state = new_state;                                               \
        if ((pin_trigs & _BV(0)) != 0) int_pc.callbacks[0]();                       \
        if ((pin_trigs & _BV(1)) != 0) int_pc.callbacks[1]();                       \
        if ((pin_trigs & _BV(2)) != 0) int_pc.callbacks[2]();                       \
        if ((pin_trigs & _BV(3)) != 0) int_pc.callbacks[3]();                       \
        if ((pin_trigs & _BV(4)) != 0) int_pc.callbacks[4]();                       \
        if ((pin_trigs & _BV(5)) != 0) int_pc.callbacks[5]();                       \
        if ((pin_trigs & _BV(6)) != 0) int_pc.callbacks[6]();                       \
        if ((pin_trigs & _BV(7)) != 0) int_pc.callbacks[7]();                       \
    }
Used to simplify the pin change interrupt ISR definition.
Parameters
vect ISR vector.
int_pc Pin-change interrupt configuration.
pcmsk Pin-change interrupt enable register.
input Pin-change interrupt port input.
Definition at line 15 of file int_pc.cpp.
Function Documentation
get_int_pc_from_pin()
int_pc_pin_t * get_int_pc_from_pin (pins_t pin)
Private function. Returns the pin-change interrupt info.
Prepare all pin-change interrupt ISRs
Parameters
pin Board pin value.
Returns
Pin change interrupt info int_pc_pin_t.
Definition at line 128 of file int_pc.cpp.
References int_pc_pin_t::config, GPIO_PIN_BIT, GPIO_PORT, int_pc_pin_t::idx_int, int_pc_pin_t::idx_pin, int_pc_pin_t::pcicr, and int_pc_pin_t::pcmsk.
Referenced by int_pc_attach(), and int_pc_detach().
{
     int_pc_pin_t* pc_pin = (int_pc_pin_t*) malloc(sizeof(int_pc_pin_t));
     switch (GPIO_PORT(pin)) {
         #if defined(INT_PC_0)
         case INT_PC_0_PORT: {
             pc_pin->pcmsk = &PCMSK0;
             pc_pin->pcicr = &PCICR;
             pc_pin->idx_pin = GPIO_PIN_BIT(pin);
             pc_pin->idx_int = 0;
             pc_pin->config = &int_pc_0;
             return pc_pin;
         } break;
         #endif
         #if defined(INT_PC_1)
         case INT_PC_1_PORT: {
             pc_pin->pcmsk = &PCMSK1;
             pc_pin->pcicr = &PCICR;
             pc_pin->idx_pin = GPIO_PIN_BIT(pin);
             pc_pin->idx_int = 1;
             pc_pin->config = &int_pc_1;
             return pc_pin;
         } break;
         #endif
         #if defined(INT_PC_2)
         case INT_PC_2_PORT: {
             pc_pin->pcmsk = &PCMSK2;
             pc_pin->pcicr = &PCICR;
             pc_pin->idx_pin = GPIO_PIN_BIT(pin);
             pc_pin->idx_int = 2;
             pc_pin->config = &int_pc_2;
             return pc_pin;
         } break;
         #endif
     }
     free(pc_pin);
     return NULL;
 }
int_pc_attach()
bool int_pc_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable a pin change interrupt and attach its ISR callback function.
Pin-change Interrupt ports available
Parameters
pin Board pin value.
function ISR callback.
mode Interrupt operation mode.
Returns
Value that indicates if the operation was successful(true) or not(false).
Definition at line 80 of file int_pc.cpp.
References _BV, ATOMIC, int_pc_t::callbacks, CHANGE, int_pc_pin_t::config, FALLING, int_pc_t::falling, get_int_pc_from_pin(), int_pc_pin_t::idx_int, int_pc_pin_t::idx_pin, int_pc_t::old_state, int_pc_pin_t::pcicr, int_pc_pin_t::pcmsk, pin_read(), RISING, int_pc_t::rising, and set_field_value().
Referenced by SPI::enable().
{
     int_pc_pin_t *int_pc = get_int_pc_from_pin(pin);
     // Verify if pin-change interrupt exists...
     if (int_pc) {
         // Enable interrupt
         ATOMIC({
             // Set callback
             int_pc->config->callbacks[int_pc->idx_pin] = function;
             // Set mode
             int_pc->config->rising  = set_field_value(int_pc->config->rising, int_pc->idx_pin, 1, (((mode == RISING) || (mode == CHANGE))? 1 : 0));
             int_pc->config->falling = set_field_value(int_pc->config->falling, int_pc->idx_pin, 1, (((mode == FALLING) || (mode == CHANGE))? 1 : 0));
             // Activate
             *(int_pc->pcmsk) |= _BV(int_pc->idx_pin);
             *(int_pc->pcicr) |= _BV(int_pc->idx_int);
             // Update state for pin
             int_pc->config->old_state = set_field_value(int_pc->config->old_state, int_pc->idx_pin, 1, pin_read(pin));
         });
         // Make sure we free the space!
         free(int_pc);
         return true;
     }
     return false;
 }
int_pc_detach()
void int_pc_detach (pins_t pin)
Disable a pin change interrupt and detach its ISR callback function.
Parameters
pin Board pin value.
Definition at line 104 of file int_pc.cpp.
References _BV, ATOMIC, int_pc_t::callbacks, int_pc_pin_t::config, int_pc_t::falling, get_int_pc_from_pin(), int_pc_pin_t::idx_int, int_pc_pin_t::idx_pin, int_pc_pin_t::pcicr, int_pc_pin_t::pcmsk, int_pc_t::rising, and set_field_value().
{
     int_pc_pin_t *int_pc = get_int_pc_from_pin(pin);
     // Verify if pin-change interrupt exists...
     if (int_pc) {
         // Disable interrupt
         ATOMIC({
             // Clear callback
             int_pc->config->callbacks[int_pc->idx_pin] = NULL;
             // Clean mode
             int_pc->config->rising  = set_field_value(int_pc->config->rising, int_pc->idx_pin, 1, 0);
             int_pc->config->falling = set_field_value(int_pc->config->falling, int_pc->idx_pin, 1, 0);
             // Deactivate
             *(int_pc->pcmsk) &= ~_BV(int_pc->idx_pin);
             // If any pin defined as interrupt, full disable.
             if (!*(int_pc->pcmsk)) {
                 *(int_pc->pcicr) &= ~_BV(int_pc->idx_int);
             }
         });
         // Make sure we free the space!
         free(int_pc);
     }
 }