AVRLibs: hardware/int_ext.cpp File Reference
int_ext.cpp File Reference
Pin external interrupt library.
#include <hardware/int_ext.h>
Classes
struct int_ext_pin_t
Macros
#define INT_EXT_ISR(vect, int_num)
Used to simplify the external interrupt ISR definition.
Functions
int_ext_pin_t * get_int_ext (volatile uint8_t *reg_int, volatile uint8_t *reg_mode, uint8_t idx_int, uint8_t idx_mode, uint8_t idx_fun)
Private function. Sets the external interrupt info.
int_ext_pin_t * get_int_ext_from_pin (pins_t pin)
Private function. Get the pin external interrupt info.
bool int_ext_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable an external interrupt pin and attach its ISR callback function.
void int_ext_detach (pins_t pin)
Disable an external interrupt pin and detach its ISR callback function.
Variables
volatile fun_ptr_vd_vd int_ext_callbacks [INT_EXT_PINS]
Detailed Description
Pin external interrupt library.
Definition in file int_ext.cpp.
Class Documentation
int_ext_pin_t
struct int_ext_pin_t
Definition at line 12 of file int_ext.cpp.
Class Members
uint8_t idx_fun Interrupt callback number.
uint8_t idx_int Interrupt number.
uint8_t idx_mode Interrupt mode field position.
volatile uint8_t * reg_int Interrupt enable register.
volatile uint8_t * reg_mode Interrupt mode register.
Macro Definition Documentation
INT_EXT_ISR
#define INT_EXT_ISR (vect, int_num)
Value:
ISR(vect) {                         \
        int_ext_callbacks[int_num]();   \
    }
Used to simplify the external interrupt ISR definition.
Parameters
vect ISR vector.
int_num External interrupt number.
Definition at line 112 of file int_ext.cpp.
Function Documentation
get_int_ext()
int_ext_pin_t * get_int_ext (volatile uint8_t * reg_int, volatile uint8_t * reg_mode, uint8_t idx_int, uint8_t idx_mode, uint8_t idx_fun)
Private function. Sets the external interrupt info.
Parameters
reg_int Pointer to external interrupt mask register.
reg_mode Pointer to external interrupt control register.
idx_int External interrupt enable index (on interrupt mask register).
idx_mode External interrupt mode index (on interrupt control register).
idx_fun ISR function handler index.
Returns
External interrupt info int_ext_pin_t.
Definition at line 79 of file int_ext.cpp.
References int_ext_pin_t::idx_fun, int_ext_pin_t::idx_int, int_ext_pin_t::idx_mode, int_ext_pin_t::reg_int, and int_ext_pin_t::reg_mode.
Referenced by get_int_ext_from_pin().
{
     int_ext_pin_t* ext_pin = (int_ext_pin_t*) malloc(sizeof(int_ext_pin_t));
     ext_pin->reg_int  = reg_int;
     ext_pin->reg_mode = reg_mode;
     ext_pin->idx_int  = idx_int;
     ext_pin->idx_mode = idx_mode;
     ext_pin->idx_fun  = idx_fun;
     return ext_pin;
 }
get_int_ext_from_pin()
int_ext_pin_t * get_int_ext_from_pin (pins_t pin)
Private function. Get the pin external interrupt info.
Parameters
pin Board pin value.
Returns
External interrupt info int_ext_pin_t.
Definition at line 90 of file int_ext.cpp.
References get_int_ext().
Referenced by int_ext_attach(), and int_ext_detach().
{
     switch(pin) {
         #if defined(__AVR_ATmega16U4__) || defined(__AVR_ATmega32U4__)
         case PTD0: return get_int_ext(&EIMSK, &EICRA, INT0, ISC00, 0); break;
         case PTD1: return get_int_ext(&EIMSK, &EICRA, INT1, ISC10, 1); break;
         case PTD2: return get_int_ext(&EIMSK, &EICRA, INT2, ISC20, 2); break;
         case PTD3: return get_int_ext(&EIMSK, &EICRA, INT3, ISC30, 3); break;
         case PTE6: return get_int_ext(&EIMSK, &EICRB, INT6, ISC60, 4); break;
         #elif defined(__AVR_Atmega168__) || defined(__AVR_ATmega328P__)
         case PTD2: return get_int_ext(&EIMSK, &EICRA, INT0, ISC00, 0); break;
         case PTD3: return get_int_ext(&EIMSK, &EICRA, INT1, ISC10, 1); break;
         #endif
         default: return NULL; break;
     }
 }
int_ext_attach()
bool int_ext_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable an external interrupt pin and attach its ISR callback function.
External interrupt pins available
Parameters
pin Board pin value.
function ISR callback.
mode Interrupt operation mode.
Returns
Value that indicates if the operation was successful(true) or not(false).
Definition at line 45 of file int_ext.cpp.
References _BV, ATOMIC, get_int_ext_from_pin(), int_ext_pin_t::idx_fun, int_ext_pin_t::idx_int, int_ext_pin_t::idx_mode, int_ext_callbacks, int_ext_pin_t::reg_int, int_ext_pin_t::reg_mode, and set_field_value().
Referenced by SPI::enable().
{
     // Check if interrupt is valid
     int_ext_pin_t* ext_pin = get_int_ext_from_pin(pin);
     if ((ext_pin == NULL) || (function == NULL))
         return false;
     // Attach pin interruption
     ATOMIC({
         *ext_pin->reg_mode = set_field_value(*ext_pin->reg_mode, ext_pin->idx_mode, 2, mode);
         *ext_pin->reg_int |= _BV(ext_pin->idx_int);
     });
     // Set callback
     int_ext_callbacks[ext_pin->idx_fun] = function;
     // Free the space
     free(ext_pin);
     // Return success
     return true;
 }
int_ext_detach()
void int_ext_detach (pins_t pin)
Disable an external interrupt pin and detach its ISR callback function.
Parameters
pin Board pin value.
Definition at line 63 of file int_ext.cpp.
References _BV, ATOMIC, get_int_ext_from_pin(), int_ext_pin_t::idx_fun, int_ext_pin_t::idx_int, int_ext_callbacks, and int_ext_pin_t::reg_int.
{
     // Check if interrupt is valid
     int_ext_pin_t* ext_pin = get_int_ext_from_pin(pin);
     if (ext_pin == NULL)
         return;
     // Detach pin interruption
     ATOMIC({
         *ext_pin->reg_int &= ~_BV(ext_pin->idx_int);
     });
     // Clear callback
     int_ext_callbacks[ext_pin->idx_fun] = NULL;
     // Free the space
     free(ext_pin);
 }
Variable Documentation
int_ext_callbacks
volatile fun_ptr_vd_vd int_ext_callbacks[INT_EXT_PINS]
External interrupt callbacks
Definition at line 22 of file int_ext.cpp.
Referenced by int_ext_attach(), and int_ext_detach().