AVRLibs: hardware/int_pc.h File Reference
int_pc.h File Reference
Pin change interrupt library.
#include <hardware/int_defs.h>
Functions
bool int_pc_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable a pin change interrupt and attach its ISR callback function.
void int_pc_detach (pins_t pin)
Disable a pin change interrupt and detach its ISR callback function.
Detailed Description
Pin change interrupt library.
#include "hardware/int_pc.h"
Definition in file int_pc.h.
Function Documentation
int_pc_attach()
bool int_pc_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable a pin change interrupt and attach its ISR callback function.
Pin-change Interrupt ports available
Parameters
pin Board pin value.
function ISR callback.
mode Interrupt operation mode.
Returns
Value that indicates if the operation was successful(true) or not(false).
Definition at line 80 of file int_pc.cpp.
References _BV, ATOMIC, int_pc_t::callbacks, CHANGE, int_pc_pin_t::config, FALLING, int_pc_t::falling, get_int_pc_from_pin(), int_pc_pin_t::idx_int, int_pc_pin_t::idx_pin, int_pc_t::old_state, int_pc_pin_t::pcicr, int_pc_pin_t::pcmsk, pin_read(), RISING, int_pc_t::rising, and set_field_value().
Referenced by SPI::enable().
{
     int_pc_pin_t *int_pc = get_int_pc_from_pin(pin);
     // Verify if pin-change interrupt exists...
     if (int_pc) {
         // Enable interrupt
         ATOMIC({
             // Set callback
             int_pc->config->callbacks[int_pc->idx_pin] = function;
             // Set mode
             int_pc->config->rising  = set_field_value(int_pc->config->rising, int_pc->idx_pin, 1, (((mode == RISING) || (mode == CHANGE))? 1 : 0));
             int_pc->config->falling = set_field_value(int_pc->config->falling, int_pc->idx_pin, 1, (((mode == FALLING) || (mode == CHANGE))? 1 : 0));
             // Activate
             *(int_pc->pcmsk) |= _BV(int_pc->idx_pin);
             *(int_pc->pcicr) |= _BV(int_pc->idx_int);
             // Update state for pin
             int_pc->config->old_state = set_field_value(int_pc->config->old_state, int_pc->idx_pin, 1, pin_read(pin));
         });
         // Make sure we free the space!
         free(int_pc);
         return true;
     }
     return false;
 }
int_pc_detach()
void int_pc_detach (pins_t pin)
Disable a pin change interrupt and detach its ISR callback function.
Parameters
pin Board pin value.
Definition at line 104 of file int_pc.cpp.
References _BV, ATOMIC, int_pc_t::callbacks, int_pc_pin_t::config, int_pc_t::falling, get_int_pc_from_pin(), int_pc_pin_t::idx_int, int_pc_pin_t::idx_pin, int_pc_pin_t::pcicr, int_pc_pin_t::pcmsk, int_pc_t::rising, and set_field_value().
{
     int_pc_pin_t *int_pc = get_int_pc_from_pin(pin);
     // Verify if pin-change interrupt exists...
     if (int_pc) {
         // Disable interrupt
         ATOMIC({
             // Clear callback
             int_pc->config->callbacks[int_pc->idx_pin] = NULL;
             // Clean mode
             int_pc->config->rising  = set_field_value(int_pc->config->rising, int_pc->idx_pin, 1, 0);
             int_pc->config->falling = set_field_value(int_pc->config->falling, int_pc->idx_pin, 1, 0);
             // Deactivate
             *(int_pc->pcmsk) &= ~_BV(int_pc->idx_pin);
             // If any pin defined as interrupt, full disable.
             if (!*(int_pc->pcmsk)) {
                 *(int_pc->pcicr) &= ~_BV(int_pc->idx_int);
             }
         });
         // Make sure we free the space!
         free(int_pc);
     }
 }