AVRLibs: hardware/int_ext.h File Reference
int_ext.h File Reference
Pin external interrupt library.
#include <hardware/int_defs.h>
Functions
bool int_ext_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable an external interrupt pin and attach its ISR callback function.
void int_ext_detach (pins_t pin)
Disable an external interrupt pin and detach its ISR callback function.
Detailed Description
Pin external interrupt library.
#include "hardware/int_ext.h"
Definition in file int_ext.h.
Function Documentation
int_ext_attach()
bool int_ext_attach (pins_t pin, fun_ptr_vd_vd function, int_mode_t mode)
Enable an external interrupt pin and attach its ISR callback function.
External interrupt pins available
Parameters
pin Board pin value.
function ISR callback.
mode Interrupt operation mode.
Returns
Value that indicates if the operation was successful(true) or not(false).
Definition at line 45 of file int_ext.cpp.
References _BV, ATOMIC, get_int_ext_from_pin(), int_ext_pin_t::idx_fun, int_ext_pin_t::idx_int, int_ext_pin_t::idx_mode, int_ext_callbacks, int_ext_pin_t::reg_int, int_ext_pin_t::reg_mode, and set_field_value().
Referenced by SPI::enable().
{
     // Check if interrupt is valid
     int_ext_pin_t* ext_pin = get_int_ext_from_pin(pin);
     if ((ext_pin == NULL) || (function == NULL))
         return false;
     // Attach pin interruption
     ATOMIC({
         *ext_pin->reg_mode = set_field_value(*ext_pin->reg_mode, ext_pin->idx_mode, 2, mode);
         *ext_pin->reg_int |= _BV(ext_pin->idx_int);
     });
     // Set callback
     int_ext_callbacks[ext_pin->idx_fun] = function;
     // Free the space
     free(ext_pin);
     // Return success
     return true;
 }
int_ext_detach()
void int_ext_detach (pins_t pin)
Disable an external interrupt pin and detach its ISR callback function.
Parameters
pin Board pin value.
Definition at line 63 of file int_ext.cpp.
References _BV, ATOMIC, get_int_ext_from_pin(), int_ext_pin_t::idx_fun, int_ext_pin_t::idx_int, int_ext_callbacks, and int_ext_pin_t::reg_int.
{
     // Check if interrupt is valid
     int_ext_pin_t* ext_pin = get_int_ext_from_pin(pin);
     if (ext_pin == NULL)
         return;
     // Detach pin interruption
     ATOMIC({
         *ext_pin->reg_int &= ~_BV(ext_pin->idx_int);
     });
     // Clear callback
     int_ext_callbacks[ext_pin->idx_fun] = NULL;
     // Free the space
     free(ext_pin);
 }